### ISSUE TITLE
Seems a `MONITORINFOF_PRIMARY` const/enum is not defined/generated when using `PInvoke.GetMonitorInfo()` and `MONITORINFO` struct

### ISSUE THREAD

**Issue by MBODM** [microsoft/CsWin32#1004]
## Actual behavior

Using this code, including the following generated `PInvoke` stuff:

```csharp
var hWnd = PInvoke.GetDesktopWindow();
var hMonitor = PInvoke.MonitorFromWindow(hWnd, MONITOR_FROM_FLAGS.MONITOR_DEFAULTTOPRIMARY);

var mi = new MONITORINFO();
mi.cbSize = (uint)Marshal.SizeOf(mi);
PInvoke.GetMonitorInfo(hMonitor, ref mi);

Console.WriteLine(mi.dwFlags); // Prints "1" to the console.

if (mi.dwFlags == MONITORINFOF_PRIMARY) // Not possible at the moment, in any form.
{
    Console.WriteLine("Hooray!");
}
```

The `MONITORINFO` struct contains a `dwFlags` field. There should be a const/enum or something named `MONITORINFOF_PRIMARY`, to compare the `dwFlags` value with.

Some other `PInvoke` generated functions have those. Example given:
```csharp
Windows.Win32.Graphics.Gdi.MONITOR_FROM_FLAGS.MONITOR_DEFAULTTOPRIMARY
```
exists along with 
```csharp
PInvoke.MonitorFromWindow()
```
function.

**In short:** There is no `MONITORINFOF_PRIMARY` const/enum.

## Expected behavior

There should be a `MONITORINFOF_PRIMARY` const/enum.

## Repro steps

- Use above code
- Generate a `NativeMethods.txt` containing above used function names
- Compile
- Inspect `MONITORINFO.dwFlags` and look around for some `MONITORINFOF_PRIMARY` const/enum
- Read MSDN https://learn.microsoft.com/de-de/windows/win32/api/winuser/ns-winuser-monitorinfo

### Context

- CsWin32 version: `0.3.18-beta`
- Target Framework: `.NET 6`
- LangVersion: `C# 10`

**Comment by AArnott** [comment]
The metadata _does_ declare a `MONITORINFOF_PRIMARY` constant, so if you add that specifically to your `NativeMethods.txt` file, you'll get what you need. 
CsWin32 doesn't auto-generate it because the APIs you're asking for don't directly reference constants -- only enums, structs, and the like. 
If you feel we should be using an enum here instead of a `uint` though, you can open an issue over in the win32metadata repo.

**Comment by MBODM** [comment]
Oh, then i´m sorry!

I didn´t know you can also put in types, structs or consts into the ``NativeMethods.txt` file. If it´s mentioned in the documentation i maybe missed that part. Cause of the file name of the`.txt` file i assumed you can only put in function names in there. And everyting else, related to that function(s), is resolved/created automatically. My bad.

Thanks a lot for clarifying this and sorry when i wasted your sparse time!

**Comment by AArnott** [comment]
No worries. FYI the docs on NativeMethods.txt and what it can contain are here: https://github.com/microsoft/CsWin32#usage

**Comment by MBODM** [comment]
> No worries. FYI the docs on NativeMethods.txt and what it can contain are here: https://github.com/microsoft/CsWin32#usage

Yeah, it seems i missed that part:

>The name of a struct, enum, constant or interface to generate. This may be qualified with a namespace but is only recommended in cases of ambiguity, which CsWin32 will prompt where appropriate.

The name „_NativeMethods_“ missleaded me to „methods/functions only“.

Anyway, all fine and thx for clarifying!
