### ISSUE TITLE
`GetKernelObjectSecurity` should return `bool` instead of `unsafe Windows.Win32.Foundation.BOOL`

### ISSUE THREAD

**Issue by zbalkan** [microsoft/CsWin32#1008]
The signature generated by CsWin32:

```csharp
public static unsafe Windows.Win32.Foundation.BOOL GetKernelObjectSecurity(
SafeHandle Handle,
uint RequestedInformation,
Windows.Win32.Security.PSECURITY_DESCRIPTOR pSecurityDescriptor,
uint nLength,
out uint lpnLengthNeeded)
```

The method returns `unsafe Windows.Win32.Foundation.BOOL` but it should return `bool` in a safe way.

The way to handle `GetKernelObjectSecurity` using conventional P/Invoke calls looks like this:
```csharp
[DllImport("advapi32.dll", SetLastError = true)]
[DefaultDllImportSearchPaths(DllImportSearchPath.System32)]
internal static extern bool GetKernelObjectSecurity(
IntPtr Handle,
int RequestedInformation,
[Out] byte[] pSecurityDescriptor,
uint nLength,
out uint lpnLengthNeeded);
```

The `CsWin32` should look and behave similar, too.

**Comment by zbalkan** [comment]
> It's correct as-is:
> 
> ```c++
> BOOL GetKernelObjectSecurity(...);
> ```

The requirement of using PInvoke is to utilize native API in a managed way, C#, F# or VB.NET, if I understood correctly. Therefore, instead of creating a new `BOOL` type, a `bool` makes more sense. Since the `Windows.Win32.Foundation.BOOL` is already not the actual `BOOL` in C/C++, it's not necessary to have a similar type by adding a new one.

There's a discussion here which they mention the difference and they said that they want to make `Windows.Win32.Foundation.BOOL` behave similar to `bool`. But, I believe, it's better to just use `bool`. 
https://github.com/microsoft/CsWin32/discussions/584

**Comment by Nuklon** [comment]
A bool and BOOL are not equivalent. You can already do if (GetKernelObjectSecurity(...)) in C#.
