### ISSUE TITLE
HRESULT_FROM_WIN32

### ISSUE THREAD

**Issue by Nuklon** [microsoft/CsWin32#1010]
Not entirely sure if it should be posted here or in CsWin32, but this macro would be useful to add (perhaps in HRESULT).

**Comment by AArnott** [comment]
CsWin32 can already generate `HRESULT_FROM_WIN32`. You just have to ask for it in your NativeMethods.txt file.

**Comment by Nuklon** [comment]
Hmm, it didn't get generated for me last time, but it does now, thanks :)
