### ISSUE TITLE
Provide SafeHandle instead of manually calling CredFree

### ISSUE THREAD

**Issue by jnm2** [microsoft/CsWin32#1011]
Right now, we're forced to write `try`...`finally` around a pointer.

This applies to these functions and possibly more:
- https://learn.microsoft.com/en-us/windows/win32/api/wincred/nf-wincred-credreadw
- https://learn.microsoft.com/en-us/windows/win32/api/wincred/nf-wincred-credenumeratew
- https://learn.microsoft.com/en-us/windows/win32/api/wincred/nf-wincred-credgettargetinfow
- https://learn.microsoft.com/en-us/windows/win32/api/wincred/nf-wincred-credreaddomaincredentialsw

```cs
public static unsafe NetworkCredential ReadGenericCredential(string targetName)
{
    if (!PInvoke.CredRead(targetName, (int)CRED_TYPE.CRED_TYPE_GENERIC, out var credentialPointer))
        throw new Win32Exception();

    try
    {
        return new NetworkCredential(
            credentialPointer->UserName.ToString(),
            credentialPointer->CredentialBlob is null
                ? null
                : Marshal.PtrToStringUni(
                    (nint)credentialPointer->CredentialBlob,
                    (int)(credentialPointer->CredentialBlobSize / UnicodeEncoding.CharSize)));
    }
    finally
    {
        PInvoke.CredFree(credentialPointer);
    }
}
```

**Comment by AArnott** [comment]
I'm afraid this is unlikely to be 'fixed' because types like `CREDENTIALW` are not mere handles. SafeHandle can only represent an `IntPtr`. Even if we derived from it to add more fields, as a class it couldn't stand in for the `CREDENTIALW` struct where methods took pointers to it.

**Comment by jnm2** [comment]
I could see it working to have a `CREDENTIALW* Pointer` property on the generated SafeHandle class, but I do see how this could be worse for discoverability.

**Comment by AArnott** [comment]
Thanks for describing more about what you were thinking. But I don't think we're going to go with that. If we find many more types that could fit the same pattern it might be worth it, but as a one-off case, this is too much customization to be worthwhile IMO.
