### ISSUE TITLE
Support custom Dll Import search path for entry point functions

### ISSUE THREAD

**Issue by youyuanwu** [microsoft/CsWin32#1029]
The generated code marks the dll import search path to be system32 path.
But the dll lives in `C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code` 
```cs
namespace Microsoft.ServiceFabric
{
    [GeneratedCode("Microsoft.Windows.CsWin32", "0.3.18-beta+dc807e7787")]
    public static class PInvoke
    {
        public static HRESULT FabricCreateLocalClient(in Guid iid, out void* fabricClient);
        [DefaultDllImportSearchPaths(DllImportSearchPath.System32)]
        public static HRESULT FabricCreateLocalClient(Guid* iid, void** fabricClient);
    }
}
```
So, when using these functions, this error is encountered.
`The specified module could not be found. `

The solution is to support custom values for "DefaultDllImportSearchPaths" in the generated code.

More details can be found here:
https://github.com/youyuanwu/service-fabric-cs/issues/2

**Comment by AArnott** [comment]
Would specifying `System32 | ApplicationDirectory | AssemblyDirectory` be sufficient here? If not, what would be required?

**Comment by youyuanwu** [comment]
`FabricCreateLocalClient` function comes from `FabricClient.dll`. This dll lives inside directory `C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code` and is in the system env:PATH variable.

So to make this work the code needs to find FabricClient.dll in the right directory.
I am not familiar with the dll searching in cs. But given the generated code, I think [DefaultDllImportSearchPaths("C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code")] might work?
Is it possible to look up dll in the system PATH like native application?

**Comment by youyuanwu** [comment]
Using "LoadLibrary" suggested solved the issue.
