### ISSUE TITLE
Generated extension methods do not correctly handle optional array parameters

### ISSUE THREAD

**Issue by BasTossings** [microsoft/CsWin32#1041]
## Actual behavior

For example, the generated extension for `ID2D1Factory.CreateStrokeStyle` is as follows:

```c#
internal static unsafe void CreateStrokeStyle(this winmdroot.Graphics.Direct2D.ID2D1Factory @this, in winmdroot.Graphics.Direct2D.D2D1_STROKE_STYLE_PROPERTIES strokeStyleProperties, float[] dashes, out winmdroot.Graphics.Direct2D.ID2D1StrokeStyle strokeStyle)
	{
	fixed (winmdroot.Graphics.Direct2D.D2D1_STROKE_STYLE_PROPERTIES* strokeStylePropertiesLocal = &strokeStyleProperties)
		{
		@this.CreateStrokeStyle(strokeStylePropertiesLocal, dashes, (uint )dashes.Length, out strokeStyle);
		}
	}
```

The official API [documentation](https://learn.microsoft.com/en-us/windows/win32/api/d2d1/nf-d2d1-id2d1factory-createstrokestyle(constd2d1_stroke_style_properties_constfloat_uint32_id2d1strokestyle)) states `dashes` is `[in, optional]`.

when you call `CreateStrokeStyle` with dashes set to `null`, you get a `NullReferenceException` on `(uint )dashes.Length`.

## Expected behavior

The generated extension methods should test for `null` on optional array parameters.

## Repro steps

1. `NativeMethods.txt` content:
```
ID2D1Factory
```

2. `NativeMethods.json` content (if present):
```json
{
  "$schema": "https://aka.ms/CsWin32.schema.json",
  "public": false,
  "allowMarshaling": true
}
```

3. Any of your own code that should be shared?

### Context

- CsWin32 version: `0.3.18-beta`
- Win32Metadata version (if explicitly set by project): n/a
- Target Framework: `net7.0`
- `LangVersion` (if explicitly set by project): n/a

**Comment by AArnott** [comment]
Thanks for the excellent report.
