### ISSUE TITLE
ClientToScreen has a `ref POINT` parameter instead of `out POINT`

### ISSUE THREAD

**Issue by jnm2** [microsoft/CsWin32#105]
This makes the API less nice to use. 

https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-clienttoscreen:

> `lpPoint`
>
> A pointer to a POINT structure that contains the client coordinates to be converted. The new screen coordinates are copied into this structure if the function succeeds.

Not sure this is different from any other place where `out` would be used.

**Comment by AArnott** [comment]
> that contains the client coordinates _to be converted_

This isn't supposed to be `out`. Per the docs, you are expected to pass a value in and then the function changes it. So `ref` is the appropriate choice here.

**Comment by jnm2** [comment]
My bad, thanks. I was using it to map the window origin to the screen.
