### ISSUE TITLE
IPropertyStore, RECT, etc. generated with non-public visibility

### ISSUE THREAD

**Issue by riverar** [microsoft/CsWin32#1099]
## Actual behavior

`IPropertyStore` and other types are generated with **internal** visibility, which is unexpected and hard to work with.

## Expected behavior

**Public** visibility like other types and methods generated by CsWin32.

## Repro steps

`NativeMethods.txt` content:
```
IPropertyStore
```

Results in:

```csharp
// ...
namespace Windows.Win32
{
	namespace UI.Shell.PropertiesSystem
	{
		[Guid("886D8EEB-8CF2-4446-8D02-CDBA1DBDCF99"),InterfaceType(ComInterfaceType.InterfaceIsIUnknown),ComImport()]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.3.49-beta+91f5c15987")]
		internal interface IPropertyStore
// ...
```

### Context

- CsWin32 version: **0.3.49-beta**
- Win32Metadata version (if explicitly set by project):
- Target Framework: **net8.0-windows10.0.19041.0**
- `LangVersion` (if explicitly set by project): [e.g. `9`]

**Comment by riverar** [comment]
Just realized there's a `NativeMethods.json` ([schema](https://raw.githubusercontent.com/microsoft/CsWin32/main/src/Microsoft.Windows.CsWin32/settings.schema.json)), where I can specify `"public": true`. Neat. Maybe we can add a schema link to the README?

**Comment by AArnott** [comment]
> Public visibility like other types and methods generated by CsWin32.

CsWin32 doesn't generate _anything_ as `public` by default unless the C# specification requires it (e.g. operators). Or if you see otherwise, it's a bug in the generator, as the goal is to not add any public types to the receiving assembly unless the project opts in, as you've discovered.

I'll add a link to the schema as you suggest.

**Comment by riverar** [comment]
Thanks @aarnott, the `"public": true` is working great stepping stone as I migrate a large project over.
