### ISSUE TITLE
It's not pleasant to pass nulls (IntPtr.Zero) to optional SafeHandle parameters

### ISSUE THREAD

**Issue by jnm2** [microsoft/CsWin32#110]
Currently, I have to do this: `hbrFlickerFreeDraw: new(IntPtr.Zero, ownsHandle: false)`

It would be nice if .NET natively supported passing a null reference instead of creating an invalid ` SafeHandle` instance, but IIRC it doesn't. Can friendly overloads help with that?

For example, https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-drawiconex gets a `DeleteObjectSafeHandle hbrFlickerFreeDraw` that I want to pass `null` to. Normally I just declare the DllImport method to use `IntPtr` for that parameter and always pass `IntPtr.Zero`, but that's probably not the best solution.

What if the exposed overload was actually `DeleteObjectSafeHandle? hbrFlickerFreeDraw`, showing that the parameter is optional using C# 8's Nullable Reference Types feature, and the overload called a private IntPtr-based DllImport method using the same sequence of calls that the runtime would make to the SafeHandle, except tolerant of nulls?

**Comment by AArnott** [comment]
We're addressing this by generating the `NullSafeHandle.NullHandle`:

https://github.com/microsoft/CsWin32/blob/3e0f0cd6122a01bd9fda75afd0fa319aa2cd5e01/test/GenerationSandbox.Tests/BasicTests.cs#L131

Although in the older release on nuget.org, you can do this with `DeleteObjectSafeHandle.Null`.

**Comment by jnm2** [comment]
Nice! My suggestion of null-checking overloads was filed at #129.
