### ISSUE TITLE
HRESULT static fields not easily usable in switches

### ISSUE THREAD

**Issue by riverar** [microsoft/CsWin32#1100]
## Actual behavior

```diff
switch(...)
{
-   case HRESULT.S_OK:
    default:
        throw new NotImplementedException();
}
```

```
Error CS9135 A constant value of type 'HRESULT' is expected
```

## Expected behavior

Naturally switch on HRESULT values against compile-time statics.

### Context

- CsWin32 version: **0.3.49-beta**
- Win32Metadata version (if explicitly set by project):
- Target Framework: **net8.0-windows10.0.19041.0**
- `LangVersion` (if explicitly set by project): [e.g. `9`]

**Comment by AArnott** [comment]
Oh boy, I wish we could. 

But C# doesn't allow defining constants typed as a custom struct. That as you see in the error precludes them from being used in a `switch` statement. If HRESULT was an enum it would work, but after a long discussion it was decided that HRESULT should _not_ be expressed as an enum for a few reasons, including:
1. Enums convey an idea of an exhaustive list of allowed values. This isn't actually true, but it almost always is.
2. Enums do not support custom members such as methods or conversion operators, which would make HRESULT much _less_ user friendly in some cases. Extension methods can be defined, but this cannot adequately fill the gap.

So I'm afraid C# forces code to use `if` statements instead.

**Comment by ceztko** [comment]
Of the two arguments I can agree with 2. but 1. looks weak to me, as CsWin32 is already used to create an incomplete list of HRESULT values. Also, other than not providing a fast path for switch scenarios, generating values as readonly properties waste a little memory at runtime. So why not combine the best of two worlds? For example:

```
public struct HRESULT
{
    public enum Values : int
    {
        S_OK = 0,
        // ...
    }

    public static implicit operator Values(HRESULT value) => (Values)(int)value;
}
```

**Comment by AArnott** [comment]
> generating values as readonly properties wastes a little memory at runtime

These are static fields, so we're losing 4 bytes of memory each. We could avoid that by making them property getters instead, but I really wouldn't worry about saving 4 bytes of memory per specially requested HRESULT value.

Your nested enum approach means a lot more casting. Not just in the generated code but in user code, because `HRESULT` will be the type used in all the APIs not `HRESULT.Values`. Especially for users that have to declare their own HRESULT values, enums will be a significant step backward in usability.

**Comment by ceztko** [comment]
> Your nested enum approach means a lot more casting.

Are you concerned more about cost of casting in CPU cycles or requiring manual casting in the user code (or both)? Implicit casting certainly reduces the hassle of having the values being in another type, but as you say `HRESULT` is "open" so there's should be not much fear about castling implicitly an integer to `HRESULT` (currently the cast is explicit).  Also I have no specific technical knowledge about the ability of the compiler to trim trivial operator conversions, but I'm hoping it can do a good job in release builds (won't it?). `enum` as I was suggesting may be overkill: have you also considered for example having the values to be just const integers? Something like the following:

```csharp
public struct HRESULT
{
    int value;

    public const int S_OK = 0;

    public const int S_FALSE = 1;

    public HRESULT(int value)
    {
        this.value = value;
    }

    public static implicit operator int(HRESULT hres) => hres.value;

    public static implicit operator HRESULT(int value) => new HRESULT(value);
}


class Program
{
    public static int Main(string[] _)
    {
        var rc = Foo();
        switch (rc)
        {
            case HRESULT.S_OK:
            {
                break;
            }
            case HRESULT.S_FALSE:
            {
                break;
            }
        }

        return 0;
    }

    static HRESULT Foo()
    {
        return HRESULT.S_FALSE;
    }
}
```

Sorry to keep arguing about this topic again, but I think you've kind of overlooked the switch scenario and the fact that some C rooted developers really want to use it.

**Comment by AArnott** [comment]
I assure you I haven't overlooked the switch scenario.
I'm not concerned at all with the runtime cost of casting. I'm trying to optimize the C# experience.
There are pros and cons each way, and as we've already evaluated it, and nothing has changed in the C# language that would alter the points we considered, I am not interested in spending time reevaluating it.
