### ISSUE TITLE
IPolicyConfig and PolicyConfigClient not created

### ISSUE THREAD

**Issue by DerMagereStudent** [microsoft/CsWin32#1105]
I want to set the default audio endpoint. I need both IPolicyConfig and PolicyConfigClient. I added both into the NativeMethods.txt along with some other classes and interfaces:

```
IMMDeviceEnumerator
MMDeviceEnumerator
IAudioEndpointVolume
IPropertyStore
IPolicyConfig
PolicyConfigClient
```

## Actual behavior

Both IPolicyConfig and PolicyConfigClient are not created

## Expected behavior

I would expect them to be created and usable.

## Repro steps

1. `NativeMethods.txt` content:
```
IPolicyConfig
PolicyConfigClient
```

2. `NativeMethods.json` content (if present):
no json

3. Any of your own code that should be shared?
Not needed the issue is about the source generator only

### Context

- CsWin32 version: [e.g. `0.3.49-beta`] Dont know why 0.4.422-beta is the example. Mine is the highest version there is on nuget
- Win32Metadata version (if explicitly set by project):
I'm referencing `Windows Kits\10\UnionMetadata\10.0.20348.0\Windows.winmd` if thats what is meant
- Target Framework: net6.0-windows10.0.20348.0
- `LangVersion` 10

**Comment by AArnott** [comment]
I [can't find documentation](https://learn.microsoft.com/en-us/search/?terms=IPolicyConfig) for `IPolicyConfig`. Where do you see these APIs that you expect CsWin32 to be able to generate? They aren't in the metadata, so if they are indeed in the win32 SDK, we can move this issue to the win32metadata repo to get it added.

**Comment by DerMagereStudent** [comment]
I'm currently rewriting an application I wrote back in 2021. So I can't recall where I saw these APIs. But I can tell you the COM CLSIDs are:

```
IPolicyConfig:       F8679F50-850A-41CF-9C72-430F290290C8
PolicyConfigClient:  870AF99C-171D-4F9E-AF0D-E63DF40C2BC9
```

I thought they are part of the Windows Core Audio APIs

**Comment by AArnott** [comment]
If you can provide a doc link or the header file they come from, I'll forward to the win32metadata repo for consideration. But without that, we may not be able to do anything.

**Comment by DerMagereStudent** [comment]
Unfortunately, everywhere I look for it, it's only said it's an undocumented COM interface. In [this](https://github.com/microsoft/windows-rs/issues/1355) issue it looks like the header file is called `PolicyConfig.h`. But I can only find custom header files like [these](https://github.com/LizardByte/Sunshine/blob/nightly/src/platform/windows/PolicyConfig.h)

**Comment by AArnott** [comment]
We don't generated undocumented APIs. Looks like you'll have to keep your own declarations for them.
