### ISSUE TITLE
Source generated files are added to compilation with SHA1 algorithm

### ISSUE THREAD

**Issue by jaholme** [microsoft/CsWin32#1125]
## Actual behavior
We are utilizing https://github.com/microsoft/binskim to ensure that we are shipping secure binaries, and one of the issues it flagged is that our binaries are not using SHA256 hashing for source matching to PDBs.  We added the <ChecksumAlgorithm>SHA256</ChecksumAlgorithm> tag to our csproj but we were still failing this analysis step.

Upon further examination using [pdb2xml](https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet-tools/NuGet/Microsoft.DiaSymReader.Pdb2Xml/overview/1.1.0-beta2-23252-02), the CsWin32 generated files are using the insecure SHA1 hashing algorithm:
    <file id="1" name="...\Microsoft.Windows.CsWin32\Microsoft.Windows.CsWin32.SourceGenerator\Windows.Win32.DeleteObjectSafeHandle.g.cs" language="C#" **checksumAlgorithm="SHA1"** checksum="EF-A7-39-E2-E1-3B-98-7C-9B-67-8B-52-4E-D9-AB-25-2D-EB-B2-C2" hasEmbeddedSource="true" />

## Expected behavior

Generated files should utilize the project's defined ChecksumAlgorithm.

## Repro steps

1. `NativeMethods.txt` content:
```
<any api>
```
2. Add <ChecksumAlgorithm>SHA256</ChecksumAlgorithm> to csproj configuration properties.

### Context

- CsWin32 version: 0.3.49-beta
- Win32Metadata version (if explicitly set by project): Not explicitly set
- Target Framework: net8.0-windows
- `LangVersion` : Not explicitly set

**Comment by AArnott** [comment]
Thanks for reporting. My team uses binskim too in combination with CsWin32, and this hasn't come up.
What's more, CsWin32 doesn't invoke any hash algorithm at all (unless you specifically ask for an API that represents it). The `DeleteObjectSafeHandle` class (which is what would presumably be in the file the xml fragment you shared had the path to) certainly doesn't invoke any hashing. I suspect this is rather an issue with how the C# compiler adds source generated files into the pdb, which is outside the scope of CsWin32.

@jasonmalinowski, what do you think?

**Comment by jaholme** [comment]
I was looking at a similar issue in [XAML](https://github.com/dotnet/wpf/issues/7348), and it looks like they solved this by injecting "#pragma checksum" with the correct checksum algorithm in the generated code file.

**Comment by jasonmalinowski** [comment]
It looks like this is https://github.com/dotnet/roslyn/issues/63039. @chsienki any thoughts here?

**Comment by chsienki** [comment]
Huh yeah, looks like the same thing. No workarounds unfortunately, we just need to fix the bug.

**Comment by AArnott** [comment]
Thanks. I'll close here since it sounds like it isn't a CsWin32 bug.
