### ISSUE TITLE
Failed to open generated code in Visual Studio Code

### ISSUE THREAD

**Issue by altamkp** [microsoft/CsWin32#1128]
## Actual behavior

Hi there, 

I have recently started using this library to generate Win32 APIs for my projects. As my go-to IDE is Visual Studio Code, I would like to also view the generated code in VS Code, but it fails to do so currently. I have provided a minimal reproducible example project below.

![image](https://github.com/microsoft/CsWin32/assets/65537185/01e83a34-a3dd-449a-9066-f2198e715225)

I have also tried to open the project in Visual Studio and it works fine.

![image](https://github.com/microsoft/CsWin32/assets/65537185/55c20102-e1a3-45ee-bed3-0a1e2cf3bac9)

## Expected behavior

Being able to open generated source code in VS Code.

## Repro steps

1. `NativeMethods.txt` content:
```
GetVersion
```

2. `NativeMethods.json` content (if present):
Not configured.

3. Any of your own code that should be shared?

[CsWin32Test.zip](https://github.com/microsoft/CsWin32/files/14035863/CsWin32Test.zip)

### Context

- CsWin32 version: 0.3.49-beta
- Win32Metadata version (if explicitly set by project):  default
- Target Framework: net8.0
- `LangVersion` (if explicitly set by project): default

**Comment by AArnott** [comment]
There is nothing CsWin32 can do to improve the VS Code visualization story. Please file an issue with the VS Code folks, possibly targeting the C# extension.
