### ISSUE TITLE
IAudioSessionManager2::GetSessionEnumerator missing parameter

### ISSUE THREAD

**Issue by seanyu0** [microsoft/CsWin32#1129]
IAudioSessionManager2::GetSessionEnumerator should have a parameter in [document](https://learn.microsoft.com/en-us/windows/win32/api/audiopolicy/nf-audiopolicy-iaudiosessionmanager2-getsessionenumerator). But in generated code:
`winmdroot.Media.Audio.IAudioSessionEnumerator GetSessionEnumerator();`
And I check the SDK win32metadata, GetSessionEnumerator have a [out] [retval] parameter.
So the parameter is missing.

`NativeMethods.txt` content:
```
IAudioSessionControl
IAudioSessionControl2
IAudioSessionEnumerator
IAudioSessionEvents
IAudioSessionManager
IAudioSessionManager2
IAudioSessionNotification
IAudioVolumeLevel
IAudioVolumeDuckNotification
```

`NativeMethods.json` content:
```json
{
  "$schema": "https://aka.ms/CsWin32.schema.json",
  "public": true
}
```

- CsWin32 version: 0.3.49-beta
- Win32Metadata version: 58.0.18-preview
- Target Framework: .NET 7
- `LangVersion`: 12

**Comment by AArnott** [comment]
This is by design. The method is declared like this in the metadata:

```cs
unsafe HRESULT GetSessionEnumerator([Out][RetVal] IAudioSessionEnumerator* SessionEnum);
```

Note the `[retval]` attribute on the out parameter. That's an indicator that a projection *may* choose to move the out parameter to the return value position. In .NET, this is the default behavior for COM interfaces, and CsWin32 follows the same pattern.

**Comment by riverar** [comment]
It's not missing an argument. CsWin32 is performing return value transformation here--note how the generated method is returning `IAudioSessionEnumerator`.

You can preserve the original signature by adding, to `NativeMethods.json`:

```json
...
"comInterop": {
    "preserveSigMethods": [
        "IAudioSessionEnumerator.GetSessionEnumerator"
    ]
}
```

**Comment by riverar** [comment]
Drat, @aarnott beat me to it!

**Comment by AArnott** [comment]
@riverar: I'll slow down. I love it when you respond to these issues. :)
