### ISSUE TITLE
Bug: CONNECT_UPDATE_PROFILE cannot be found

### ISSUE THREAD

**Issue by 0x5bfa** [microsoft/CsWin32#1131]
## Actual behavior

CONNECT_UPDATE_PROFILE cannt be found though I added this const to the NativeMethods.txt file.

## Expected behavior

It must be found.

## Repro steps

1. `NativeMethods.txt` content:
```
WNetCancelConnection2
CONNECT_UPDATE_PROFILE
```

2. `NativeMethods.json` content (if present):
```json
```

3. Any of your own code that should be shared?

### Context

- CsWin32 version: 0.1.647-beta
- Win32Metadata version (if explicitly set by project):
- Target Framework: .NET 8
- `LangVersion`: 9

**Comment by AArnott** [comment]
`CONNECT_UPDATE_PROFILE` is a value on an enum in the metadata. When you compile your project, a warning should have been produced telling you to switch asking for `CONNECT_UPDATE_PROFILE` out for asking for the enum type name itself. Do you see that when you build?

**Comment by 0x5bfa** [comment]
I could not find the enum name. Looking at the docs about [WNetCancelConnection2A](https://learn.microsoft.com/en-us/windows/win32/api/winnetwk/nf-winnetwk-wnetcancelconnection2a), I have thought this is defined by #define directive.

**Comment by AArnott** [comment]
When I put `CONNECT_UPDATE_PROFILE` into my NativeMethods.txt file, I see this warning when building, which tells you the name of the enum to use:

> CsWin32Sandbox\NativeMethods.txt(1,1,1,23): warning PInvoke004: Use the name of the enum that declares this constant: NET_USE_CONNECT_FLAGS

**Comment by 0x5bfa** [comment]
How do I know that enum class before building?

**Comment by AArnott** [comment]
You might not know before building, but since building emits a warning that tells you the enum type name, you can then fix it.
