### ISSUE TITLE
Generate overload that sets `dwLength`?

### ISSUE THREAD

**Issue by chucker** [microsoft/CsWin32#1142]
**Is your feature request related to a problem? Please describe.**
I'm trying to replace custom PInvoke wrappers with this library to reduce brittle code I have to maintain. As an example call, I picked `GlobalMemoryStatusEx`, and found that it didn't initially work as expected.

It turned out that, [similarly to here](https://github.com/microsoft/CsWin32/issues/90#issuecomment-779980236), the root cause was that the metadata [was incorrect](https://github.com/microsoft/win32metadata/issues/1743#issuecomment-1823304532). By explicitly (rather than transitively) referencing a newer `Microsoft.Windows.SDK.Win32Metadata`, the source generator created a slightly different method. Before, it took an `out` parameter, suggesting I didn't have to pass a struct; now, it takes a `ref`.

However, this now means I have to externally initialize the struct's `dwLength`:

```csharp
var status = new Windows.Win32.System.SystemInformation.MEMORYSTATUSEX
{
    dwLength = (uint)Marshal.SizeOf(typeof(Windows.Win32.System.SystemInformation.MEMORYSTATUSEX))
};

if (Windows.Win32.PInvoke.GlobalMemoryStatusEx(ref status))
    return status.ullTotalPhys;
```

This strikes me as unnecessary boilerplate. `Windows.Win32.System.SystemInformation.MEMORYSTATUSEX` is a source generator-emitted type, and `Windows.Win32.PInvoke.GlobalMemoryStatusEx` a source generator-emitted method, so why pass it information it can already know?

**Describe the solution you'd like**
With `friendlyOverloads` enabled, an overload should be offered that skips this boilerplate. In that case, the parameter should revert to being `out`, since there's really no useful information to pass _in_, something like:

```csharp
/// <inheritdoc cref="GlobalMemoryStatusEx(winmdroot.System.SystemInformation.MEMORYSTATUSEX*)"/>
[SupportedOSPlatform("windows5.1.2600")]
internal static unsafe winmdroot.Foundation.BOOL GlobalMemoryStatusEx(out winmdroot.System.SystemInformation.MEMORYSTATUSEX lpBuffer)
{
        var status = new winmdroot.System.SystemInformation.MEMORYSTATUSEX
        {
            dwLength = (uint)Marshal.SizeOf(typeof(Windows.Win32.System.SystemInformation.MEMORYSTATUSEX))
        };

	fixed (winmdroot.System.SystemInformation.MEMORYSTATUSEX* lpBufferLocal = &lpBuffer)
	{
		winmdroot.Foundation.BOOL __result = PInvoke.GlobalMemoryStatusEx(lpBufferLocal);
		return __result;
	}
}
```

…so that I can do:

```csharp
if (Windows.Win32.PInvoke.GlobalMemoryStatusEx(out var status))
    return status.ullTotalPhys;
```

More than that, given that `Windows.Win32.System.SystemInformation.MEMORYSTATUSEX` is emitted by the source generator in the first place, I'm not sure the call to `Marshal.SizeOf` should be even necessary.

```csharp
/// <inheritdoc cref="GlobalMemoryStatusEx(winmdroot.System.SystemInformation.MEMORYSTATUSEX*)"/>
[SupportedOSPlatform("windows5.1.2600")]
internal static unsafe winmdroot.Foundation.BOOL GlobalMemoryStatusEx(out winmdroot.System.SystemInformation.MEMORYSTATUSEX lpBuffer)
{
        var status = new winmdroot.System.SystemInformation.MEMORYSTATUSEX
        {
            dwLength = 64u // we can just determine this at source generation time, no?
        };

	fixed (winmdroot.System.SystemInformation.MEMORYSTATUSEX* lpBufferLocal = &lpBuffer)
	{
		winmdroot.Foundation.BOOL __result = PInvoke.GlobalMemoryStatusEx(lpBufferLocal);
		return __result;
	}
}
```

I apologize if this has been discussed before; I did try to look for similar issues.

**Comment by AArnott** [comment]
This strikes me as unnecessary boilerplate. Windows.Win32.System.SystemInformation.MEMORYSTATUSEX is a source generator-emitted type, and Windows.Win32.PInvoke.GlobalMemoryStatusEx a source generator-emitted method, so why pass it information it can already know?
What you're asking for requires deeper insight
