### ISSUE TITLE
Why is `SHGetStockIconInfo` function is not supported by generator?

### ISSUE THREAD

**Issue by y0ung3r** [microsoft/CsWin32#1159]
Hello!

Why is [SHGetStockIconInfo](https://learn.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shgetstockiconinfo) function is not supported by generator?

`NativeMethods` content:
```
SHGetStockIconInfo 
```

**Context**

- CsWin32 version: [e.g. `0.3.49-beta`]
- Target Framework: `net8.0-windows`

**Comment by AArnott** [comment]
Have you tried building and looking at the error list or output window for warnings? CsWin32 will report that the API is allowed, but not when targeting AnyCPU, because the declared APIs vary by architecture.
