### ISSUE TITLE
DeleteObjectSafeHandle can't be passed to GetObject

### ISSUE THREAD

**Issue by jnm2** [microsoft/CsWin32#116]
The 'h' parameter is currently `CloseHandleSafeHandle` which never matches the API. It should be `DeleteObjectSafeHandle`.

As mentioned at https://github.com/microsoft/CsWin32/issues/111#issuecomment-780273730, ideally there would be strongly-typed safe handles like BitmapSafeHandle so that `GetObject(BitmapSafeHandle h, int c, out BITMAP pv);` is possible.

**Comment by AArnott** [comment]
Fixed by #9
