### ISSUE TITLE
GetModuleHandle with null parameter.

### ISSUE THREAD

**Issue by Samael7777** [microsoft/CsWin32#1166]
## Actual behavior

GetModuleHandle don't works with null on input.

## Expected behavior

GetModuleHandle(null) must returns current module handle, see [https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-getmodulehandlea](url)

## Repro steps

1. `NativeMethods.txt` content:
```
ImmGetDefaultIMEWnd
GetWindowThreadProcessId
GetForegroundWindow
GetKeyboardLayout
GetGUIThreadInfo
GetAncestor
SendMessage
PostMessage
SetWindowsHookEx
CallNextHookEx
UnhookWindowsHookEx
GetModuleHandle
RegisterShellHookWindow
DeregisterShellHookWindow
GetDesktopWindow
RegisterWindowMessage
GetThreadId
```

2. `NativeMethods.json` content (if present):
```
{
	"$schema": "https://aka.ms/CsWin32.schema.json",
	"useSafeHandles": true
}
```

3. Any of your own code that should be shared?

### Context

- CsWin32 version: 0.3.49-beta
- Target Framework: .net 6.0

**Comment by AArnott** [comment]
What do you mean by it doesn't work? Does it fail at runtime?

There are two overloads to the function, and passing null in by itself produces a C# ambiguity error, but that's easily rectified:

```cs
PInvoke.GetModuleHandle((string?)null);
```

**Comment by Samael7777** [comment]
PInvoke.GetModuleHandle(null) causes compiler error. But PInvoke.GetModuleHandle((string?)null) works. Thank you!

**Comment by luojunyuan** [comment]
I won't know that cast hack

**Comment by AArnott** [comment]
@luojunyuan Casting null is just a way to help the C# compiler know which overload to use, since it's ambiguous since `null` will match any overload with a reference type parameter.
