### ISSUE TITLE
How to create instance for `IDesktopWallpaper` COM interface

### ISSUE THREAD

**Issue by seayxu** [microsoft/CsWin32#1168]
**Is your feature request related to a problem? Please describe.**

- [Target:IDesktopWallpaper](https://learn.microsoft.com/en-us/windows/win32/api/shobjidl_core/nn-shobjidl_core-idesktopwallpaper)
- [Built-in and source-generated COM interop](https://learn.microsoft.com/en-us/dotnet/standard/native-interop/comwrappers-source-generation)

```csharp
[Guid("B92B56A9-8B55-4E14-9A89-0199BBB6F93B"),InterfaceType(ComInterfaceType.InterfaceIsIUnknown),ComImport()]
[SupportedOSPlatform("windows8.0")]
[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.3.49-beta+91f5c15987")]
internal interface IDesktopWallpaper
{
}
```

The code not  gen `GeneratedComInterface`,so not gen implement in below.

```csharp
[GeneratedComClass]
internal partial class DesktopWallpaper : IDesktopWallpaper
{
}
```

- https://github.com/microsoft/CsWinRT/issues/1337
- https://github.com/microsoft/CsWinRT/issues/1533

**Comment by AArnott** [comment]
The `[GeneratedComClass]` attribute is unrelated to this source generator. CsWin32 generates all the code necessary for interop of the APIs it emits, as far as I'm aware. I'm not too familiar with that attribute but from the docs you linked to (thank you!) it seems that that triggers a source generator to fill in more. But as a source generator itself, CsWin32 cannot depend on the compiler running any other source generator _after_ itself, so it must be self-sufficient.

Further, I see that both `IDesktopWallpaper` and `DesktopWallpaper` are in the metadata, so I expect both can be emitted by CsWin32.

Can you clarify what it generates and how that falls short to support your scenario?

**Comment by dongle-the-gadget** [comment]
CsWin32 currently uses the built-in COM interop system via `[ComImport]` (when runtime marshalling is enabled), which isn't trimming or AOT compatible. `[GeneratedComClass]` and `[GeneratedComInterface]` are two attributes introduced in .NET 8 to support the new source-generated COM wrappers, which are trimming and AOT compatible.

As far as I'm aware, when an attribute is marked with `[GeneratedComInterface]`, a source generator then provides the `[IUnknownDerivedAttribute<T,TImpl>]` ([source code](https://source.dot.net/#System.Runtime.InteropServices/System/Runtime/InteropServices/Marshalling/IUnknownDerivedAttribute.cs)) attribute for it, which provides metadata for the `StrategyBasedComWrappers` class to initiate RCWs and CCWs for the interface.

**Comment by Gaoyifei1011** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> * [Target:IDesktopWallpaper](https://learn.microsoft.com/en-us/windows/win32/api/shobjidl_core/nn-shobjidl_core-idesktopwallpaper)
> * [Built-in and source-generated COM interop](https://learn.microsoft.com/en-us/dotnet/standard/native-interop/comwrappers-source-generation)
> 
> ```cs
> [Guid("B92B56A9-8B55-4E14-9A89-0199BBB6F93B"),InterfaceType(ComInterfaceType.InterfaceIsIUnknown),ComImport()]
> [SupportedOSPlatform("windows8.0")]
> [global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.3.49-beta+91f5c15987")]
> internal interface IDesktopWallpaper
> {
> }
> ```
> 
> The code not gen ,so not gen implement in below.`GeneratedComInterface`
> 
> ```cs
> [GeneratedComClass]
> internal partial class DesktopWallpaper : IDesktopWallpaper
> {
> }
> ```
> 
> * [Implement interop with .NET source generated `GeneratedComInterface` interfaces CsWinRT#1337](https://github.com/microsoft/CsWinRT/issues/1337)
> * [Add support for generated COM interfaces CsWinRT#1533](https://github.com/microsoft/CsWinRT/issues/1533)



> **Is your feature request related to a problem? Please describe.**
> 
> * [Target:IDesktopWallpaper](https://learn.microsoft.com/en-us/windows/win32/api/shobjidl_core/nn-shobjidl_core-idesktopwallpaper)
> * [Built-in and source-generated COM interop](https://learn.microsoft.com/en-us/dotnet/standard/native-interop/comwrappers-source-generation)
> 
> ```cs
> [Guid("B92B56A9-8B55-4E14-9A89-0199BBB6F93B"),InterfaceType(ComInterfaceType.InterfaceIsIUnknown),ComImport()]
> [SupportedOSPlatform("windows8.0")]
> [global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.3.49-beta+91f5c15987")]
> internal interface IDesktopWallpaper
> {
> }
> ```
> 
> The code not gen ,so not gen implement in below.`GeneratedComInterface`
> 
> ```cs
> [GeneratedComClass]
> internal partial class DesktopWallpaper : IDesktopWallpaper
> {
> }
> ```
> 
> * [Implement interop with .NET source generated `GeneratedComInterface` interfaces CsWinRT#1337](https://github.com/microsoft/CsWinRT/issues/1337)
> * [Add support for generated COM interfaces CsWinRT#1533](https://github.com/microsoft/CsWinRT/issues/1533)

You can use the CoCreateInstance function to create an instance of the interface
你可以使用 CoCreateInstance 函数来创建接口的实例

Samples
例子

IDoManager COM Interface definition
IDoManager COM 接口定义

Reference link / 参考链接：https://learn.microsoft.com/windows/win32/api/deliveryoptimization/nn-deliveryoptimization-idomanager

```
    /// <summary>
    /// IDOManager 接口用于创建新的下载，并枚举现有下载。
    /// </summary>
    [GeneratedComInterface, Guid("400E2D4A-1431-4C1A-A748-39CA472CFDB1")]
    public partial interface IDOManager
    {
        /// <summary>
        /// 创建新的下载。
        /// </summary>
        /// <param name="download">IDODownload 接口指针的地址。</param>
        /// <returns>如果函数成功，则返回 S_OK。 否则，它将返回 HRESULT错误代码。</returns>
        [PreserveSig]
        int CreateDownload([MarshalAs(UnmanagedType.Interface)] out IDODownload download);

        /// <summary>
        /// 检索指向枚举器对象的接口指针，该对象用于枚举现有下载。
        /// </summary>
        /// <param name="category">
        /// 可选。 要用作枚举的类别的属性名称。 nullptr传递将检索所有现有下载。 支持将以下属性作为一个类别。
        /// DODownloadProperty_Id
        /// DODownloadProperty_Uri
        /// DODownloadProperty_ContentId
        /// DODownloadProperty_DisplayName
        /// DODownloadProperty_LocalPath
        /// </param>
        /// <returns>如果函数成功，则返回 S_OK。 否则，它将返回 HRESULT错误代码。</returns>
        [PreserveSig]
        int EnumDownloads(IntPtr category, out IntPtr ppEnum);
    }
```

IDoManager Indicates the CLSID and IID of the interface
IDoManager 接口对应的 CLSID 和 IID
```
        private static Guid CLSID_DeliveryOptimization = new("5B99FA76-721C-423C-ADAC-56D03C8A8007");
        private static Guid IID_DOManager = new("400E2D4A-1431-4C1A-A748-39CA472CFDB1");
```

CoCreateInstance function(in Ole32.dll)
CoCreateInstance 函数（在 Ole32.dll）
```
        /// <summary>
        /// 创建和默认初始化与指定 CLSID 关联的类的单个对象。
        /// 如果只想在本地系统上创建一个对象，请调用 CoCreateInstance 。 若要在远程系统上创建单个对象，请调用 CoCreateInstanceEx 函数。 若要基于单个 CLSID 创建多个对象，请调用 CoGetClassObject 函数。
        /// </summary>
        /// <param name="rclsid">与要用于创建对象的数据和代码关联的 CLSID。</param>
        /// <param name="pUnkOuter">
        /// 如果 为 NULL，则指示对象未作为聚合的一部分创建。 如果为非 NULL，则指向聚合对象的 IUnknown 接口的指针 (控制 IUnknown) 。
        /// </param>
        /// <param name="dwClsContext">管理新创建对象的代码将在其中运行的上下文。 这些值取自枚举 CLSCTX。</param>
        /// <param name="riid">对要用于与对象通信的接口标识符的引用。</param>
        /// <param name="ppv">接收 riid 中请求的接口指针的指针变量的地址。 成功返回后，*ppv 包含请求的接口指针。 失败后，*ppv 包含 NULL。</param>
        [LibraryImport(Ole32, EntryPoint = "CoCreateInstance", SetLastError = false), PreserveSig]
        public static partial int CoCreateInstance(ref Guid rclsid, IntPtr pUnkOuter, CLSCTX dwClsContext, ref Guid riid, out IntPtr ppv);
```

Invoke
调用

```
           private static readonly StrategyBasedComWrappers strategyBasedComWrappers = new();
           int createResult = CoCreateInstance(ref CLSID_DeliveryOptimization, IntPtr.Zero, CLSCTX.CLSCTX_LOCAL_SERVER, ref                                  IID_DOManager, out IntPtr doManagerPointer);

           if (createResult is 0)
                    {
                        IDoManger doManager = (IDOManager)strategyBasedComWrappers.GetOrCreateObjectForComInstance(doManagerPointer, CreateObjectFlags.None);
                    }

```
