### ISSUE TITLE
Add EntryPoint #865 IsElevationRequired

### ISSUE THREAD

**Issue by gumbarros** [microsoft/CsWin32#1170]
**Is your feature request related to a problem? Please describe.**
IsElevationRequired is not generated after adding to `NativeMethods.txt`

**Describe the solution you'd like**
Generate IsElevationRequired

**Describe alternatives you've considered**
```LibraryImportAttribute```

**Additional context**
(https://undoc.airesoft.co.uk/shell32.dll/IsElevationRequired.php)

**Comment by AArnott** [comment]
CsWin32 only generated Win32 members that are in the Win SDK header files and/or are documented. It _appears_ that `IsElevationRequired` (if there is such a function in shell32 as your link suggests) isn't a documented, publicly supported API. Therefore, it wouldn't be in win32metadata and cswin32 wouldn't generate it.
