### ISSUE TITLE
Many Win32 structs (HDC, HMONITOR, etc.) lack the IntPtr conversion operator.

### ISSUE THREAD

**Issue by L00pZBreak3r** [microsoft/CsWin32#1217]
## Actual behavior

Many Win32 structs (HDC, HMONITOR, etc.) lack the IntPtr conversion operator. For example, HWND has such an operator, but HDC does not. So, it's not even possible to check if HDC equals to zero.

## Expected behavior

Maybe it's not a bug, however it's not clear why these stucts lack such an operator. Why does HWND have it and HDC does not?

### Context

- CsWin32 version: 0.3.106, built from the latest source code.
- Win32Metadata: 61.0.15-preview.
- Target Framework: netstandard2.0.
- LangVersion: latest.

**Comment by Nuklon** [comment]
This is because of https://github.com/microsoft/win32metadata/issues/1924.

> So, it's not even possible to check if HDC equals to zero.

That's possible, use Value != null. But yes, some helpers would be useful for some of these types.

**Comment by AArnott** [comment]
It works for me with 0.3.106

```cs
IntPtr p = (HMONITOR)default;
HMONITOR m = (HMONITOR)p;

p = (HWND)default;
HWND h = (HWND)p;
```
