### ISSUE TITLE
Incompatiblity with WinUI Preview 4 (using daily)

### ISSUE THREAD

**Issue by dotMorten** [microsoft/CsWin32#124]
Looks like I'm still hitting some incompatibilities with WinUI and the latest daily (v0.1.362-beta). From my understanding the issues in #59 should have been addressed already.

To repro, create the following project:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0-windows10.0.18362.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17134.0</TargetPlatformMinVersion>
    <RootNamespace>CsWin32Repro</RootNamespace>
    <RestoreAdditionalProjectSources>https://pkgs.dev.azure.com/azure-public/vside/_packaging/winsdk/nuget/v3/index.json;$(RestoreAdditionalProjectSources)</RestoreAdditionalProjectSources>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.CsWin32" Version="0.1.362-beta">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.WinUI" Version="3.0.0-preview4.210210.4" />
  </ItemGroup>
</Project>
```
Next add `Shell_NotifyIcon` to the `NativeMethods.txt` and compile.
Observe these two build errors:

```
1>E:\sources.tmp\CsWin32Repro\CsWin32Repro\Microsoft.Windows.CsWin32\Microsoft.Windows.CsWin32.SourceGenerator\NOTIFYICONDATAW.g.cs(146,25,146,29): error CS0234: The type or namespace name 'Guid' does not exist in the namespace 'Microsoft.System' (are you missing an assembly reference?)
1>E:\sources.tmp\CsWin32Repro\CsWin32Repro\Microsoft.Windows.CsWin32\Microsoft.Windows.CsWin32.SourceGenerator\PInvoke.Shell32.g.cs(49,98,49,104): error CS0208: Cannot take the address of, get the size of, or declare a pointer to a managed type ('NOTIFYICONDATAW')
1>Done building project "CsWin32Repro.csproj" -- FAILED.
```

Remove the WinUI package, and things builds fine.

The first one seems to be able to be addressed with changing `internal System.Guid guidItem;` to `internal global::System.Guid guidItem;` which in turn takes care of the second error.

I'm guessing anything that is using a namespace in the type name should be prefixed with `global::`

**Comment by AArnott** [comment]
It looks from the errors I'm seeing from your repro that I need to install some VC SDKs... trying now...

**Comment by AArnott** [comment]
![image](https://user-images.githubusercontent.com/3548/108308874-bfe8a180-716d-11eb-93cb-5a059f8393a9.png)

**Comment by AArnott** [comment]
I never could get the SDKs to work. But I was able to repro the problem trivially in a test so we can make sure this never regresses.

**Comment by dotMorten** [comment]
Thanks @AArnott . Fix looks great

**Comment by dotMorten** [comment]
Just confirming that 0.1.370-beta works great with WinUI 3. Thank you!

**Comment by dotMorten** [comment]
> I never could get the SDKs to work.

@aarnott FYI if you're hitting this:
![image](https://user-images.githubusercontent.com/1378165/108614886-4e019980-73b3-11eb-8323-7ff5d06f8712.png)

You're missing this:
![image](https://user-images.githubusercontent.com/1378165/108614879-4641f500-73b3-11eb-864f-4b3ae1ea65cb.png)

**Comment by AArnott** [comment]
I never hit that, because your repro used earlier build targets. But I installed all the ones referenced in your repro and it still didn't work.
No worries though. I don't need to at this point.
