### ISSUE TITLE
`ReadFileEx` incorrectly takes a `Span<byte>`

### ISSUE THREAD

**Issue by colejohnson66** [microsoft/CsWin32#1244]
CsWin32 generates a `ReadFileEx` and `WriteFileEx` that take `Span<byte>`. The generated methods increment the reference count on the handle, pin the span, then invoke the native routines. For asynchronous I/O (which these are designed for), this is incorrect. When the native method returns, two issues occur:

1. Decrementing the reference count could inadvertently dispose the safe handle
2. Unpinning the span leaves a GC hold that the underlying I/O driver will be reading from or writing to. could cause the handle to be inadvertently disposed. and leaves a GC hole for the underlying I/O driver to read from or write to.

## Generated code

```csharp
[SupportedOSPlatform("windows5.1.2600")]
internal static unsafe winmdroot.Foundation.BOOL ReadFileEx(SafeHandle hFile, Span<byte> lpBuffer, ref global::System.Threading.NativeOverlapped lpOverlapped, delegate *unmanaged[Stdcall]<uint,uint,global::System.Threading.NativeOverlapped*,void> lpCompletionRoutine)
{
    bool hFileAddRef = false;
    try
    {
        fixed (global::System.Threading.NativeOverlapped* lpOverlappedLocal = &lpOverlapped)
        {
            fixed (byte* lpBufferLocal = lpBuffer)
            {
                winmdroot.Foundation.HANDLE hFileLocal;
                if (hFile is object)
                {
                    hFile.DangerousAddRef(ref hFileAddRef);
                    hFileLocal = (winmdroot.Foundation.HANDLE)hFile.DangerousGetHandle();
                }
                else
                    throw new ArgumentNullException(nameof(hFile));
                winmdroot.Foundation.BOOL __result = PInvoke.ReadFileEx(hFileLocal, lpBufferLocal, (uint )lpBuffer.Length, lpOverlappedLocal, lpCompletionRoutine);
                return __result;
            }
        }
    }
    finally
    {
        if (hFileAddRef)
            hFile.DangerousRelease();
    }
}
```

## Expected behavior

CsWin32 should at least _not_ generate "nice" `Span<byte>` overloads for `ReadFileEx` and `WriteFileEx`.

If you want to go further, you could provide a `Memory<byte>` version that handles pinning, and a completion routine that wraps the users' to unpin it. This is what one has to do anyways to properly use these APIs.

## Repro steps

`NativeMethods.txt` content:
```
ReadFileEx
WriteFileEx
```

### Context

- CsWin32 version: 0.3.106
- Target Framework: `net8.0`
- `LangVersion`: `Latest`

**Comment by AArnott** [comment]
This sounds like a dupe (in area at least) of #1066.
But the two functions you mention wouldn't be included in the fix for that because they are missing an attribute in the metadata. I filed https://github.com/microsoft/win32metadata/issues/1994 to track that.
