### ISSUE TITLE
Regression - Null static property not generated for `HDC` in v0.3.106 (Stable)

### ISSUE THREAD

**Issue by adammw** [microsoft/CsWin32#1258]
## Actual behavior

`HDC.Null` is not generated

## Expected behavior

`HDC.Null` is generated

## Repro steps

1. `NativeMethods.txt` content:
```
EnumDisplayMonitors
```

3. Any of your own code that should be shared?

### Context

- CsWin32 version: v0.3.106 (Stable)
- Win32Metadata version (if explicitly set by project): n/a
- Target Framework: [e.g. `netstandard2.0`] Microsoft.NETCore.App 8.0.7
- `LangVersion` (if explicitly set by project): [e.g. `9`]

Tested working again in v0.3.136 Daily build

Wondering if this is a consequence of it being silently broken in stable release, and https://github.com/microsoft/CsWin32/commit/f9aefcc5afe69c792e4c57d36f903e2d5d87176d inadvertently fixing it.

**Comment by oold** [comment]
I just noticed this after updating the metadata package. `HWND` has lost its `IsNull` property.

**Comment by AArnott** [comment]
`Null` and `IsNull` are indeed working in the latest CI builds, so I'm closing this.
