### ISSUE TITLE
GetIconInfo throws "Pointers cannot reference marshaled structures. Use ByRef instead."

### ISSUE THREAD

**Issue by jnm2** [microsoft/CsWin32#126]
This broke in 0.1.362-beta and works in 0.1.355-beta-gc4a93d0827.

> System.Runtime.InteropServices.MarshalDirectiveException: 'Cannot marshal 'parameter \#2': Pointers cannot reference marshaled structures.  Use ByRef instead.'

Generated code, minus most of the doc comments:

```cs
internal static unsafe bool GetIconInfo(SafeHandle hIcon, out ICONINFO piconinfo)
{
    fixed (ICONINFO*piconinfoLocal = &piconinfo)
    {
        return PInvoke.GetIconInfo(hIcon, piconinfoLocal);
    }
}

[DllImport("User32", ExactSpelling = true, SetLastError = true)]
internal static extern unsafe bool GetIconInfo(SafeHandle hIcon, [Out] ICONINFO*piconinfo);
```

```cs
internal partial struct ICONINFO
{
    /// <summary>
    /// <para>Type: <b>BOOL</b></para>
    /// <para>Specifies whether this structure defines an icon or a cursor. A value of <b>TRUE</b> specifies an icon; <b>FALSE</b> specifies a cursor.</para>
    /// <para><see href = "https://docs.microsoft.com/windows/win32/api//winuser/ns-winuser-iconinfo#members">Read more on docs.microsoft.com</see>.</para>
    /// </summary>
    internal bool fIcon;
    internal uint xHotspot;
    internal uint yHotspot;
    internal HBITMAP hbmMask;
    internal HBITMAP hbmColor;
}
```

`ICONINFO.fIcon` is now declared as `bool` instead of `BOOL`, meaning that `ICONINFO` is no longer blittable.

It looks like this could be a result of https://github.com/microsoft/CsWin32/pull/104.

**Comment by jnm2** [comment]
`ICONINFO.fIcon` is now declared as `bool` instead of `BOOL`, meaning that `ICONINFO` is no longer blittable.

It looks like this could be a result of https://github.com/microsoft/CsWin32/pull/104.

**Comment by AArnott** [comment]
Thanks for catching the regression.
