### ISSUE TITLE
Question: How do I reference Apis class?

### ISSUE THREAD

**Issue by 0x5bfa** [microsoft/CsWin32#1265]
Most of what I want such as FOLDERIDs and BHIDs is in Apis class of every namespace.

How can I reference here?
![image](https://github.com/user-attachments/assets/8d11f8f6-8336-4e05-9b97-9d7200643586)

Thanks!

**Comment by AArnott** [comment]
`Apis` is only a type to serve as a container for ECMA-335 compliance. Projections such as CsWin32 do not typically recreated this in user code. You should ask for the member of `Apis` that you need using `NativeMethods.txt`, and you'll find that under the `PInvoke` class in C#.

**Comment by 0x5bfa** [comment]
Oh I see.

Sorry that I'm asking many questions but I have one more to ask...
How can I use QueryInterface for the class implemented a Com interface IPreviewHandler.Interface?
I implemented my own PreviewHandlerFrame from IPreviewHandlerFrame.
And converted the instance into nint with Marshal.GetComInterfaceFrom...
And casted to (IPreviewHandler*)
It should be able to get IInitializeWithStream and more.
But it returns 0x0000.
Do you have any clue?
