### ISSUE TITLE
NtQueryInformationProcess can not be generated

### ISSUE THREAD

**Issue by NeverMorewd** [microsoft/CsWin32#1282]
## Actual behavior

NtQueryInformationProcess was not generated.

## Expected behavior

NtQueryInformationProcess can be generated after being added to NativeMethods.txt

## Repro steps

1. `NativeMethods.txt` content:
```
NtQueryInformationProcess
PROCESS_BASIC_INFORMATION
```

2. `NativeMethods.json` content (if present):
-

3. Any of your own code that should be shared?

### Context

- CsWin32 version: [0.3.106]
- Win32Metadata version (if explicitly set by project):
- Target Framework: [net6.0;net8.0;netframework48]
- `LangVersion` (if explicitly set by project): [12]

**Comment by Ephron-WL** [comment]
I see this generated under Windows.Wdk.PInvoke.NtQueryInformationProcess using Microsoft.Windows.WDK.Win32Metadata 0.11.4.  The function is in the Microsoft.Windows.SDK.Win32Metadata as well, but I see it generated from the WDK.  You shouldn't have to include the structure, in your native methods files since it will be automatically generated.

**Comment by NeverMorewd** [comment]
> I see this generated under Windows.Wdk.PInvoke.NtQueryInformationProcess using Microsoft.Windows.WDK.Win32Metadata 0.11.4. The function is in the Microsoft.Windows.SDK.Win32Metadata as well, but I see it generated from the WDK. You shouldn't have to include the structure, in your native methods files since it will be automatically generated.

Thank you.I see, some functions were generated from Microsoft.Windows.WDK.Win32Metadata which can be accessed by Windows.WDK.PInvoke not Windows.win32.PInvoke.

Could I consider all functions from 'ntdll' are declared in namespace 'Windows.WDK'?

**Comment by Ephron-WL** [comment]
I think it is generally the case, but I wouldn’t guarantee it.

Namespaces (courtesy ILSpy):

***@***.***

**Comment by NeverMorewd** [comment]
Got it, thank you!
