### ISSUE TITLE
`dotnet/pinvoke` is deprecated and should not be recommended

### ISSUE THREAD

**Issue by colejohnson66** [microsoft/CsWin32#1283]
The README recommends using [dotnet/pinvoke](https://github.com/dotnet/pinvoke) if one wants precompiled interop code, but that repository is archived and recommends users switch over to CsWin32.

![image](https://github.com/user-attachments/assets/c3e8c445-56b0-4305-9f8f-871a61f6391b)

![image](https://github.com/user-attachments/assets/e23133ed-5957-4d44-a99e-8619c5daff80)

**Comment by AArnott** [comment]
Good catch. Thank you, @colejohnson66.
