### ISSUE TITLE
Make optional `SafeHandle` parameters accept null

### ISSUE THREAD

**Issue by AArnott** [microsoft/CsWin32#129]
While the .NET interop layer may not permit `null` for `SafeHandle` parameters, we can certainly support it by making the `extern` method `private` and exposing a wrapper to it that checks for `null` SafeHandle args and does the right thing.

Example:

```cs
[DllImport(Entrypoint = "CreateFileW")]
private static extern SafeFileHandle CreateFile_Private(char* path, [Optional, In] SafeHandle hTemplate);

internal static SafeFileHandle CreateFile(char* path, SafeHandle? hTemplate)
{
   return CreateFile_Private(path, hTemplate ?? NullSafeHandle.NullHandle);
}
```

**Comment by jnm2** [comment]
When the project langversion is >= 8, Could you also put `#nullable enable` or at least `#nullable annotations` in the file or around the parameter declaration and use `SafeHandle?` as the parameter type so that IntelliSense shows me the right thing?

**Comment by AArnott** [comment]
@jnm2 yes, I have that in mind to eventually do. I filed an issue to track.
