### ISSUE TITLE
Manually declaring one struct requires the structs it brings in to be manually reincluded

### ISSUE THREAD

**Issue by jnm2** [microsoft/CsWin32#132]
If you have `CreateDIBSection` in NativeMethods.txt and you define your own BITMAPINFO struct as a temporary workaround, you have to add `BITMAPINFOHEADER` to NativeMethods.txt as part of the same workaround.

It seems like it would be cleaner not to have to opt back in to getting BITMAPINFOHEADER, for it to continue to be defined by virtue of `CreateDIBSection` pulling it in. On the other hand, maybe this seems wasteful in case your redefinition of BITMAPINFO is missing the header field. If so, could the custom BITMAPINFO source file be scanned for unqualified references to BITMAPINFOHEADER and declare BITMAPINFOHEADER if the occurrence is an error symbol?

**Comment by AArnott** [comment]
Interesting use case. But if you define a type, we can't inspect it to see if it still needs anything generated to support it. Too many variables to consider to get acceptable results. 
Honestly the primary case for us suppressing generation when a type already exists wasn't even to support hand-authored structs but rather to support cases where you have a reference to another project or assembly that defines the type that was projected over there, in which case it would have to have all its dependencies included as well.
So if you replace a type, you'll have to be responsible to ask for the types you need to complete it.
