### ISSUE TITLE
Length property on inline arrays

### ISSUE THREAD

**Issue by jnm2** [microsoft/CsWin32#169]
PCWSTR has a Length property. Do you see the potential for there to be value in adding one to a fixed-length inline array type? What about variable-length inline arrays, when the metadata supports them?

**Comment by AArnott** [comment]
Fixed length, definitely. Wanna send a pull request?

Variable length... maybe. We'll see if the metadata ever describes it.

**Comment by jnm2** [comment]
Sure!

**Comment by jnm2** [comment]
Struct-based GetEnumerator could be fun too, but that's probably too much bloat.

**Comment by AArnott** [comment]
Agreed. Let's leave the enumerator out.
