### ISSUE TITLE
LPARAM should declare an implicit conversion from `nint`

### ISSUE THREAD

**Issue by AArnott** [microsoft/CsWin32#182]
It explicitly converts `nint` to `LPARAM` today, but this should probably be an `implicit` operator.

**Comment by AArnott** [comment]
I agree in general. Where semantics get more significant, data is lost, or the conversion costly, it should be an explicit conversion.
The reason I think it's appropriate here is that `LPARAM` *doesn't mean anything*. It isn't a handle, or a pointer, or anything defined. It means _whatever_ the user wishes it to mean. In C it's `LONG_PTR`, which is `nint` in C#. In C and C# that means `0` should be an acceptable value, but because in CsWin32 `LPARAM` is a struct rather than a `typedef`, `0` is rejected without a cast. That makes coding harder than it needs to be, seemingly with no value to defend it.

**Comment by jnm2** [comment]
Sounds good. I can't speak to the value, unless there's value in saying "oops, this is already an LPARAM, don't pass it to the WPARAM parameter."

**Comment by AArnott** [comment]
`LPARAM` and `WPARAM` are not convertible. Even if both are implicitly convertible to some common type, C# does not make "jumps" through an intermediate type for conversions.

**Comment by jnm2** [comment]
You're right in this case. It does make jumps through intermediate types though, much to my chagrin, preferring to invisibly go through the explicit `int` cast on a custom `double`-wrapping struct rather than the implicit `double` cast, when explicitly casting to `float`. That's off topic though

**Comment by AArnott** [comment]
If you're saying C# will pick an arbitrary type to convert to in order to make two other types convert when there is no direct conversion, even though it may be off-topic, I'm curious to learn about it. Feel free to pollute this issue to educate me. :)

**Comment by AArnott** [comment]
Wow. So many questions. Maybe file a bug on dotnet/csharplang. I can't imagine why that's by design, at least the way it manifests here.

**Comment by jnm2** [comment]
@AArnott Asked at https://github.com/dotnet/csharplang/discussions/4520 in case you want to follow along.
