### ISSUE TITLE
BOOL.Value should be typed as int

### ISSUE THREAD

**Issue by AArnott** [microsoft/CsWin32#186]
Perhaps unbelievably, it has come to my attention that some `BOOL` types carry more than just a binary zero/non-zero state. We should expose this in CsWin32 rather than hide it by only exposing it as `bool`.

**Comment by jnm2** [comment]
Side note in case it's interesting :D C#'s `bool` carries more than just a binary state, too. The fact that it's actually eight bits can be observed this way: https://github.com/dotnet/csharplang/issues/544#issuecomment-300179855

**Comment by AArnott** [comment]
Funny. Well, BOOL is 4 bytes, so `bool` just doesn't quite cut it, *theoretically*.
