### ISSUE TITLE
Generators don't seem to run on .NET 5 Console app

### ISSUE THREAD

**Issue by anaisbetts** [microsoft/CsWin32#192]
My repro steps for trying to get this going:

1. Install the latest public VS2019 (16.9.1)
1. Create a brand new .NET 5 console app
1. Add Microsoft.Windows.SDK.Win32Metadata @ `10.0.19041.5-preview.1`
1. Click on project => Add new Item => Text file "NativeMethods.txt", add `CreateFile` to file
1. In my app:

```cs
using System;
using Microsoft.Windows.Sdk;

namespace MyApp
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}
```

This blows up with:

```
1>C:\Users\ani\code\anaisbetts\MyApp\MyApp\Program.cs(2,17,2,24): error CS0234: The type or namespace name 'Windows' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
```

My project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.SDK.Win32Metadata" Version="10.0.19041.5-preview.1" />
  </ItemGroup>

</Project>
```

**Comment by AArnott** [comment]
You're installing the wrong package. Per our readme file, the package you should install is Microsoft.Windows.CsWin32.

**Comment by anaisbetts** [comment]
hwhoops, thanks for the tip 😅

**Comment by user16307** [comment]
And my project file: "<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.CsWin32" Version="0.2.1-beta">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>"

**Comment by AArnott** [comment]
@user16307 if you look closely, you'll see the problem:
> The type or namespace name 'Windows' does not exist in the namespace 'Microsoft'

It looks like your `using Windows.Win32` directive is being interpreted as being rooted in a `Microsoft` namespace, which isn't as intended. Try applying this change to your project:

```diff
-using Windows.Win32;
+using global::Windows.Win32;
```
