### ISSUE TITLE
Please skip emitting DefaultDllImportSearchPaths on targets < net45

### ISSUE THREAD

**Issue by jnm2** [microsoft/CsWin32#208]
This seems like an easy fix which would be in line with past PRs that keep CsWin32 usable for projects that include a net35 target.

https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.dllimportsearchpath#applies-to

Alternatively, an additional source file could be generated internally defining DefaultDllImportSearchPathsAttribute and DllImportSearchPath. This would have value *if* (1) an assembly compiled for .NET Framework 3.5 was loaded into .NET Framework 4.5+ or .NET Core and (2) the runtime recognized the attributes regardless of which assembly defined them. I don't know about (2) without testing. (1) is fairly likely. For instance, I have a library targeting `net35;net48;net5.0-windows`. If someone uses it in a `net472` project, they will get the `net35` build.

**Comment by AArnott** [comment]
Declaring the attribute ourselves on downlevel TFMs in case newer runtimes will honor them is a fine idea. If you do ever verify that it works, please open a new bug to track your idea of generating the attribute here.
