### ISSUE TITLE
Support making only certain types specified as public in the config.

### ISSUE THREAD

**Issue by AraHaan** [microsoft/CsWin32#213]
I would love if the configuration (currently if I read right it is for making all of them public), However I would like it to also have an optional setting that if set in the json file, makes only the types listed in it public instead.

**Comment by AArnott** [comment]
We generally discourage making the APIs public except for when you're writing a library that intends to expose all the APIs (e.g. the dotnet/pinvoke project).
What is the scenario where you want to expose just some of them?

Also consider that the generated code is not (yet) stable, so exposing any of it as public API is not recommended at this point especially. If you had to, we recommend copying the generated code into your own project to "lock it in".

**Comment by AraHaan** [comment]
I basically have code where I pass in the values in the ``MINIDUMP_TYPE`` enum into an attribute (it must be public and is used to let the user configure what they want in their minidumps), and then the code internally has to then use the value(s) they provide to actually generate the dump. In this case I must make the following from the generator public:
- MINIDUMP_TYPE

and the rest remain as internal/private (since they should only be used by my library itself). On the current version of it on the repository, it does not use the source generator, however I got maintainability issues on it because what I really needed on that enum is to source generate it and the p/invokes but expose only that enum generated from the source generator as public.

> Also consider that the generated code is not (yet) stable, so exposing any of it as public API is not recommended at this point especially. If you had to, we recommend copying the generated code into your own project to "lock it in".

Usually for dbghelp (in this case the ``MINIDUMP_TYPE`` enum) it most likely is stable anyway, likewise I do not want to lock it in because I also want to have it automatically get new enum members as new ones are added (stay in sync always with the windows SDK) as I never know if any of the old members *might*(possibly unlikely to happen but can always happen) randomly change and break the whole thing.

Plus I see no harm with making stuff like source generated enums public while the rest remain private/internal as usually enum values from the type in particular are stable.

I *could* proxy it, however then it would need to be casted and plus it seems that an enum, cannot inherit from another enum to get the members from the internal and autogenerated enum into the public one (with docs) for free without having to be forced to proxy every enum member manually inside of the public one and then having to check the autogenerated code manually to see if anything new is present or not that needs to be proxied as well.

I guess enums inheriting from enums could be requested to be added to the c# language however 🤔.

**Comment by AArnott** [comment]
Thanks for explaining your scenario.

I'll keep the issue active to track the possibility of requesting specific types/members to be public. I imagine we may implement it by also making anything public that is exposed by something you ask to be public. For example if you asked for a `struct` to be public, all types that support that struct must also be public, so we might do that automatically for you.

**Comment by AArnott** [comment]
Closing as part of focusing on more impactful bugs and features.
And a perhaps superior approach is to copy the generated API that you want to be public into your own code, mark it public, and keep the fully-qualified name of the API exactly the same so that CsWin32 will see and consume it instead of generating the internal equivalent. I say it may be superior because as you upgrade CsWin32, these APIs may silently change, and public API shouldn't do that.
