### ISSUE TITLE
Support making only specific types in a specific namespace in the config.

### ISSUE THREAD

**Issue by AraHaan** [microsoft/CsWin32#214]
I would love if I could list the specific types in the source generator and specify manually which namespace to emit them too in the configuration, instead of emitting ALL of the source generated code to that namespace.

Take for example, if I source generate p/invokes to kernel32.dll, and dbghelp.dll and then expect to be able to do get the following:
- PInvoke class for kernel32 to be emitted to ``ExampleNamespace.PInvokes.Kernel32``.
- PInvoke class for dbghelp to be emitted to ``ExampleNamespace.PInvokes.DbgHelp``.
- Every other type emitted from the Windows SDK (like parameter types) all emitted to the default ``Microsoft.Windows.Sdk`` namespace or to ``Microsoft.Windows.Sdk.Constants`` for constants.

As such I think this would be great and also needed as well too.

**Comment by AArnott** [comment]
Our plans regarding namespaces are in #31. We have no plans to let the user customize it further.

**Comment by AraHaan** [comment]
I guess it could be done with a dummy project that defines each one to a specific namespace, but then other things would have to somehow be excluded as well then too.
