### ISSUE TITLE
P/Invoke methods that set SetLastError to true should return the win32 error code instead of the return value from the native call.

### ISSUE THREAD

**Issue by AraHaan** [microsoft/CsWin32#215]
Let's say for example you p/invoke using the Source Generator at the default settings ``MiniDumpWriteDump``.

Well in the code it then generates (in ``PInvoke.DbgHelp.cs``):

```cs
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable CS1591, CS1573, CS0465, CS0649, CS8019, CS1570, CS1584, CS1658
namespace Microsoft.Windows.Sdk
{
    using global::System;
    using global::System.Diagnostics;
    using global::System.Runtime.CompilerServices;
    using global::System.Runtime.InteropServices;

    /// <content>
    /// Contains extern methods from "DbgHelp.dll".
    /// </content>
    internal static partial class PInvoke
    {
        /// <inheritdoc cref = "MiniDumpWriteDump(HANDLE, uint, HANDLE, MINIDUMP_TYPE, MINIDUMP_EXCEPTION_INFORMATION*, MINIDUMP_USER_STREAM_INFORMATION*, in MINIDUMP_CALLBACK_INFORMATION)"/>
        internal static unsafe bool MiniDumpWriteDump(SafeHandle hProcess, uint ProcessId, SafeHandle hFile, MINIDUMP_TYPE DumpType, MINIDUMP_EXCEPTION_INFORMATION? ExceptionParam, MINIDUMP_USER_STREAM_INFORMATION? UserStreamParam, in MINIDUMP_CALLBACK_INFORMATION CallbackParam)
        {
            bool hProcessAddRef = false;
            bool hFileAddRef = false;
            try
            {
                HANDLE hProcessLocal;
                if (hProcess is object)
                {
                    hProcess.DangerousAddRef(ref hProcessAddRef);
                    hProcessLocal = (HANDLE)hProcess.DangerousGetHandle();
                }
                else
                    hProcessLocal = default(HANDLE);
                HANDLE hFileLocal;
                if (hFile is object)
                {
                    hFile.DangerousAddRef(ref hFileAddRef);
                    hFileLocal = (HANDLE)hFile.DangerousGetHandle();
                }
                else
                    hFileLocal = default(HANDLE);
                MINIDUMP_EXCEPTION_INFORMATION ExceptionParamLocal = ExceptionParam.HasValue ? ExceptionParam.Value : default(MINIDUMP_EXCEPTION_INFORMATION);
                MINIDUMP_USER_STREAM_INFORMATION UserStreamParamLocal = UserStreamParam.HasValue ? UserStreamParam.Value : default(MINIDUMP_USER_STREAM_INFORMATION);
                bool __result = PInvoke.MiniDumpWriteDump(hProcessLocal, ProcessId, hFileLocal, DumpType, ExceptionParam.HasValue ? &ExceptionParamLocal : null, UserStreamParam.HasValue ? &UserStreamParamLocal : null, in CallbackParam);
                return __result;
            }
            finally
            {
                if (hProcessAddRef)
                    hProcess.DangerousRelease();
                if (hFileAddRef)
                    hFile.DangerousRelease();
            }
        }

        /// <summary>Writes user-mode minidump information to the specified file.</summary>
        /// <param name = "hProcess">
        /// <para>A handle to the process for which the information is to be generated.</para>
        /// <para>This handle must have <b>PROCESS_QUERY_INFORMATION</b> and <b>PROCESS_VM_READ</b> access to the process. If handle information is to be collected then <b>PROCESS_DUP_HANDLE</b> access is also required. For more information, see <a href = "https://docs.microsoft.com/windows/desktop/ProcThread/process-security-and-access-rights">Process Security and Access Rights</a>. The caller must also be able to get <b>THREAD_ALL_ACCESS</b> access to the threads in the process. For more information, see <a href = "https://docs.microsoft.com/windows/desktop/ProcThread/thread-security-and-access-rights">Thread Security and Access Rights</a>.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//minidumpapiset/nf-minidumpapiset-minidumpwritedump#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <param name = "ProcessId">The identifier of the process for which the information is to be generated.</param>
        /// <param name = "hFile">A handle to the file in which the information is to be written.</param>
        /// <param name = "DumpType">
        /// <para>The type of information to be generated. This parameter can be one or more of the values from the <a href = "https://docs.microsoft.com/windows/desktop/api/minidumpapiset/ne-minidumpapiset-minidump_type">MINIDUMP_TYPE</a> enumeration.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//minidumpapiset/nf-minidumpapiset-minidumpwritedump#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <param name = "ExceptionParam">
        /// <para>A pointer to a <a href = "https://docs.microsoft.com/windows/win32/api/minidumpapiset/ns-minidumpapiset-minidump_exception_information">MINIDUMP_EXCEPTION_INFORMATION</a> structure describing the client exception that caused the minidump to be generated. If the value of this parameter is <b>NULL</b>, no exception information is included in the minidump file.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//minidumpapiset/nf-minidumpapiset-minidumpwritedump#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <param name = "UserStreamParam">
        /// <para>A pointer to a <a href = "https://docs.microsoft.com/windows/win32/api/minidumpapiset/ns-minidumpapiset-minidump_user_stream_information">MINIDUMP_USER_STREAM_INFORMATION</a> structure. If the value of this parameter is <b>NULL</b>, no user-defined information is included in the minidump file.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//minidumpapiset/nf-minidumpapiset-minidumpwritedump#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <param name = "CallbackParam">
        /// <para>A pointer to a <a href = "https://docs.microsoft.com/windows/win32/api/minidumpapiset/ns-minidumpapiset-minidump_callback_information">MINIDUMP_CALLBACK_INFORMATION</a> structure that specifies a callback routine which is to receive extended minidump information. If the value of this parameter is <b>NULL</b>, no callbacks are performed.</para>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//minidumpapiset/nf-minidumpapiset-minidumpwritedump#parameters">Read more on docs.microsoft.com</see>.</para>
        /// </param>
        /// <returns>
        /// <para>If the function succeeds, the return value is <b>TRUE</b>; otherwise, the return value is <b>FALSE</b>. To retrieve extended error information, call <a href = "/windows/desktop/api/errhandlingapi/nf-errhandlingapi-getlasterror">GetLastError</a>. Note that the last error will be an <b>HRESULT</b> value.</para>
        /// <para>If the operation is canceled, the last error code is <code>HRESULT_FROM_WIN32(ERROR_CANCELLED)</code>.</para>
        /// </returns>
        /// <remarks>
        /// <para><see href = "https://docs.microsoft.com/windows/win32/api//minidumpapiset/nf-minidumpapiset-minidumpwritedump">Learn more about this API from docs.microsoft.com</see>.</para>
        /// </remarks>
        [DllImport("DbgHelp", ExactSpelling = true, SetLastError = true)]
        [DefaultDllImportSearchPaths(DllImportSearchPath.System32)]
        internal static extern unsafe bool MiniDumpWriteDump(HANDLE hProcess, uint ProcessId, HANDLE hFile, MINIDUMP_TYPE DumpType, [Optional] MINIDUMP_EXCEPTION_INFORMATION*ExceptionParam, [Optional] MINIDUMP_USER_STREAM_INFORMATION*UserStreamParam, in MINIDUMP_CALLBACK_INFORMATION CallbackParam);
    }
}
```

However there are a few nits I have with the generated code:
- does not use ``ref`` instead of pointers.
- the types to CallbackParam and UserStreamParam could be skipped by the source generator and be replaced with ``IntPtr`` so one can pass ``IntPtr.Zero`` to basically pass a nullptr like in native code.
- hProcess, and hFile can be an ``IntPtr`` (I think ``DangerousGetHandle`` returns IntPtr) So HANDLE can be skipped from being generated as well too on this api call.
- the generated method that generates with ``SafeHandle`` should return ``int`` instead of bool, discard the native (bool) result from the native call, and return ``Marshal.GetLastWin32Error()``.
- the generated struct ``MINIDUMP_EXCEPTION_INFORMATION`` does not use ``IntPtr`` for the ``ExceptionPointers`` member and instead generates the ``EXCEPTION_POINTERS`` type for that member and then that member is a pointer to it (which can also be replaced with ``IntPtr`` as ``Marshal.GetExceptionPointers()`` returns it as an ``IntPtr``.
- a lot of wrapper classes/structs (like ``HANDLE``) can be replaced with IntPtr instead of providing implicit conversions to/from IntPtr.
- The enum ``MINIDUMP_TYPE`` lacks the ``Flags`` attribute.

I can file issues for each of my nits at the respective places wherever they need to be filed at (if not this repository).

Note: if the following above can be applied the generated method using ``SafeHandle`` could look like this:
```cs
        /// <inheritdoc cref = "MiniDumpWriteDump(IntPtr, uint, IntPtr, MINIDUMP_TYPE, ref MINIDUMP_EXCEPTION_INFORMATION, IntPtr, IntPtr)"/>
        internal static int MiniDumpWriteDump(SafeHandle hProcess, uint ProcessId, SafeHandle hFile, MINIDUMP_TYPE DumpType, ref MINIDUMP_EXCEPTION_INFORMATION ExceptionParam, IntPtr UserStreamParam, IntPtr CallbackParam) // unsafe might not be needed anymore with using IntPtr and ref instead.
        {
            bool hProcessAddRef = false;
            bool hFileAddRef = false;
            try
            {
                IntPtr hProcessLocal;
                if (hProcess is object)
                {
                    hProcess.DangerousAddRef(ref hProcessAddRef);
                    hProcessLocal = hProcess.DangerousGetHandle();
                }
                else
                    hProcessLocal = IntPtr.Zero;
                IntPtr hFileLocal;
                if (hFile is object)
                {
                    hFile.DangerousAddRef(ref hFileAddRef);
                    hFileLocal = hFile.DangerousGetHandle();
                }
                else
                    hFileLocal = IntPtr.Zero;
                _ = PInvoke.MiniDumpWriteDump(hProcessLocal, ProcessId, hFileLocal, DumpType, ExceptionParam, UserStreamParam, CallbackParam);
                return Marshal.GetLastWin32Error();
            }
            finally
            {
                if (hProcessAddRef)
                    hProcess.DangerousRelease();
                if (hFileAddRef)
                    hFile.DangerousRelease();
            }
        }
```

**Comment by AArnott** [comment]
> does not use `ref` instead of pointers.

I don't see any pointers in the friendly overload, so I don't understand your complaint here.

> the types to CallbackParam and UserStreamParam could be skipped by the source generator and be replaced with IntPtr so one can pass IntPtr.Zero to basically pass a nullptr like in native code.

- [ ] I see what you mean by CallbackParam and we can look into that.
- UserStreamParam is a pointer in one cane and an `Optional<T>` struct in the other, so it *does* in fact allow `null` to be provided as the argument.

We try to avoid using `IntPtr` as that is the hardest to do memory management for in C#, besides losing all type information which makes it hard to know which struct to allocate memory for as well.

> hProcess, and hFile can be an IntPtr (I think DangerousGetHandle returns IntPtr) So HANDLE can be skipped from being generated as well too on this api call.

`HANDLE` is just a struct that wraps an `IntPtr` for added type safety. The C headers themselves take `HANDLE` here. If what you have is an `IntPtr`, you can pass it in just be explicitly casting it to `HANDLE`: `(HANDLE)myIntPtr`

> the generated method that generates with SafeHandle should return int instead of bool, discard the native (bool) result from the native call, and return Marshal.GetLastWin32Error().
 
There's no way we can generally know that the `BOOL` is not interesting to the caller, and we don't want to change the behavior of the native method by giving or receiving different values than are documented.

> the generated struct MINIDUMP_EXCEPTION_INFORMATION does not use IntPtr for the ExceptionPointers member and instead generates the EXCEPTION_POINTERS type for that member and then that member is a pointer to it (which can also be replaced with IntPtr as Marshal.GetExceptionPointers() returns it as an IntPtr.

I'm struggling to understand the problem here. We are providing the same API that is available on the native side, and you're wanting *less*. Why is "more" causing a problem for you? If you want to initialize your `MINIDUMP_EXCEPTION_INFORMATION.ExceptionPointers` field with the result from `Marshal.GetExceptionPointers()`, can you simply do this: `info.ExceptionPointers = (EXCEPTION_POINTERS*)Marshal.GetExceptionPointers().ToPointer();` ?
Otherwise if you really want the struct defined with less than the full API that the native side has, you can copy the generated struct into your own code and redefine it (within the same namespace). The source generator will gracefully skip over defining the struct since it sees you have done so.

> a lot of wrapper classes/structs (like HANDLE) can be replaced with IntPtr instead of providing implicit conversions to/from IntPtr.

We intentionally preserve the typedef structs that were on the native side for type safety and recognition of how different handle types are released, which also informs our `SafeHandle` type generation. These typedefs all include implicit conversion operators to their primitive types (usually `IntPtr`) and explicit conversion operators from their primitive type.

> The enum MINIDUMP_TYPE lacks the Flags attribute.

Please file a bug against the metadata repo for this.

**Comment by jnm2** [comment]
> the generated method that generates with SafeHandle should return int instead of bool, discard the native (bool) result from the native call, and return Marshal.GetLastWin32Error().

This is not, in general, safe. Functions don't always reset the last error when they succeed. For example, BitBlt doesn't.

**Comment by jnm2** [comment]
> Otherwise if you really want the struct defined with less than the full API that the native side has, you can copy the generated struct into your own code and redefine it (within the same namespace).

@AArnott Do you also have to remove the `partial` modifier when you do this?

**Comment by AArnott** [comment]
> Do you also have to remove the partial modifier when you do this?

Yes, good point. Otherwise the source generator assumes you just want to add to what it generates.

**Comment by AraHaan** [comment]
> > the types to CallbackParam and UserStreamParam could be skipped by the source generator and be replaced with IntPtr so one can pass IntPtr.Zero to basically pass a nullptr like in native code.
> 
>     * I see what you mean by CallbackParam and we can look into that. Can you please file a separate bug to track just this?

Alright, filed #216.
