### ISSUE TITLE
Namespace collision when used with WinUI 3

### ISSUE THREAD

**Issue by wjk** [microsoft/CsWin32#219]
When you link WinUI 3 into your app, it defines a namespace called `Microsoft.System`. CsWin32 outputs go into `Microsoft.Windows.Sdk`. Notice the common prefix. The generated code (ab)uses a strange quirk of the C# language by placing its using statements inside the namespace body, which changes the algorithm used to look up types. This results in `using System.Runtime.InteropServices` resolving to the namespace `Microsoft.System.Runtime.InteropServices` because of the common prefix. Of course, this namespace doesn’t exist, which breaks the build. Hence, CsWin32 and WinUI 3 cannot coexist in the same project.

The fix here is dead simple: Move the using statements to the top of the file, outside the namespace, which is where they should have been in the first place. When you do this, the using statements will be resolved exactly as they are specified. Thanks!

**Comment by AArnott** [comment]
> The fix here is dead simple: Move the using statements to the top of the file, outside the namespace, which is where they should have been in the first place.

That's one option. There are actually `using` directives that *only* work when *inside* the namespace, just FYI. That isn't the case here, but we already avoid this problem using the `global::` prefix on our `using` directives.

What version of CsWin32 are you using that has this bug? It doesn't repro on 0.1.422-beta, I think.

![image](https://user-images.githubusercontent.com/3548/111820026-9c1c9680-88a6-11eb-810e-fcdb544e480f.png)

**Comment by AArnott** [comment]
See #124 for the original report and fix for the namespace collision.

**Comment by wjk** [comment]
You are correct. This has been fixed since I last used CsWin32 and WinUI 3 together. Thank you for your assistance.

**Comment by AArnott** [comment]
@dotMorten, can you navigate to the generated file and line that produces the error and copy the code snippet into the issue?

**Comment by dotMorten** [comment]
@aarnott Here: Doesn't show any squiggles, so think it is still the xaml precompile step causing it
![image](https://user-images.githubusercontent.com/1378165/113186507-a1fe6a00-920c-11eb-94c0-ae9c7f711650.png)

**Comment by AArnott** [comment]
oh, it's complaining about *your* code, @dotMorten ? I don't know there's anything we can do about that. Try adding `global::` in front of your fully-qualified types on that line.

**Comment by dotMorten** [comment]
@Aarnott Well it's complaining about calling "your" code :-) It's not a namespace collision issue (see last line in my above comment).
I _think_ the xaml precompile step compiles this code prior to the generated code getting included.

**Comment by AArnott** [comment]
Ok, so this looks like a project reunion flavor of #7, but the WPF workaround is apparently not effective in Reunion. I filed https://github.com/dotnet/roslyn/issues/52306 to get this fixed.

**Comment by AArnott** [comment]
This isn't a namespace collision with WinUI which is what this bug was tracking, so I'm going to re-close this issue. We'll open another issue in this repo to track the dotnet/roslyn one.
