### ISSUE TITLE
Add documentation for constants

### ISSUE THREAD

**Issue by AArnott** [microsoft/CsWin32#22]
The `BS_BOTTOM` constant for example *is* documented [here](https://docs.microsoft.com/en-us/windows/win32/controls/button-styles).
Can we scrape that?

**Comment by wieslawsoltes** [comment]
Is this only for documentation or constants will be generated ?

**Comment by AArnott** [comment]
@wieslawsoltes  Many constants are already generated. This is just for adding docs to them. If a constant is missing (and you can't get it by listing it in `NativeMethods.txt` as directed in the README file) then please file a bug against the metadata here: https://github.com/microsoft/win32metadata/issues

**Comment by wieslawsoltes** [comment]
@AArnott Thank you for answer, reported issues in https://github.com/microsoft/win32metadata/issues

**Comment by dotMorten** [comment]
They really aren't constants, but enums or enum-flags. I'd prefer that you generate enums instead. Would be much much easier to code against

**Comment by AArnott** [comment]
@dotMorten: feedback around what constants should be represented within an enum are most welcome, but more effectively directed to https://github.com/microsoft/win32metadata/issues.

Ultimately whether a constant remains as a constant of a class or within an enum, the documentation collection process is the same. The doc processor is in this repo, which is why this issue is here.
