### ISSUE TITLE
WndProc with UnmanagedCallersOnly throws exception for non-blittable parameters.

### ISSUE THREAD

**Issue by mikestek** [microsoft/CsWin32#222]
When using UnmanagedCallersOnly on a WndProc function:
```
[UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]  
private static LRESULT WndProc(HWND hWnd, uint msg, WPARAM wParam, LPARAM lParam)
```

it throws
```
System.InvalidProgramException
  HResult=0x8013153A
  Message=Non-blittable parameter types are invalid for UnmanagedCallersOnly methods.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>
```

Each  parameter structure appears to only contain blittable types so I'm not exactly sure why this is failing.

**Comment by AArnott** [comment]
@mikestek: Where did you get this `WndProc` definition? This doesn't look like anything produced by CsWin32.

**Comment by jnm2** [comment]
@AArnott It looks like the sort of thing you'd define yourself and pass to a native API that takes WindowProc.

**Comment by AArnott** [comment]
Maybe so. 
The calling convention specified in the metadata is `Winapi` rather than `Stdcall` so you might want to fix that. I also didn't expect that attribute to be necessary at all on the method itself. That attribute didn't even exist till .NET 5 so I'd be *very* surprised if it is required.

**Comment by mikestek** [comment]
@AArnott,
sorry, thought I had included this:

It's for the lpfnWndProc in WNDCLASSEXW which is generated as: 
`internal unsafe delegate *unmanaged[Stdcall]<HWND, uint, WPARAM, LPARAM, LRESULT> lpfnWndProc;`

so it is assignable as `lpfnWndProc = &WndProc` with that attribute to set the calling convention.

**Comment by mikestek** [comment]
So it turns out in dotnet 5 the new UnmanagedCallersOnlyAttribute (optimizes and allows taking address of function) doesn't work with functions that return a non-primitive value. The issue is fixed in dotnet 6 as per this runtime issue: https://github.com/dotnet/runtime/issues/35928

What this means is that if using CSWin32 without marshaling in dotnet 5 and you want to pass a function pointer for a function that returns a struct it cannot be done with UnmanagedCallersOnlyAttribute and it needs an ugly cast instead of just getting the address of the function.
