### ISSUE TITLE
CreateCompatibleDC returns HDC but it should return DeleteDCSafeHandle

### ISSUE THREAD

**Issue by jnm2** [microsoft/CsWin32#227]
Referencing Microsoft.Windows.CsWin32 **0.1.432-beta** only.

In **0.1.422-beta**, I could dispose created DCs easily. Now, it looks like I need to declare DeleteDCSafeHandle myself to safely deal with owning this handle.

**Comment by AArnott** [comment]
I can see this repro. Thank you for reporting.

**Comment by AArnott** [comment]
Evidently fixed by 1ef99357eb93fd (v0.1.433-beta).

**Comment by Gavin-Williams** [comment]
Why the weird naming? DeleteDCSafeHandle. Why not HDCSafeHandle?

**Comment by AArnott** [comment]
@gavin-williams The `SafeHandle` names are not human crafted. They are based on the name of the method that releases the handle.
