### ISSUE TITLE
CreateHwndRenderTarget has object as last parameter, should be void** or out object

### ISSUE THREAD

**Issue by bastos80** [microsoft/CsWin32#243]
## Actual behavior

Direct2D's ID2D1Factory.CreateHwndRenderTarget signature seems to be wrong. It takes an object as a last parameter. If I supply null, the call understandably throws an exception. If I supply a boxed IntPtr, the runtime crashes.

## Expected behavior

The last parameter is specified as `ID2D1HwndRenderTarget **hwndRenderTarget` in the API documentation. I.e: it should return the created rendertarget objects interface. I would expect the last parameter to be of the type `void**`, `out object` or `out ID2D1HwndRenderTarget`

## Repro steps

1. `NativeMethods.txt` content:
```
D2D1CreateFactory
ID2D1Factory
```
3. Any of your own code that should be shared?

```c#
var Result = PInvoke.D2D1CreateFactory ( D2D1_FACTORY_TYPE.D2D1_FACTORY_TYPE_SINGLE_THREADED, typeof ( ID2D1Factory ).GUID, new D2D1_FACTORY_OPTIONS (), out var pFactory );
var Factory = Marshal.GetObjectForIUnknown ( new IntPtr ( pFactory ) ) as ID2D1Factory;
var RtProps = new D2D1_RENDER_TARGET_PROPERTIES () { };
var HwndRtProps = new D2D1_HWND_RENDER_TARGET_PROPERTIES () { hwnd = new HWND ( _NativeWindowHandle.ToInt32 () ), pixelSize = new D2D_SIZE_U () { width = 123, height = 123 } };
Factory.CreateHwndRenderTarget ( RtProps, HwndRtProps, null /*!?*/ );
```

### Context

- CsWin32 version: 0.1.422-beta
- Win32Metadata version (if explicitly set by project): n/a
- Target Framework: .NET 5
- `LangVersion` (if explicitly set by project): n/a

**Comment by AArnott** [comment]
The metadata looks correct as the last parameter is declared as `[Out][ComOutPtr] ID2D1HwndRenderTarget* hwndRenderTarget`.
This may be a CsWin32 code generation bug.

**Comment by bastos80** [comment]
I updated to the latest metadata (10.0.19041.5-preview.138) and the problem seems to have corrected itself.
