### ISSUE TITLE
Include transitive closure of dependencies in package

### ISSUE THREAD

**Issue by AArnott** [microsoft/CsWin32#261]
...sticking a debugger onto the Omnisharp process, it appears the generator is throwing an exception. We also seem to be eating the exception rather than reporting it, so we'll need to fix that! But the exception is:

    Could not load file or assembly 'System.Numerics.Vectors, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

Which seems to point to the first problem: the generator package is packaging dependencies like System.Text.Json, but isn't packaging dependencies of System.Text.Json (namely System.Numerics.Vectors):

https://github.com/microsoft/CsWin32/blob/e67e9c55652afa1139409790622c1176e730db02/src/Microsoft.Windows.CsWin32/Microsoft.Windows.CsWin32.targets#L23-L35

So that probably should be updated to copy in the dependency. 

_Originally posted by @jasonmalinowski in https://github.com/microsoft/CsWin32/discussions/218#discussioncomment-696590_

**Comment by AraHaan** [comment]
I think what someone needs to do is walk the dependency trees to all of the dependencies of CsWin32 and then copy them over.

Also I think the ``IsExternalInit.cs`` file can be nuked for the nuget package of the same name that provides that code for the generator.

**Comment by AraHaan** [comment]
Also After looking in Rider don't we also got to include:

- System.Threading.Tasks.Extensions (dependency of the included Microsoft.Bcl.AsyncInterfaces which is dependency of System.Text.Json)
- System.Memory (dependency of System.Text.Json and other dependencies as well)
- System.Buffers (dependency of System.Memory and others)
- System.Runtime.CompilerServices.Unsafe (dependency of System.Text.Json and others)

I will see if I can work out  a patch.

**Comment by AraHaan** [comment]
uh did the bot just remove the commit I made? It does not look to be anywhere in the main branch currently.

**Comment by AArnott** [comment]
Yes, it appears since your PR source branch was `main` that your bot force-pushed your `main` branch to match ours, just before I completed your PR, so there was nothing there. I suggest you create your PRs from a branch with another name.

**Comment by AraHaan** [comment]
Since this is technically a fix to a major issue should a new nuget.org version be pushed?

**Comment by AArnott** [comment]
Yes, I'll be pushing a new one out soon. I want folks to try out tonight's CI build (the one that includes #270) before I push to nuget.org in case there is important feedback to account for.

**Comment by AraHaan** [comment]
ah ok

**Comment by AArnott** [comment]
This 'fix' was ultimately reverted in #843 to solve #836. I found that Omnisharp and Rider still work after this change.
