### ISSUE TITLE
Type 'xxx' already defines a member called 'yyy' with the same parameter compile errors in the generated code. 

### ISSUE THREAD

**Issue by zgabi** [microsoft/CsWin32#263]
## Actual behavior

Type 'xxx' already defines a member called 'yyy' with the same parameter compile errors in the generated code. 

## Expected behavior

No compile error in the generated code.

## Repro steps

1. `NativeMethods.txt` content:
```
D2D1CreateFactory
ID2D1Factory7
DWriteCreateFactory
IDWriteFactory
```

3. Any of your own code that should be shared?

### Context

- CsWin32 version: 0.1.422-beta
- Win32Metadata version (if explicitly set by project): -
- Target Framework: net5.0-windows
- `LangVersion` (if explicitly set by project): -

**Comment by AArnott** [comment]
No repro after #270 was merged. Probably fixed in that large change.
