### ISSUE TITLE
Utilize SupportedArchitectureAttribute to filter metadata to what is compatible in the target compilation

### ISSUE THREAD

**Issue by AArnott** [microsoft/CsWin32#264]
This is required to take the latest metadata update.

When targeting AnyCPU, omit generation of arch-specific members. When targeting any specific architecture, omit members in the metadata that do not apply to it.

When an omitted API is explicitly required (e.g. included in the NativeMethods.txt file), we should emit an error so the user understands that targeting a specific architecture will be required.

**Comment by AArnott** [comment]
As an alternative to *omitting* these APIs, we *could* generate them anyway but with a name change to make it clear where they apply and avoid name collisions when for example a struct is declared twice in metadata with differences based on architecture.

**Comment by marcinkurek** [comment]
So happy that this is being addressed I *just* realized why my project stopped working after moving from P/Invoke to C#/Win32...

**Comment by AraHaan** [comment]
> As an alternative to _omitting_ these APIs, we _could_ generate them anyway but with a name change to make it clear where they apply and avoid name collisions when for example a struct is declared twice in metadata with differences based on architecture.
> 
> The benefit of this option would be that assemblies could continue targeting AnyCPU, which can significantly simplify deployment.

Not to mention isn't there BCL helpers now to get if the AnyCPU code is running in x86, x64, arm, or even arm64?

**Comment by AArnott** [comment]
@arahaan the `RuntimeInformation.ProcessArchitecture` API to perform the runtime check on process architecture is already available as far back as .NET Standard 1.1: https://apisof.net/catalog/25dce236-75f6-f21d-9a94-a94b69143c03.

If/when the source generator emits the APIs that work in all architectures at once rather than just the target one, the generated source would *not* do the runtime discrimination for the app. Instead, the app would have to do it. This is because the types across 32-bit and 64-bit would not be equivalent, as the structs would have to be declared multiple times with slightly different names. The app/library would then have to decide at runtime which struct to initialize and then call the method that accepts that struct, which also may vary by process architecture.

But our initial plan is to go with the design in the issue description, where the app/library doesn't need to worry about runtime checks, but rather if it requires these arch-specific APIs, to target a specific CPU when compiling and then only one method and struct will be generated.
For an app, this shouldn't be too much of a problem because a .NET 5+ app already tends to commit to a specific OS and architecture in order to generate the .exe stub that runs the app. On .NET Framework of course it's possible to have an AnyCPU build .exe because the exe is pure managed code, unlike .NET Core where the stub is native.
For a library that consumes CsWin32, the ideal when requiring these CPU-specific APIs is to target AnyCPU *and* the 3 other architectures. Then pack the anycpu assembly into the ref/ folder of the nuget package and put the CPU-specific ones under the runtimes/ folder.

**Comment by dotMorten** [comment]
I just hit this issue when upgrading to latest.  IMHO this adds a large unnecessary complexity: 

> For a library that consumes CsWin32, the ideal when requiring these CPU-specific APIs is to target AnyCPU and the 3 other architectures. Then pack the anycpu assembly into the ref/ folder of the nuget package and put the CPU-specific ones under the runtimes/ folder.

**Comment by AArnott** [comment]
> since the anycpu ref assembly can't be used at runtime so it affects everyone.

Well, it only affects the *app*. It may not have to impact other libraries (which *may* be AnyCPU) that reference it.

> I'm actually quite surprised that Shell_NotifyIcon is no longer available

That method uses `NOTIFYICONDATAW` in its signature, which has unique packing between the two architectures, evidently. You can compare the metadata we're using as a source to see this for yourself. 

> IMHO this adds a large unnecessary complexity

I get that it adds complexity, but *generally* it *is* necessary. Structs (or even method signatures) can vary in very significant ways across architectures in ways that simply cannot be expressed in AnyCPU. 
If you see specific signatures, structs, etc. that are CPU specific in the metadata, but you believe can be expressed in the metadata in an accurate way with just one AnyCPU declaration, please file a bug against the win32metadata to suggest a change there.

I would love to see a sample, and perhaps even a nuget package that adds the build authoring necessary to build a class library for AnyCPU + the CPU-specific architectures and packs them up properly. One of these days I may build one if no one else has.
