### ISSUE TITLE
CredUIPromptForWindowsCredentials ppvOutAuthBuffer is of type void** and is not and output parameter

### ISSUE THREAD

**Issue by Ssiws** [microsoft/CsWin32#268]
## Actual behavior

Unable to use CredUIPromptForWindowsCredentials because the param `ppvOutAuthBuffer` is missing the `out` modifier

## Expected behavior

I think that `ppvOutAuthBuffer` should be an out param.

## Repro steps

1. `NativeMethods.txt` content:
```
CredUIPromptForWindowsCredentialsW
```

2. `NativeMethods.json` content (if present):
```json
```

3. Any of your own code that should be shared?

``` cs
uint authpkg = 0;
IntPtr outCredBuffer;
uint outCredSize;
PInvoke.CredUIPromptForWindowsCredentials(null, 0, ref authpkg, null, 0, out outCredBuffer, out outCredSize, null, CREDUIWIN_FLAGS.CREDUIWIN_AUTHPACKAGE_ONLY);
```

### Context

- CsWin32 version: 0.1.422-beta
- Win32Metadata version (if explicitly set by project): Tested with version from commit [e025bcd7d0](https://github.com/microsoft/win32metadata/blob/e025bcd7d0b72323eeaa4cb84e2a3d7c1fb81aac/scripts/BaselineWinmd/Windows.Win32.winmd)
- Target Framework: net5.0-windows
- `LangVersion` (if explicitly set by project): 9

**Comment by AArnott** [comment]
After the latest metadata update in #270, the friendly overload for this function now uses the `out` modifier:

```cs
internal static unsafe uint CredUIPromptForWindowsCredentials(win32.Security.CREDUI_INFOW? pUiInfo, uint dwAuthError, ref uint pulAuthPackage, void* pvInAuthBuffer, uint ulInAuthBufferSize, out void* ppvOutAuthBuffer, out uint pulOutAuthBufferSize, bool* pfSave, win32.Security.CREDUIWIN_FLAGS dwFlags)
```
