### ISSUE TITLE
Calling ID2D1Factory.CreateGeometryGroup causes Access violation

### ISSUE THREAD

**Issue by BasTossings** [microsoft/CsWin32#269]
## Actual behavior

When I call `ID2D1Factory.CreateGeometryGroup` with a `geometriesCount` other than `0`, I get the following access violation:

```
Exception thrown at 0x00007FF92F4C8F08 (d2d1.dll) in MyApp.exe: 0xC0000005: Access violation reading location 0x0000000802400011.
```

I suspect the problem has to do with the `ID2D1Geometry[] geometries` argument not being marshaled correctly. The geometries I pass to `CreateGeometryGroup` are all valid and can be used fine on their own.

## Expected behavior

I expect it not to cause an access violation.

## Repro steps

```c#
var Factory = PInvoke.D2D1CreateFactory ( ... );
var Geoms = new ID2D1Geometry[] { ... };
Factory.CreateGeometryGroup ( D2D1_FILL_MODE.D2D1_FILL_MODE_ALTERNATE, Geoms, (uint) Geoms.Length, out var D2DGeometry );
```

1. `NativeMethods.txt` content:
```
D2D1CreateFactory
ID2D1Factory
ID2D1RenderTarget
D2D1_RENDER_TARGET_PROPERTIES
D2D1_HWND_RENDER_TARGET_PROPERTIES
D2D_RECT_F
D2D1_ROUNDED_RECT
D2D1_ELLIPSE
D2D1_FILL_MODE
D2D_MATRIX_3X2_F
D2D1_STROKE_STYLE_PROPERTIES
ID2D1RectangleGeometry
CWPSTRUCT
```

2. `NativeMethods.json` content (if present):
```json
{
  "$schema": "https://aka.ms/CsWin32.schema.json",
  "public": false,
  "allowMarshaling": true
}
```

3. Any of your own code that should be shared?

### Context

- CsWin32 version: `0.4.422-beta`
- Win32Metadata version (if explicitly set by project): `10.0.19041.202-preview`
- Target Framework: `net5.0`
- `LangVersion`: n/a

**Comment by bastos80** [comment]
When I replace the CsWin32 implementation of `ID2D1Factory` with my own, where I modified the signature of `ID2D1Factory.CreateGeometryGroup` with the following:

```c#
unsafe void CreateGeometryGroup ( D2D1_FILL_MODE fillMode, [MarshalAs ( UnmanagedType.CustomMarshaler, MarshalType = "InterfaceArrayMarshaler" )] ID2D1Geometry[] geometries, uint geometriesCount, out ID2D1GeometryGroup geometryGroup );
```

And the following implementation of InterfaceArrayMarshaler:

```c#
    class InterfaceArrayMarshaler : ICustomMarshaler
        {
        public static ICustomMarshaler GetInstance ( string pstrCookie ) => new InterfaceArrayMarshaler ();

        public void CleanUpManagedData ( object ManagedObj )
            {
            }

        public void CleanUpNativeData ( IntPtr pNativeData )
            {
            Marshal.FreeHGlobal ( pNativeData );
            }

        public unsafe int GetNativeDataSize ()
            {
            return sizeof ( IntPtr );
            }

        public unsafe IntPtr MarshalManagedToNative ( object managedObj )
            {
            var Source = (Array) managedObj;
            var ArrayPtr = Marshal.AllocHGlobal ( sizeof ( IntPtr ) * Source.Length );
            var pArray = (IntPtr*) ArrayPtr.ToPointer ();

            for ( int i = 0; i < Source.Length;i++  )
                pArray[i] = Marshal.GetIUnknownForObject ( Source.GetValue ( i ) );

            return ArrayPtr;
            }

        public object MarshalNativeToManaged ( IntPtr pNativeData )
            {
            throw new NotImplementedException ();
            }
        }
```

It works. Obviously this is nothing but a stop-gap solution but it confirmed my suspicion that the marshaling of `ID2D1Geometry[] geometries` is to blame.

**Comment by pziezio** [comment]
Hi,
just like to confirm that this problem occurs in other places too, e.g. `ID3D11DeviceContext`:
Calling generated functions results in AccessViolation exception.

```
[PreserveSig()] void OMSetRenderTargets(uint NumViews, win32.Graphics.Direct3D11.ID3D11RenderTargetView[] ppRenderTargetViews, win32.Graphics.Direct3D11.ID3D11DepthStencilView pDepthStencilView);
[PreserveSig()] unsafe void IASetVertexBuffers(uint StartSlot, uint NumBuffers, win32.Graphics.Direct3D11.ID3D11Buffer[] ppVertexBuffers, [Optional] uint* pStrides, [Optional] uint* pOffsets);
```

Marshaling with just `[MarshalAs(UnmanagedType.LPArray)]` solves the problem.

The only solution for me now is to emit all of the generated sources into single file and manually add MarshalAs to interface-array arguments.

**Comment by AArnott** [comment]
Thank you for the report and for finding the right `[MarshalAs]` attribute that we need to add.

> The only solution for me now is to emit all of the generated sources into single file and manually add MarshalAs to interface-array arguments.

You shouldn't need to copy *all* generated sources into your own files. CsWin32 will happily work around individual types that you declare yourself, so you can pick and choose what to copy over.

**Comment by pziezio** [comment]
> You shouldn't need to copy _all_ generated sources into your own files. CsWin32 will happily work around individual types that you declare yourself, so you can pick and choose what to copy over.

Didn't know that, thanks for the info. That information should probably be somewhere in the readme file.

Is that a feature of code generation mechanism or something that CsWin32 do?

**Comment by AArnott** [comment]
@pziezio good idea. I documented it here: b1be7ba78a95d27c654def4adf7d7ed69227c8e5

It is not a general source generator feature. We have special code in CsWin32 to do it.

**Comment by pziezio** [comment]
> And the following implementation of InterfaceArrayMarshaler:
> It works. Obviously this is nothing but a stop-gap solution but it confirmed my suspicion that the marshaling of `ID2D1Geometry[] geometries` is to blame.

We should also be able to pass null as the array parameter, `InterfaceArrayMarshaler` needs some checking to do that.
I think your implementation is almost equivalent to `[MarshalAs(UnmanagedType.LPArray)]` which does all of that.

E.g. [ID3D11DeviceContext::OMSetRenderTargets](https://docs.microsoft.com/en-us/windows/win32/api/d3d11/nf-d3d11-id3d11devicecontext-omsetrendertargets) requires passing nulls.

**Comment by AArnott** [comment]
Agreed: we should just use `LPArray`'s marshaler.
