### ISSUE TITLE
Period is distractingly styled differently from the rest of the sentence

### ISSUE THREAD

**Issue by jnm2** [microsoft/CsWin32#279]
The period should be part of the link if the entire sentence is a link.

![image](https://user-images.githubusercontent.com/8040367/120229839-05f8db00-c21c-11eb-9751-898998886c59.png)

(0.1.422-beta)

**Comment by AArnott** [comment]
This is a low priority that I will not be addressing. I'd take a PR if you care to send one. Otherwise we should close this.

**Comment by jnm2** [comment]
I'll send one.
