### ISSUE TITLE
ToString override on fixed char array structs

### ISSUE THREAD

**Issue by jnm2** [microsoft/CsWin32#281]
What do you think about generating this line if `T` is `char`?

```diff
 internal struct __char_N
 {
+    public override string ToString() => AsSpan().ToString();
 }
```

Since this is a copy in the same sense as StringBuilder.ToString() or StringWriter.ToString(), or ToArray/ToList/etc, no pointers need to survive the call. That means  System.Memory is not needed for a safe implementation:

```cs
public override string ToString()
{
    unsafe
    {
        fixed (char* p0 = &_0)
            return new string(p0, 0, 256);
    }
}
```

**Comment by jnm2** [comment]
Perhaps ToString should return a string shorter than the length (and AsSpan().Length) if it contains a null terminator. There could be `ToString()` which is guaranteed to never return a string containing a null terminator and `ToFullString()` which is guaranteed to be the same length as the span.

**Comment by AArnott** [comment]
I'm glad you already thought about the `null` character possibility. Your proposal makes sense.
I wonder if it leaves out the possibility of no null termination but a length is specified in the parent struct as another field. In that case, a `ToString(int length)` could potentially be useful. 

`AsSpan().ToString()` honestly doesn't seem too bad though. Are you saying that doesn't work, or simply that you're trying to shorten the amount of code to be written?

**Comment by jnm2** [comment]
I like `ToString(int length)` too. Should it throw ArgumentOutOfRangeException if the length is greater than the fixed array length?

`AsSpan().ToString()` does work, but it lacks the benefit of being obvious, and the other point is that `ToString()` is there whether you like it or not, and whatever choice is made by overriding or not overriding `ToString()`, that will be the default display seen when debugging.

**Comment by AArnott** [comment]
> Should it throw ArgumentOutOfRangeException if the length is greater than the fixed array length?

Yes, that makes sense.

With your points well taken, I'm thinking override `ToString()` to return up to the first null character and `ToString(int)` to return the string of the specified length. 
With those two, I think `ToFullString()` is probably unnecessary so long as the fixed-length struct is generated with a constant that indicates what a full length would be. I don't remember if that's the case.

**Comment by jnm2** [comment]
It makes sense not to provide `ToFullString()` because it doesn't seem like a common scenario. We generate an instance property like `internal int Length => 64;` so that you can consume fixed-length arrays using familiar syntax. Rather than `expr.SomeFixedArray.ToString(expr.SomeFixedArray.Length)`, I think people could just use `expr.AsSpan().ToString()` in this scenario.

The overridden `ToString()` should also stop at the fixed array length if there is no null terminator, right?

**Comment by jnm2** [comment]
What do you think of this template? Is `int` the right type for the `length` parameter and the `Length` property?

```cs
public string ToString(int length)
{
    if (length < 0 || 64 < length)
        throw new ArgumentOutOfRangeException(nameof(length), length, "Length must be between 0 and the fixed array length.");

    unsafe
    {
        fixed (char* p0 = &_0)
            return new string(p0, 0, length);
    }
}

// Can only be emitted if AsSpan is emitted. Span<>.IndexOf is vectorized, so it should be used when available.
// If AsSpan is not emitted, this override could be skipped or a loop could be generated.
public override string ToString()
{
    var terminatorIndex = AsSpan().IndexOf('\0');
    return ToString(terminatorIndex != -1 ? terminatorIndex : 64);
}
```

**Comment by AArnott** [comment]
I like your approach of reviewing the output before going to the code gen phase. That may save a lot of effort.
In this case, I like what you're producing. Only tips are:
1. Use `Length` instead of the `64` magic number. While it will be equivalent and this isn't even user-maintained code, when someone gets the exception, they'll probably look at the code and wonder how they could know the appropriate length to use. Seeing `Length` will inspire them to use the existing property rather than copying the magic number out.
2. Consider using `length > 64` instead of `64 < length`. StyleCop (and I) tend to prefer the variables to the left and constants to the right of operators.

**Comment by jnm2** [comment]
Point 1 sounds great, and I'm okay with point 2. 👍

**Comment by AraHaan** [comment]
> What do you think of this template? Is `int` the right type for the `length` parameter and the `Length` property?
> 
> ```cs
> public string ToString(int length)
> {
>     if (length < 0 || 64 < length)
>         throw new ArgumentOutOfRangeException(nameof(length), length, "Length must be between 0 and the fixed array length.");
> 
>     unsafe
>     {
>         fixed (char* p0 = &_0)
>             return new string(p0, 0, length);
>     }
> }
> 
> // Can only be emitted if AsSpan is emitted. Span<>.IndexOf is vectorized, so it should be used when available.
> // If AsSpan is not emitted, this override could be skipped or a loop could be generated.
> public override string ToString()
> {
>     var terminatorIndex = AsSpan().IndexOf('\0');
>     return ToString(terminatorIndex != -1 ? terminatorIndex : 64);
> }
> ```

Why not use ``AsSpan().Slice(0, length).ToString()`` over needing ``unsafe``?

Besides almost everyone use ``System.Memory`` API's in their codebases already (Well almost everyone that uses compatible frameworks with it).

**Comment by jnm2** [comment]
@AraHaan The answer is given in my original post:

> That means System.Memory is not needed for a safe implementation:

And in the code sample that Andrew approved:

> ```cs
> // Can only be emitted if AsSpan is emitted. Span<>.IndexOf is vectorized, so it should be used when available.
> // If AsSpan is not emitted, this override could be skipped or a loop could be generated.
> ```

> Besides almost everyone use System.Memory API's in their codebases already (Well almost everyone that uses compatible frameworks with it).

I use CsWin32 with a project that necessarily targets `net35;net48;net5.0-windows`.
