### ISSUE TITLE
PCWSTR namespace issues

### ISSUE THREAD

**Issue by bodrick** [microsoft/CsWin32#296]
PCWSTR relies on PWSTR but can't compile because of either PCWSTR should be in the foundation namespace or needs to reference the foundation namespace.

**Comment by AArnott** [comment]
Which version of CsWin32 are you using? We have tests to verify that our generated code can compile, including PCWSTR, so I wonder what's unique about your project that leads to the break.

**Comment by bodrick** [comment]
Here are my package references 
<PackageReference Include="Microsoft.Windows.CsWin32" Version="0.1.478-beta" PrivateAssets="All" />
<PackageReference Include="Microsoft.Windows.SDK.Win32Metadata" Version="10.2.84-preview" />

**Comment by AArnott** [comment]
Thanks. 
It looks like you're jumping ahead with the metadata version. That's not (yet) supported because the metadata keeps changing in breaking ways. See #131.
