### ISSUE TITLE
No code generated with JetBrains Rider

### ISSUE THREAD

**Issue by andi0b** [microsoft/CsWin32#298]
Don't know if it is CsWin32's or Rider's fault. There is also a ticket at JetBrains: https://youtrack.jetbrains.com/issue/RIDER-57026

## Actual behavior

Opening a project with CsWin32 in JetBrains Rider on Windows won't generate any code at all.

All references to CsWin32 generated code wills be marked as errors in red.

Build works; it is done via `dotnet build` and everything is set up correctly.

## Expected behavior

Similar behaviour to Visual Studio. After opening a project or at least after a build code should be generated and available to the IDE. The IDE shouldn't show any errors.

Other source generators work with Rider, the integration of source generators seems to be not so perfect though. 

## Repro steps

1. Open a Project with CsWin32 with JetBrains Rider. For example this repository and one of the samples
2. Build the project and run it - CsWin32 will generate correct code, project will run
3. Rider won't see any generated code (all references red)
4. Rider doesn't show any errors regarding source generators

## Context

Exact versions don't seem to matter. Maybe Linux or MacOS will work, as Rider is using .NET Core on those platforms as a base, but .NET 4.6.x on Windows.

I tried a lot of combinations of those versions/settings:

- CsWin32
  - 0.1.476-beta (winsdk nightly)
  - 0.1.422-beta (nuget.org)
  - 0.1.378-beta (nuget.org)
  - 0.1.319-beta (nuget.org)
- JetBrains Rider
  - 2021.1.3
  - 2021.2 EAP3
- .NET SDK (switched via global.json)
  - 5.0.301
  - 6.0-preview4
- TargetFramework
  - net5.0
  - net6.0
  - netstandard2.0
- LangVersion
  - 9
  - omitted
- Windows 10 21H1

**Comment by AraHaan** [comment]
@andi0b it's rider's fault for not using roslyn and invoking the source generator apis before it actually does the "indexing" which is their way to have their IDE show up any errors in the code.

**Comment by andi0b** [comment]
> it's rider's fault
@AraHaan good to know. I was trying different things for hours to get it work. Maybe this information can be added to the README.

**Comment by AArnott** [comment]
Done in 2c05bc0

**Comment by andi0b** [comment]
@AraHaan What I actually still don't understand what makes CsWin32 different. All other source generators I tried in Rider work perfectly fine. They generate code and everything works. CsWin32 just doesn't seem to do anything. Not even fail.

**Comment by AArnott** [comment]
The symptoms you describe make it sound like maybe Rider isn't initializing the source generators with msbuild's `AdditionalFiles` items, which CsWin32 absolutely requires but perhaps other source generators do not.

**Comment by AraHaan** [comment]
> The symptoms you describe make it sound like maybe Rider isn't initializing the source generators with msbuild's `AdditionalFiles` items, which CsWin32 absolutely requires but perhaps other source generators do not.

I used to use AdditionalFiles myself until I later decided to use compiler exposed MSBuild properties. Perhaps what could be done is the files currently marked under AdditionalFiles could be opened up in an task and then output to an exposed MSBuild property if that file exists within the ``$(MSBuildProjectDirectory)`` (which is the directory of the project itself).

Perhaps that *could* be a test to see if the generator would start working within Rider.

**Comment by AArnott** [comment]
@arahaan, I appreciate the brainstorming, but I'm not going to stop using AdditionalFiles for what they were designed for and dump entire file content into a scalar property value to workaround what ought to be a simple bug fix in Rider. 
If you're interested in doing this as an experiment to inform JetBrains as to what they need to do to fix this scenario in their IDE, you're of course welcome to, but I'm afraid our limited resources require me to spend time fixing and enhancing CsWin32 without much regard to working around bugs in Rider.

**Comment by AraHaan** [comment]
I got email today that the rider issue that is opened for it was closed as ``fixed in branch``. So a new release hopefully will fix it for this, and other source generators.

**Comment by TorbenJ** [comment]
https://youtrack.jetbrains.com/issue/RIDER-57026 related jetbrains issue.  
Works in Rider 2021.2 EAP6 although I have to reload the solution everytime I modify NativeMethods.txt. Rider also hides the txt file after loading the solution again. So there are some rough edges

**Comment by andi0b** [comment]
I can confirm everything works for me now on Rider 2021.2 EAP 6 (pre-release build).

**Comment by andi0b** [comment]
> Works in Rider 2021.2 EAP6 although I have to reload the solution everytime I modify NativeMethods.txt. Rider also hides the txt file after loading the solution again. So there are some rough edges

@TorbenJ: true. This is generally an issue with Rider and source generators, but I can live with that. Unloading and reloading just the project (right click in solution explorer) does the trick. And if I add this to the csproj, the file stays visible in solution explorer:

```xml
<ItemGroup>
    <File Include="NativeMethods.txt" />
</ItemGroup>
```

**Comment by andi0b** [comment]
> Works in Rider 2021.2 EAP6 although I have to reload the solution everytime I modify NativeMethods.txt

New related issue at JetBrians: https://youtrack.jetbrains.com/issue/RIDER-65302
