### ISSUE TITLE
Microsoft.Windows.SDK.Win32Docs.dll appears in build and publish output

### ISSUE THREAD

**Issue by jnm2** [microsoft/CsWin32#316]
## Actual behavior

Microsoft.Windows.SDK.Win32Docs.dll is being added as a runtime dependency for the consuming project.

## Expected behavior

No Windows SDK .dll files appearing as runtime dependencies.

## Repro steps

The only file needed to repro is the .csproj file. This is the package reference metadata created by the NuGet UI, but the problem remains unchanged if you remove the IncludeAssets metadata.

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net4.8</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.CsWin32" Version="0.1.506-beta">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
```

Result:

![image](https://user-images.githubusercontent.com/8040367/124210355-410b5a00-dab9-11eb-81ec-363669989530.png)

**Comment by AArnott** [comment]
Nice catch. Fortunately, an easy fix.
