### ISSUE TITLE
`LPCWSTR []` gets mapped as `Span<PWSTR>` instead of `Span<PCWSTR>`

### ISSUE THREAD

**Issue by jnm2** [microsoft/CsWin32#321]
Possibly related to https://github.com/microsoft/CsWin32/issues/290.

## Actual behavior

[`RmRegisterResources`](https://docs.microsoft.com/en-us/windows/win32/api/restartmanager/nf-restartmanager-rmregisterresources) is given `Span<PWSTR>` parameters.

![image](https://user-images.githubusercontent.com/8040367/125171675-60724900-e183-11eb-88e4-eaa50175253b.png)

## Expected behavior

`Span<PCWSTR>` parameters to indicate that the strings I pin will not be written to by the API.

## Repro steps

1. `NativeMethods.txt` content:
```
RmRegisterResources
```

### Context

- CsWin32 version: `0.1.506-beta`
- Target Framework: `net5.0-windows`

**Comment by colejohnson66** [comment]
Doesn't seem to be an issue in 0.3.49:

![image](https://github.com/microsoft/CsWin32/assets/11381599/9cef9fe4-a81d-44a2-873b-e18624390c4a)

```csharp
internal static unsafe winmdroot.Foundation.WIN32_ERROR RmRegisterResources(
    uint dwSessionHandle, ReadOnlySpan<winmdroot.Foundation.PCWSTR> rgsFileNames,
    Span<winmdroot.System.RestartManager.RM_UNIQUE_PROCESS> rgApplications,
    ReadOnlySpan<winmdroot.Foundation.PCWSTR> rgsServiceNames)
```

**Comment by AArnott** [comment]
Ya, this seems to be fixed. Thanks for noticing, @colejohnson66.

As for exposing this as .NET `string` objects, that would incur allocations, which CsWin32 generally tries to avoid. But it does make creating strings out of them easy, since `PCWSTR.ToString()` is overridden to work as expected.
