### ISSUE TITLE
Direct2D bindings

### ISSUE THREAD

**Issue by jtorjo** [microsoft/CsWin32#327]
**Is your feature request related to a problem? Please describe.**

I want to be able to use Direct2D from a WinUI3 Desktop app. I've been asking for a port of win2d (from UWP to WinUI3 Desktop) for close to 2 years, but there's really no concise answer at this time.

Having Direct2D bindings would actually solve this issue altogether. I would need to rewrite a lot of my code, but I'd be happy to do it, just to be able to port my app to WinUI3 Desktop (right now, it's a UWP app)

**Describe the solution you'd like**

I'd love to have Direct2D bindings, since using Direct2D (or a wrapper, such as win2d) is critical for my app. Clearly in time, I'd love DirectX 11/12 bindings, but Direct2D bindings would be an insanely awesome first step!

**Describe alternatives you've considered**

I'm currently using win2d, which forces me to stay on UWP. I hate that -- I want to be able to port my app to WinUI3 Desktop, but right now I can't. Thus, a lot of awesome stuff from .Net5/.Net6/latest versions of C# are simply unavailable to me. Not to mention UWP compiles orders of magnitude slower than Desktop, has some weird bugs and so on.

There's no decent alternative to win2d at this point, and that's a big shame, since having the ability to draw efficiently is beyond important for any non-trivial GUI app.

**Additional context**

I've started this as a continuation of https://github.com/microsoft/WindowsAppSDK/issues/14

**Comment by wjk** [comment]
@jtorjo I am happy to tell you that there is _finally_ now an easy way to obtain what you are asking. If you download Windows.Win32.winmd and open it in ILSpy, you will find the Direct2D types and interfaces inside the `Windows.Win32.Graphics.Direct2D` namespace. Thanks to #300, you can now just put that namespace by itself on a line in your NativeMethods.txt file and CsWin32 will generate the requisite code for every type and interface in that namespace, plus any dependent types in other namespaces. You will then have a complete managed binding of Direct2D, including a class containing any necessary loose function P/Invokes. The code generated is internal by default, but there is an option in NativeMethods.json to generate public types instead. You can even put multiple namespaces in your NativeMethods.txt file if you want to use e.g. DirectWrite as well. Enjoy!

**Comment by jtorjo** [comment]
@wjk This sounds insanely awesome! I will definitely give this a test.

Quick question: how is COM reference counting handled?

**Comment by Gavin-Williams** [comment]
Is this also available for WinRT?

**Comment by wjk** [comment]
@jtorjo All COM interfaces are decorated with `ComImportAttribute`, so you would use the standard CLR COM interop calls.

@Gavin-Williams Despite what the naming would imply, this is not actually a WinRT API. The Windows.Win32.* namespaces are mostly imaginary, a way to organize APIs in the win32metadata winmd file (which cannot be linked against directly). The projected APIs that CsWin32 creates are standard COM imports, and do not have any dependencies outside of what CsWin32 will generate.

**Comment by jtorjo** [comment]
@wjk

> @jtorjo All COM interfaces are decorated with `ComImportAttribute` by default, so you would use the standard CLR COM interop calls. There is a setting to disable COM interop and manually manipulate vtables, but that technique requires unsafe code and is much more verbose. If you use that option, you would have to manually call Release() when appropriate.

I took a look at `ComImport` : https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.comimportattribute?view=net-5.0 -- I'm not sure what happens behind the scenes, or more to the point -- should I worry about that?

When I've been using win2d, I always need to be aware of how I deal with resources, and need to `.Dispose()` them at the right time. Since I'll be dealing with DirectX resources, I do expect either of:
- there should be a way to `.Dispose()` of them
- this should happen automatically right when there are no references to a COM object, and NOT during garbage collection

What will happen here?

> Despite what the naming would imply, this is not actually a WinRT API. The Windows.Win32.* namespaces are mostly imaginary, a way to organize APIs in the win32metadata winmd file 

This is amazing! The fact that there's no WinRT in between is **beyond amazing!**

**Comment by wjk** [comment]
@jtorjo If you are using COM objects with `enableMarshalling: true` (which is the default), then you will need to call `Marshal.ReleaseComObject()` before the underlying COM pointer will be released; this does _not_ happen automatically when the last CLR object referencing the instance is collected. So yes, you will need to implement IDisposable.

> This is amazing! The fact that there's no WinRT in between is **beyond amazing!**

I’m so happy that I was able to give you this news. 😄

**Comment by jtorjo** [comment]
> @jtorjo If you are using COM objects with `enableMarshalling: true` (which is the default), then you will need to call `Marshal.ReleaseComObject()` before the underlying COM pointer will be released; this does _not_ happen automatically when the last CLR object referencing the instance is collected. So yes, you will need to implement IDisposable.

@wjk This is awesome! If I understand things correctly, I could implement a thin layer on top of this and be really really close to win2d -- which is pretty amazing! Congrats! I will test this out the first chance I get!
