### ISSUE TITLE
Generated method signature may not be completely correct for cfapi->CfConnectSyncRoot

### ISSUE THREAD

**Issue by stefan-agl** [microsoft/CsWin32#344]
## Actual behavior

The definition of method CfConnectSyncRoot in cfapi.h is as follows: 

```C
STDAPI
CfConnectSyncRoot (
    _In_ LPCWSTR SyncRootPath,
    _In_ CONST CF_CALLBACK_REGISTRATION *CallbackTable,
    _In_opt_ LPCVOID CallbackContext,
    _In_ CF_CONNECT_FLAGS ConnectFlags,
    _Out_ CF_CONNECTION_KEY *ConnectionKey
    );
```

generated C# method signature is respectively

```cs
[SupportedOSPlatform("windows10.0.16299")]internal static unsafe win32.Foundation.HRESULT CfConnectSyncRoot(
    string SyncRootPath, 
    in win32.Storage.CloudFilters.CF_CALLBACK_REGISTRATION CallbackTable,
    void* CallbackContext, 
    win32.Storage.CloudFilters.CF_CONNECT_FLAGS ConnectFlags, 
    out win32.Storage.CloudFilters.CF_CONNECTION_KEY ConnectionKey) 
{ ... } 
```

where 

`_In_ CONST CF_CALLBACK_REGISTRATION *CallbackTable` 

translates to 

`in win32.Storage.CloudFilters.CF_CALLBACK_REGISTRATION CallbackTable`

This parameter as the name suggests is used to pass in a table of typed callbacks to handle certain filesystem events, however I am not completely sure if I fail to understand how to properly call the method, or is the parameter's type not generated correctly.

I became more suspicious when I looked at the P/Invoke signature provided by the Vanara project for the same method, which I add for reference: 

```cs
 [PInvokeData("cfapi.h", MSDNShortId = "287DA978-9797-48DF-9C90-BA53BB82475C")]
 public static HRESULT CfConnectSyncRoot(
    string SyncRootPath,
    CF_CALLBACK_REGISTRATION[] CallbackTable, 
    IntPtr CallbackContext, 
    CF_CONNECT_FLAGS ConnectFlags, 
    out CF_CONNECTION_KEY ConnectionKey);
```
There we have an array to pass for CallbackTable. 

I would like to know:

1. is the method signature generated correctly 
2. if yes, what would be the correct idiom in C# to call it (as I am currently becoming a C# programmer by necessity It is highly likely that I am missing something obvious here so please, do not spare details in any explanations that would follow)

## Repro steps

1. `NativeMethods.txt` content:
```
CldApi.*
```

2. Try to call `Windows.Win32.PInvoke.CfConnectSyncRoot` 

### Context

- CsWin32 version: v0.1.506-beta
- Win32Metadata version (if explicitly set by project):
- Target Framework: net5.0-windows10.0.19041.0

Thanks and regards,
Stefan

**Comment by AArnott** [comment]
Yes, I think `CfConnectSyncRoot` is being generated correctly. Vanara is sub-optimally exposing it as an array but per the docs, the parameter is a pointer to exactly one struct. The `in` modifier we emit causes the interop layer to send a pointer instead of the value itself, which in interop is equivalent to Vanara's approach of using an array.

**Comment by stefan-agl** [comment]
Greetings, again, 

Is there anything special I need to do when calling this method, because if I just pass the array parameter I receive a compile-time error:

    unsafe
    {
        CF_CONNECTION_KEY key;
        CF_CALLBACK_REGISTRATION[] callbacks = new CF_CALLBACK_REGISTRATION[13];
                        
        PInvoke.CfConnectSyncRoot(null, callbacks, null, Windows.Win32.Storage.CloudFilters.CF_CONNECT_FLAGS.CF_CONNECT_FLAG_NONE, out key);
    }
    

error being: 

`
CS1503	Argument 2: cannot convert from 'Windows.Win32.Storage.CloudFilters.CF_CALLBACK_REGISTRATION[]' to 'in Windows.Win32.Storage.CloudFilters.CF_CALLBACK_REGISTRATION'	
`
among others that popped up.

I'd appreciate further tips on how to make the actual call, because reading into MS Interop documentation for C# did not shed more light.

Regards,
Stefan

**Comment by AArnott** [comment]
Why are you trying to pass in an array for the second argument? The function only takes _one_ as [documented here](https://docs.microsoft.com/en-us/windows/win32/api/cfapi/nf-cfapi-cfconnectsyncroot).

**Comment by AArnott** [comment]
Maybe I spoke too soon. The documentation doesn't mention it, but perhaps that really is a pointer to an array. As evidence, [this specially-terminated array](https://github.com/microsoft/Windows-classic-samples/blob/67a8cddc25880ebc64018e833f0bf51589fd4521/Samples/CloudMirror/CloudMirror/FakeCloudProvider.cpp#L38-L43) is [passed in as the second argument](https://github.com/microsoft/Windows-classic-samples/blob/67a8cddc25880ebc64018e833f0bf51589fd4521/Samples/CloudMirror/CloudMirror/FakeCloudProvider.cpp#L115-L117) to this method.

So I guess this is a bug in the metadata.
