### ISSUE TITLE
There should be a way to override/replace generated types

### ISSUE THREAD

**Issue by phizch** [microsoft/CsWin32#352]
There should be a way to override or replace generated types, and have other generated types incorporate the replacements.
Alternatively, or additionally, a way to override the code generation.

## Problem related to the feature request
I've run into bugs related to types being incorrectly generated. Specifically several enums had base type `uint` instead of `ushort`.
See issue #351.

## Solution
Some way to indicate to the generator that 
* the user supplies their own version of that type.
* the generator should replace it's original output with code supplied by the user. (see ex 3)

One option is to have a tag or keyword after a type in NativeMethods.txt. 
I'm not sure what keywords to use, but here's some examples that might work:

NativeMethods.txt
```
-- example 1.a: - user replacement with different name
IMAGE_FILE_MACHINE replacewith Project.IMAGE_FILE_MACHINE

-- example 1.b: - full namespace
Windows.Win32.System.Diagnostics.Debug.IMAGE_FILE_MACHINE replacewith Project.IMAGE_FILE_MACHINE

-- example 2: - user implements type manually in the correct namespace
Windows.Win32.System.Diagnostics.Debug.IMAGE_FILE_MACHINE ignore

-- example 3.a: - specific fix using search/replace
IMAGE_FILE_MACHINE replace ":uint" with ": ushort"

-- example 3.b
IMAGE_FILE_MACHINE BaseType "ushort"
```

#### 1
To work around the problem I copied the generated types to a new file, fixed the problems and used my versions instead.
In my case that consisted of
* `struct IMAGE_NT_HEADERS64`
* `struct IMAGE_FILE_HEADER`
* `struct IMAGE_OPTIONAL_HEADER64`
* `enum IMAGE_FILE_CHARACTERISTICS`
* `enum IMAGE_OPTIONAL_HEADER_MAGIC`
* `enum IMAGE_SUBSYSTEM`
* `enum IMAGE_DLL_CHARACTERISTICS`

I corrected the base type of the enums, and changed fields in the structs to use the replaced types.

If I were to use methods to operate on the structs, I would have to replace those too, but in my case I just read into them from a file manually.

#### 2
Submitting a bug report here. Of course, that has to be done anyway, but fixing the bugs in the generator takes time, during which the generated code won't work.

**Comment by phizch** [comment]
The overrides could be specified in the `.json` file instead of having tags in the `.txt` file.

**Comment by AArnott** [comment]
Please do always (continue to) file bugs for bugs in code generation or metadata behind that code generation.

CsWin32 already suppresses generating a type if either of these are true:
1. The type (with identical name and namespace) exists in a referenced assembly.
2. The type (with identical name and namespace) exists in user code of the project _without_ the `partial` modifier.

When CsWin32 suppresses type generation, it will be happy to reference that type from other APIs that CsWin32 generates.
Does that work for you?
