### ISSUE TITLE
Discoverability of Windows GUID constants

### ISSUE THREAD

**Issue by skippy10110** [microsoft/CsWin32#353]
**Is your feature request related to a problem? Please describe.**

It's hard to determine the correct constant name to use for the various GUID constants in the Windows API. Searching through examples online they tend to use these constants as a given, but the constant names used often don't work with CsWin32. Other times I have the GUID value that I need, but have a hard time figuring out the constant name that would be listed under.

**Describe the solution you'd like**

Ideally I could feed the GUID value to CsWin32 somehow and have it tell me the correct constant name to use. If it doesn't exist under any constant name, it could tell me that so I don't keep hunting for it and I'll know I just need to define it myself.

**Describe alternatives you've considered**

Currently I define the constant values by hand if I'm unable to find the correct constant name to use, e.g.:

````csharp
public partial class Constants
{
    public static Guid CLSID_CSearchManager = new Guid("7d096c5f-ac08-4f1f-beb7-5c22c517ce39");
    public static Guid CLSID_ShellLink = new Guid("00021401-0000-0000-C000-000000000046");
}
````

**Comment by jnm2** [comment]
Possibly related to https://github.com/microsoft/CsWin32/discussions/323

**Comment by skippy10110** [comment]
Thanks! I totally missed your discussion when I was searching. I had no idea I could include CSearchManger/ShellLink like you've shown, so I'll be updating my code accordingly.

I do still have the issue of finding GUID constants where I know the value. E.g. I know there's SCHEME_BALANCED from powercfg.exe and I know it's "381b4222-f694-41f0-9685-ff5bb260df2e". But I have a hard time finding if there's any constant name I can use for that. For a successful example, I was able to find that SUB_VIDEO from powercfg.exe translates to GUID_VIDEO_SUBGROUP.

**Comment by AArnott** [comment]
`typeof(CSearchManager).GUID`
`typeof(ShellLink).GUID`

Hopefully you see the pattern there. If you have a suggestion for how to make these more discoverable, I'm interested.

I don't see `SCHEME_BALANCED` or anything like it in the metadata, so you probably have to define that yourself.
