### ISSUE TITLE
Method "SetSuspendState" is not translated correctly (BOOLEAN => byte instead of bool)

### ISSUE THREAD

**Issue by KChZellemann** [microsoft/CsWin32#354]
## Actual behavior
CsWin32 translate the BOOLEAN values of the method SetSuspendState to byte instead to bool.

The definition of method SetSuspendState in powrprof.h is as follows:
```
STDAPI_(BOOLEAN) SetSuspendState(_In_ BOOLEAN bHibernate, _In_ BOOLEAN bForce, _In_ BOOLEAN bWakeupEventsDisabled);
```
Generated C# method signature:

```
[DllImport("PowrProf", ExactSpelling = true,SetLastError = true)]
[DefaultDllImportSearchPaths(DllImportSearchPath.System32)][SupportedOSPlatform("windows5.1.2600")]internal static extern bool SetSuspendState(byte bHibernate, byte bForce, byte bWakeupEventsDisabled);
```

## Expected behavior

```
[DllImport("PowrProf", ExactSpelling = true,SetLastError = true)]
[DefaultDllImportSearchPaths(DllImportSearchPath.System32)][SupportedOSPlatform("windows5.1.2600")]internal static extern bool SetSuspendState(bool bHibernate, bool bForce, bool bWakeupEventsDisabled);
```

## Repro steps

1. `NativeMethods.txt` content:
```
SetSuspendState
```

### Context

- CsWin32 version: 0.1.506-beta
- Target Framework: net5.0

**Comment by AArnott** [comment]
The latest CsWin32 version (and metadata that it brings in) uses `BOOLEAN` instead of `byte` here. It won't be `bool` because the ABI isn't equivalent in every case. But with #586, BOOLEAN becomes much easier to work with and can implicitly convert with `bool` too.
