### ISSUE TITLE
Generator crashes if a referenced project declares an internal SupportedOSPlatformAttribute

### ISSUE THREAD

**Issue by jnm2** [microsoft/CsWin32#365]
If a referenced project declares `System.Runtime.Versioning.SupportedOSPlatformAttribute` internally, CsWin32 crashes.

(This was an attempt to create a repro for a different situation in which a referenced *binary* with an internal definition of `System.Runtime.Versioning.SupportedOSPlatformAttribute` causes CsWin32 to think it doesn't need to emit a declaration for SupportedOSPlatformAttribute. It then emits usages of that attribute, causing CS1022 errors in generated code because the type is not accessible.)

I believe this is probably due to use of `Compilation.GetTypeByMetadataName` which has [problems](https://github.com/dotnet/roslyn/issues/52399).

## Repro steps

Extract and run `dotnet build`: [Repro.zip](https://github.com/microsoft/CsWin32/files/7003448/Repro.zip)

> CSC : warning CS8785: Generator 'SourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'InvalidOperationException' with message 'Sequence contains no elements'

### Context

- CsWin32 version: `0.1.506-beta`, 
- Target Framework: `net48`

**Comment by jnm2** [comment]
@AArnott Do you want me to build up another repro for the binary dependency case file a second issue (because the CsWin32 behavior is different), even though I suspect the root cause is similar or the same in both cases?

**Comment by AArnott** [comment]
Let's start with this one and you can file the second if fixing this one doesn't fix it.
Interested in sharing a PR? Extra good if you can include a unit test.

**Comment by AArnott** [comment]
Looks like @sharwell fixes this in 2ceb50f5a36a9dffe8d3a88be3e2359c8cede840, which is (oddly?) part of #319.
