### ISSUE TITLE
All Flags enums should define a value for 0

### ISSUE THREAD

**Issue by AArnott** [microsoft/CsWin32#367]
When an API takes a flags enum, passing 0 in C was natural, but C# requires a cast for that or use of the longer and less-intuitive `default`. The .NET convention is that flags enums should define some value whose value is 0 (e.g. `None`). 
CsWin32 should generate this if the metadata does not.

**Comment by jnm2** [comment]
C# allows the numeric literal `0` to implicitly cast to any enum type.

**Comment by AArnott** [comment]
Whoa! I had no idea. I wonder if that's relatively new, or if I have no excuse for not knowing that.
Well then, I feel better about not delivering this.

**Comment by jnm2** [comment]
It seems to work in C# 1.0. I think I discovered this a year or two ago and remember being very surprised too!

**Comment by YoshiRulz** [comment]
I don't like needing to pass `(TEnum) 0`/`default` for an enum parameter. That defeats the purpose of strong typing.
If warnings were enabled for generated code, these would be flagged with [CA1008](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1008).
