### ISSUE TITLE
VS editor constantly warns about inconsistent line endings

### ISSUE THREAD

**Issue by wjk** [microsoft/CsWin32#369]
## Actual behavior

The warning showed in the below screenshot is displayed every time I open a file generated by CsWin32. Because these generated files are read-only, the options in the warning dialog do nothing, and will not stop the alert from appearing the next time I open one. This, while technically harmless, is very annoying, as I want to keep the dialog enabled so I can detect mismatched line endings in other, non-generated files. 

<img width="388" alt="Screenshot" src="https://user-images.githubusercontent.com/1915951/129972197-31d71294-12f1-4be8-b077-9d2b04db1c6f.png">

### Context

- Visual Studio version: VS 2022 Preview 3.1
- CsWin32 version: 0.1.506-beta
- Win32Metadata version: (default)
- Target Framework: net6.0-windows10.0.18362
- `LangVersion`: 10 (as required by generated code, which includes `global using` statements)

**Comment by AArnott** [comment]
I agree it's terribly annoying. It's a bug in the editor (or roslyn, IIRC) in that it shouldn't ask the user to normalize line endings in a readonly file. @sharwell, do you recall a filed bug where this was pushed from the editor team to roslyn to fix?

Within this repo, we can also try to workaround this by emitting consistent line endings.

**Comment by wjk** [comment]
@AArnott I also would like to note that the formatting in the generated files is messier than I remember it being, mostly in the form of missing newlines in odd places. Since that certainly looks like the result of a line ending mismatch bug, I would recommend that we attack the root cause of the problem, as simply suppressing the editor warning would not fix the formatting issues. Thanks!

**Comment by sharwell** [comment]
@AArnott I thought I fixed this in the generator

**Comment by sharwell** [comment]
It's fairly easy to fix additional cases; tests can be added for specific APIs (in this case, it looks like `IPersistStream`?)

**Comment by AArnott** [comment]
@sharwell: I'm still catching up on issues/PRs on this repo, and am looking at #319 now. I'm trying to reverse-engineer the missing PR description based on 53 changed files in the PR to start with. :wink:
