### ISSUE TITLE
APIs which require PWSTR or PCWSTR cause build failure on net35

### ISSUE THREAD

**Issue by jnm2** [microsoft/CsWin32#394]
## Actual behavior

Compile errors:
> ❌ CS0246 The type or namespace name 'ReadOnlySpan<>' could not be found (are you missing a using directive or an assembly reference?) in Windows.Win32.PCWSTR.g.cs, line 71
> ❌ CS0246 The type or namespace name 'Span<>' could not be found (are you missing a using directive or an assembly reference?) in Windows.Win32.PWSTR.g.cs, line 53

https://github.com/microsoft/CsWin32/blob/b050877b3bd4462aeb7f6020eb1a895f40269949/src/Microsoft.Windows.CsWin32/templates/PCWSTR.cs#L42-L45

https://github.com/microsoft/CsWin32/blob/b050877b3bd4462aeb7f6020eb1a895f40269949/src/Microsoft.Windows.CsWin32/templates/PCSTR.cs#L42-L45

## Expected behavior

No compile errors because members are omitted when the required types are missing. This would be consistent with several other places, such as:
https://github.com/microsoft/CsWin32/blob/b050877b3bd4462aeb7f6020eb1a895f40269949/src/Microsoft.Windows.CsWin32/Generator.cs#L321-L323

## Repro steps

1. `NativeMethods.txt` content:
```
CreateFile
```

FindFirstStream is also blocked by this.

### Context

- CsWin32 version: `0.1.560-beta` and the previous three versions on nuget.org which I also tried
- Target Framework: net35

**Comment by AArnott** [comment]
`netstandard2.0` is the lowest supported TFM. We do some limited testing on net40 but that's not fully supported either. Anything below the supported level is a "your mileage may vary" kind of thing.

We'll take PRs to make certain scenarios work better, if they don't add a lot of complexity and they come with tests for what you need to keep working.
