### ISSUE TITLE
No option to control where files are generated into

### ISSUE THREAD

**Issue by smaillet** [microsoft/CsWin32#402]
## Actual behavior

Files seem to be generated only into a LocalAppData temp folder location. As the user, I should be able to specify where things go and control that from a build perspective. Normally code generators generate code files into the obj directory for the project. So this tool should generate to that same location for consistency or at least let users configure where things go. Debugging becomes a real problem if the temp files are cleaned up as I won't be able to find those files anymore... 

## Expected behavior

Generated code files go into the obj folder like most other code generators or I have control of where they go. They should NOT default to a random temp directory the user won't know anything about. (I spent a really long while trying to figure out where the files were generated to as they weren't being included in the project [Filed a different bug on that])

## Repro steps

1. `NativeMethods.txt` content:
```
SetWindowPos
```

2. `NativeMethods.json` content (if present):
```json
```

3. Any of your own code that should be shared?

### Context

- CsWin32 version: [e.g. `0.1.560-beta`]
- Target Framework: [e.g. `net5.0-windows10.0.19041.0`]

**Comment by AArnott** [comment]
CsWin32 is implemented as a roslyn Source Generator. It has no say at all as to where the code files are written to disk (if at all). Any feedback you have in this area should be directed to the dotnet/roslyn repo.

Thanks for trying out CsWin32.

**Comment by jnm2** [comment]
ℹ https://github.com/dotnet/roslyn/issues?q=is%3Aissue+is%3Aopen+EmitCompilerGeneratedFiles will show you existing conversations. I think is an area being actively designed.
