### ISSUE TITLE
D3D11_SDK_Version not included

### ISSUE THREAD

**Issue by BMarques** [microsoft/CsWin32#416]
## Actual behavior

I'm trying to do a D3D11CreateDevice, which has a uint parameter called SDKVersion. Normally it requires a D3D11_SDK_VERSION value in it, but I'm not able to find it. Looking at the win32metadata, it should be in the Windows.Win32.Graphics.Direct3D11.Apis, but i'm not able to get it.

## Expected behavior

Find the D3D11_SDK_VERSION variable in the Windows.Win32.Graphics.Direct3D11.Apis.

## Repro steps

1. `NativeMethods.txt` content:
```
D3D11CreateDevice
```

2. `NativeMethods.json` content (if present):
```json
```

3. Any of your own code that should be shared?
Just try to use PInvoke.D3D11CreateDevice
### Context

- CsWin32 version: 0.1.588-beta
- Win32Metadata version (if explicitly set by project):
- Target Framework: net5.0-windows10.0.19041.0
- `LangVersion` 9

**Comment by mikestek** [comment]
if you add D3D11_SDK_VERSION to NativeMethods.txt then it will be generated in Windows.Win32.Constants

**Comment by BMarques** [comment]
Indeed it is there, thanks. Is that the intended behavior?

**Comment by BMarques** [comment]
I saw now that it's the intended behavior, so I'll close the issue.
