### ISSUE TITLE
Types are not generated when referenced project already defines them, even though they are inaccessible

### ISSUE THREAD

**Issue by TIPConsulting** [microsoft/CsWin32#43]
VS is throwing an error during compilation because of a backend file that I cannot see.  Here are the details that I can see

````
CS0122: 'BOOL' is inaccessible due to its protection level

File: PInvoke.User32.cs, Line 36
````

The method endpoint is generated properly, Pinvoke.LockWorkStation() is available and no errors appear in my app code.  "LockWorkStation" is the only method in my NativeMethods.txt

**Comment by AArnott** [comment]
> a backend file that I cannot see

Tip: if you're using VS 16.9 (in Preview), all generated files will be discoverable via Solution Explorer:

**Comment by TIPConsulting** [comment]
The first tip that you showed about finding the generated files does work for me, thanks (but it has a bug, see footnote)

I made a new discovery that might help.  The project structure is a bit bigger than I first said, and the extra complexity is key to the issue.

Project structure:
Plywood
&nbsp;&nbsp;&nbsp;&nbsp;|__Plywood.Client

Plywood.Client references Plywood.  Plywood and Plywood.Client both use CsWin32 generators.  I have added the NativeMethods.json modifier to  both projects

![image](https://user-images.githubusercontent.com/17582002/105546411-96497100-5cba-11eb-90e0-f2bac22a5c37.png)

Right now, if both projects have populated NativeMethods.txt files, then Plywood will compile but Plywood.Client will fail.  If I remove the NativeMethod.txt from Plywood, then Plywood.Client will compile.  So this BOOL error is happening when there is a parent project that also uses CsWin32

Here is the NativeMethods.cs file from Plywood.Client if both generators are enabled:
[Plywood.Client.NativeMethods_Broken.txt](https://github.com/microsoft/CsWin32/files/5858608/Plywood.Client.NativeMethods_Broken.txt)

Here is the Here is the NativeMethods.cs file from Plywood.Client if the parent generator is disabled:
[Plywood.Client.NativeMethods.txt](https://github.com/microsoft/CsWin32/files/5858612/Plywood.Client.NativeMethods.txt)

When the parent generator is active, the child does not generate its own BOOL.  This is likely because BOOL is already generated by the parent, but its marked as internal so the child cant access it.  Maybe the generators run in a shared context even though they target different projects?  Or possibly related to work done for #3?

___

Now for a bonus bug: This is related to viewing the generator output code in VS.  In the screenshot, I show two projects with generated NativeMethods.cs files.  Both of those file icons open the same physical file.  So I cannot see the actual contents of Plywood.NativeMethods.cs, it just opens the Plywood.Client.NativeMethods.cs file

Also, if both projects have active generators, then F12 will also show the same file when used from either project

**Comment by AArnott** [comment]
Thanks. I'll see if I can repro the BOOL bug and get a fix.

For the bonus bug, can you please file that against the dotnet/roslyn repo, as they own that?

**Comment by AArnott** [comment]
Yup, this is biting me too.

**Comment by TIPConsulting** [comment]
Looks like the "bonus bug" has a fix in the pipeline: https://github.com/dotnet/roslyn/issues/50714
