### ISSUE TITLE
`ExecutionEngineException` when binding to IShellItem BHID_EnumItems handler

### ISSUE THREAD

**Issue by duke7553** [microsoft/CsWin32#434]
## Actual behavior
Binding to a BHID_EnumItems handler for an IShellItem as demonstrated below results in an ExecutionEngineException. This is despite the SHCreateItemFromParsingName HRESULT being zero.
```
unsafe
{
   void* spsiFolder;
   HRESULT res = PInvoke.SHCreateItemFromParsingName(path, null, new Guid("43826d1e-e718-42ee-bc55-a1e261c37bfe"), out spsiFolder);
   IShellItem shellItem = Unsafe.AsRef<IShellItem>(spsiFolder);

   var BHID_EnumItems = new Guid("94f60519-2850-4924-aa5a-d15e84868039");
   var riid2 = typeof(IEnumShellItems).GUID;
----->   shellItem.BindToHandler(null, &BHID_EnumItems, &riid2, out object items);
   spesi = Unsafe.As<IEnumShellItems>(items);
}
```

## Expected behavior
There shouldn't be an obscure ExecutionEngineException thrown here.

## Repro steps

1. `NativeMethods.txt` content:
```
SHDefExtractIcon
SHGetFileInfo
IShellItem
IShellItem2
IImageList2
IShellItemImageFactory
SHCreateItemFromParsingName
SHGetImageList
HIMAGELIST
IEnumShellItems
CreateBindCtx
```

2. `NativeMethods.json` content (if present): 
N/A

3. Any of your own code that should be shared?
Shared above.

### Context

- CsWin32 version: `0.1.588-beta`
- Win32Metadata version (if explicitly set by project): implicitly set
- Target Framework: `net5.0-windows10.0.19041.0`
- `LangVersion` (if explicitly set by project): implicitly set

**Comment by AArnott** [comment]
Ah, the bug is in your cast to IShellItem. What they give you cannot simply be cast to an interface. The .NET marshaler has to get involved to create the RCW. This version of the code works:

```cs
    HRESULT res = PInvoke.SHCreateItemFromParsingName(path, null, typeof(IShellItem).GUID, out void* spsiFolder);
    IShellItem shellItem = (IShellItem)Marshal.GetObjectForIUnknown(new IntPtr(spsiFolder));

    var BHID_EnumItems = new Guid("94f60519-2850-4924-aa5a-d15e84868039");
    shellItem.BindToHandler(null, BHID_EnumItems, typeof(IEnumShellItems).GUID, out object items);
    IEnumShellItems spesi = (IEnumShellItems)items;
```

**Comment by AArnott** [comment]
Discoverability of the right syntax would have been easier if it were not for https://github.com/microsoft/win32metadata/issues/705.

**Comment by virzak** [comment]
This no longer works with version 0.1.635-beta since SHCreateItemFromParsingName now outs and object.

**Comment by AArnott** [comment]
@virzak if the method uses `out object` then you already have the RCW and can just cast it.

**Comment by virzak** [comment]
With version 0.2.138-beta and `"allowMarshaling": false` it goes back to `out void*`. It is possible to have a generic version `SHCreateItemFromParsingName<T>(..., out T)`?

**Comment by AArnott** [comment]
Such a method is possible, and you could code this up and add it as an overload via your own partial class. 
For CsWin32 to do this automatically I think we'd have to recognize some reliable pattern in the method signature to know that the `riid` being passed in is presumed to determine the type of the COM object coming out. I don't know that this method signature makes that obvious. We could special case it, but we generally avoid special casing APIs unless they are _very_ commonly used. I'm afraid in this case you'll have to write that method yourself.
