### ISSUE TITLE
Pointer to a COM interface in a struct is generated as interface

### ISSUE THREAD

**Issue by SmartK8** [microsoft/CsWin32#435]
## Actual behavior

In metadata the MFT_OUTPUT_DATA_BUFFER is defined as:

```C++
typedef struct _MFT_OUTPUT_DATA_BUFFER
{
    DWORD dwStreamID;
    IMFSample *pSample; // pointer to an interface
    DWORD dwStatus;
    IMFCollection *pEvents;
} MFT_OUTPUT_DATA_BUFFER;
```
But generated C# code is (comments removed for brevity):

```C#
public partial struct MFT_OUTPUT_DATA_BUFFER
{
    public uint dwStreamID;
    public IMFSample pSample; // interface
    public uint dwStatus;
    public IMFCollection pEvents;
}
```
## Expected behavior

It should generate IntPtr instead of IMFSample.

```C#
public partial struct MFT_OUTPUT_DATA_BUFFER
{
    public uint dwStreamID;
    public IntPtr pSample;
    public uint dwStatus;
    public IntPtr pEvents;
}
```

or it should be marshalled as a COM interface pointer:

```C#
public partial struct MFT_OUTPUT_DATA_BUFFER
{
    public uint dwStreamID;
    [MarshalAs(UnmanagedType.Interface)] public IMFSample pSample;
    public uint dwStatus;
    [MarshalAs(UnmanagedType.Interface)] public IMFCollection pEvents;
}
```

## Repro steps

1. `NativeMethods.txt` content:
```
MFCreateSampleCopierMFT
```

2. `NativeMethods.json` content (if present):
```json
{
  "$schema": "https://aka.ms/CsWin32.schema.json",
  "public": true,
  "wideCharOnly": false,
  "emitSingleFile": true
}
```

### Context

- CsWin32 version: 0.1.588-beta
- Target Framework: .NET 5

**Comment by AArnott** [comment]
Thanks for reporting this, @SmartK8. Are you saying that without the attribute on the interface field, the CLR won't marshal it as a COM object? Have you seen a malfunction when this attribute is missing?

@AaronRobinsonMSFT do you know whether the CLR requires `[MarshalAs(UnmanagedType.Interface)]` on a field typed as an interface that itself has `[Guid("C40A00F2-B93A-4D80-AE8C-5A1C634F58E4"),InterfaceType(ComInterfaceType.InterfaceIsIUnknown),ComImport()]` on it?

**Comment by SmartK8** [comment]
I found it out when I was trying to use it. So it definitely prohibited me from using such structures. I just written my own as a workaround. I will check it out to refresh my memory, and will report on what is needed. In the end (in my workaround) I used IntPtr. I have to test if marshalling it as an interface works all the time (I have multiple such structures). I think it might worked somewhere, but not universally, but I'll check it out.

**Comment by AArnott** [comment]
We do use IntPtr when generating structs that must be `unmanaged` types. For the marshalable structs, we prefer the field with the COM interface as its declared type. It shouldn't be too hard to add the attribute to every field typed this way. But I wonder whether it should also appear on parameter types. Kinda wonder how this hasn't been caught by many more folks...

**Comment by AaronRobinsonMSFT** [comment]
> @AaronRobinsonMSFT do you know whether the CLR requires [MarshalAs(UnmanagedType.Interface)] on a field typed as an interface that itself has [Guid("C40A00F2-B93A-4D80-AE8C-5A1C634F58E4"),InterfaceType(ComInterfaceType.InterfaceIsIUnknown),ComImport()] on it?

This is odd. The runtime should identify the type as an interface and without any other indication default to marshalling this as a COM interface. I just confirmed this on .NET 7 so this could be a bug in .NET 5. Regardless of potential bugs and defaults, the Interop team highly recommends being explicit and avoiding defaults where possible &ndash; especially when code is autogenerated. Not setting the value, `[MarshalAs(UnmanagedType.Interface)]` should be the default, but adding is helpful in my opinion.

```csharp
struct Foo1
{
    public IBar bar;
}
struct Foo2
{
    [MarshalAs(UnmanagedType.Interface)] public IBar bar;
}

[ComImport]
[Guid("05655a94-a915-4926-815d-a9ea648baad8")]
[InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
public unsafe interface IBar
{
    int Func();
}
```

**Comment by SmartK8** [comment]
I've create a sample in .NET 7 (console application) that demonstrates it directly on `IMFTransform`.
You can switch conditional compilation symbols:

**CSWIN32**
-   when on: switches to generated structure
-   when off (**_CSWIN32**) switches to my implementations

**INTERFACE**
- when on: switches to a struct with marshalling to interface
- when off (**_INTERFACE**) it uses `IntPtr`

I've included a short sample H264 video (~800k) to be used in decoding. 
It's just a barebone example of course. So everything possible is stripped to minimum.

[Sample - CsWin32ComInterfaceProblemProof.zip](https://github.com/microsoft/CsWin32/files/8921023/CsWin32ComInterfaceProblemProof.zip)

**Comment by AaronRobinsonMSFT** [comment]
Ah. This is different. In fact, this is far more complicated since it is an element of an array and I'm going to need to debug.

**Comment by AArnott** [comment]
Thanks for the repro. I can see that it works with one precompilation symbol and not the other. But I took the CsWin32 side of your code and only added the `[MarshalAs(UnmanagedType.Interface)]` attributes in all the places you used them, and it still fails in the same way, which leads me to believe that the failure is caused by some other difference in your code. I'll still look at it, but if you have any ideas of what I missed, I'm open to it.

**Comment by SmartK8** [comment]
The only difference as far as I can see - other than `MFT_OUTPUT_DATA_BUFFER` - is `IMFTransform`. I'm trying to convert my version to generated one. If I can achieve throwing the same exception in my implementation, then it must be somewhere in generated `IMFTransform`.

**Comment by AArnott** [comment]
It's definitely *not* in the struct, because I replaced yours with the generated one and your program still works. I'm working through the interface as well.

**Comment by AArnott** [comment]
I even replaced your interface with CsWin32 and it passes. It looks like the failure is caused not by CsWin32, but by the rest of your code that calls into it differently based on these preprocessor directives.

**Comment by AArnott** [comment]
Here is my version of your app. I removed all the CsWin32 code paths and then progressively deleted your own interop code and updated callers to use CsWin32 generated code. It worked just fine.
[CsWin32ComInterfaceProblemProof.zip](https://github.com/microsoft/CsWin32/files/8922053/CsWin32ComInterfaceProblemProof.zip)

I noticed your CsWin32 side of the code (which I deleted) was doing what looked like funky stuff with COM pointers, so I wonder if the bug was there.

**Comment by SmartK8** [comment]
I agree. It works for me know. That funky stuff (`Marshal.GetIUnknownForObject(sample)`) was in my implementation which worked, but the culprit was this missing code in `CreateOutputDataBuffer()`:

```
Check(PInvoke.MFCreateMemoryBuffer((UInt32) size, out IMFMediaBuffer buffer));
sample.AddBuffer(buffer);
```

I'm not sure if it was just a mistake that was newly created in this sample or a mistake when I originally posted it as well, but the important thing is that in .NET 7/latest CsWin32 it works.

**Comment by SmartK8** [comment]
Thanks to all for the cooperation solving this.
