### ISSUE TITLE
It is not possible to call `CreateWindowEx` function with `ATOM` parameter

### ISSUE THREAD

**Issue by ghord** [microsoft/CsWin32#443]
## Actual behavior

Generated `CreateWindowEx` function only expects `string` or `PCWSTR` parameter as `lpClassName`. It should be possible to pass the result of `RegisterClassEx` function as a `lpClassName` according to [msdn docs](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-registerclassexa#return-value), but the value returned from `RegisterClassEx` is of `ushort` type which is not compatbile.

## Expected behavior

User is able to pass result of `RegisterClassEx` function to `CreateWindowEx`.

## Repro steps

1. `NativeMethods.txt` content:
```
RegisterClassEx
CreateWindowEx
LoadIcon
LoadCursor
GetModuleHandle
DefWindowProc

WNDCLASS_STYLES
SYS_COLOR_INDEX

IDC_ARROW
```

3. Any of your own code that should be shared?

### Context
```c#
using var hInst = PInvoke.GetModuleHandle((string?)null);

if (hInst.IsInvalid)
    throw new Exception("Cannot get hInst");

WNDCLASSEXW windowClass;
windowClass.cbSize = (uint)Marshal.SizeOf<WNDCLASSEXW>();
windowClass.style = WNDCLASS_STYLES.CS_HREDRAW | WNDCLASS_STYLES.CS_VREDRAW;
windowClass.lpfnWndProc = null;
windowClass.cbClsExtra = 0;
windowClass.cbWndExtra = 0;
windowClass.lpfnWndProc = WindowFunction;

windowClass.hInstance = (HINSTANCE)hInst.DangerousGetHandle();
windowClass.hIcon = (HICON)PInvoke.LoadIcon(hInst, null).DangerousGetHandle();
windowClass.hCursor = PInvoke.LoadCursor((HINSTANCE)IntPtr.Zero, Constants.IDC_ARROW);
windowClass.hbrBackground = (HBRUSH)(IntPtr)(SYS_COLOR_INDEX.COLOR_WINDOW + 1);
windowClass.lpszMenuName = null;

ushort classEx;

fixed (char* ptr = "TestWindowClass")
{
    windowClass.lpszClassName = ptr;
    windowClass.hIconSm = (HICON) PInvoke.LoadIcon(hInst, null).DangerousGetHandle();
    ushort atom = PInvoke.RegisterClassEx(windowClass);

    // Cannot pass atom as a parameter here
    PInvoke.CreateWindowEx(WINDOW_EX_STYLE.WS_EX_OVERLAPPEDWINDOW, ???, ...);

}
```

**Comment by mikestek** [comment]
The CreateWindowEx documentation states:
`The atom must be in the low-order word of lpClassName; the high-order word must be zero.`

Based on that if you should be able to cast the ushort atom and pass it for that param. `(char*)atom` , the generated PCWSTR struct has an implicit cast from char*

Atoms overall are pretty useless though and there's little reason to use them and not just pass in the full class name to CreateWindowEx which can take either the string or the char* (again an implicit cast for PCWSTR)

**Comment by ghord** [comment]
That is good enough for me, not sure API surface should be changed for such small use case.

**Comment by AArnott** [comment]
Thanks folks.
