### ISSUE TITLE
Some templates' internal members are not promoted to public

### ISSUE THREAD

**Issue by AArnott** [microsoft/CsWin32#457]
### Discussed in https://github.com/microsoft/CsWin32/discussions/456

<div type='discussions-op-text'>

<sup>Originally posted by **AliveDevil** November 25, 2021</sup>
I don't see any benefit of internalizing ThrowOnFailure: https://github.com/microsoft/CsWin32/blob/main/src/Microsoft.Windows.CsWin32/templates/HRESULT.cs#L43-L62

Same with `Succeeded` and `Failed`, consuming these members in any dependent project is impossible, unless `InternalsVisibleTo` is set.</div>

We should promote `internal` members from templates to `public` when the NativeMethods.json contains `public: true`.

**Comment by AliveDevil** [comment]
You could set the internal template members always to `public`, as those are never more accessible than the parent scope.
like
```
internal HRESULT {
public ThrowOnFailure();
}
```

**Comment by AArnott** [comment]
True. That would be the simplest fix. However I dislike defining public members in an internal class because it gives the false impression or at least the possibility that the members are public. In code reviews where I see members added or changed with `public` modifiers, I have to go double-check the containing type(s) to establish whether they *really* are public since adding public members carries more cost than adding internal members. I like to save the time for code reviewers by just marking them `internal` if that's what they really are.

**Comment by AArnott** [comment]
It turns out we already had the promotion code, but it had a filter on it that caused it to miss promotion of some of them.
