### ISSUE TITLE
IFileDialog.Show returns void instead of HRESULT

### ISSUE THREAD

**Issue by virzak** [microsoft/CsWin32#465]
## Actual behavior

When `IFileSaveDialog` is added to nativemethods.txt, the resulting generation is:

```cs
internal interface IFileDialog :winmdroot.UI.Shell.IModalWindow{
    new void Show(winmdroot.Foundation.HWND hwndOwner);
...
}
```

## Expected behavior

The expected behaviour is to return [HRESULT](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-imodalwindow-show)

## Repro steps

1. `NativeMethods.txt` content:
```
IFileSaveDialog
```

2. `NativeMethods.json` content (if present):
```json
```

3. Any of your own code that should be shared?

### Context

- CsWin32 version: `0.1.631-beta`
- Win32Metadata version (if explicitly set by project):
- Target Framework: `net50`

**Comment by jnm2** [comment]
I get why this may be happening, but it was a pain for me too. Not a nice default.

**Comment by AArnott** [comment]
By default, APIs are not generated with PreserveSig. Where you need to override it you can do so like this:

https://github.com/microsoft/CsWin32/blob/8ad40ab5f25843d916839ffd370b301fb81cfc1b/test/GenerationSandbox.Tests/NativeMethods.json#L5

Let's keep this issue active though. There are several APIs that cannot be meaningfully used without access to the HRESULT and we do have a plan to make those PreserveSig by default. I want to make sure this API is on the list.

**Comment by AArnott** [comment]
[The docs](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-imodalwindow-show) for this particular API do not suggest to me that other success codes other than S_OK may be returned from this API. We are looking at automatically using PreserveSig for those APIs that may throw S_FALSE or similar non-error codes. For those that return errors, an exception is the default .NET behavior so we conform to that.

If this API does return non-S_OK success codes, please file a bug at https://github.com/microsoft/win32metadata asking them to add the `preservesig` flag to that API as they've done for https://github.com/microsoft/win32metadata/issues/559.

**Comment by jnm2** [comment]
@AArnott The docs at your link say why it's so important to know what the return code is:

> If the method succeeds, it returns S_OK. Otherwise, it returns an HRESULT error code, including the following:
> Return code | Description
> -- | --
> HRESULT_FROM_WIN32(ERROR_CANCELLED) | The user closed the window by cancelling the operation.

You can't build a file dialog without this, I don't think. I ran into the same roadblock and backed away from CsWin32 for this on this exact point.

**Comment by AArnott** [comment]
I see that errors can be returned in the docs, yes. But without PreserveSig, any error code turns into an exception being thrown so you'll still be able to tell that an error occurred and even retrieve the error code from the exception.

**Comment by jnm2** [comment]
Oh, I see what you mean, but ew. Exceptions as flow control? This is semantically correct COM consumption?

**Comment by AArnott** [comment]
It's the .NET default for interop. But yes, I share your distaste for it particularly when you *expect* error results. For those, manually adding them to the json file for preservesig to be applied as I mention in https://github.com/microsoft/CsWin32/issues/465#issuecomment-993819280, or making the case in win32metadata that these should better be generated with the preservesig flag are the options we have.
