### ISSUE TITLE
Macro generation

### ISSUE THREAD

**Issue by virzak** [microsoft/CsWin32#466]
**Is your feature request related to a problem? Please describe.**

There are Macros available for C++ users, which have to be implemented every time by C# consumers:

[HRESULT_FROM_WIN32](https://docs.microsoft.com/en-us/windows/win32/api/winerror/nf-winerror-hresult_from_win32) is one such macro, but the documentation tree specifies a few others. There are [multiple](https://github.com/search?q=HRESULT_FROM_WIN32+extension%3Acs) repeated implementations of this macro.

**Describe the solution you'd like**

Generating macros like that would be useful. Could be done by default or through options.

**Describe alternatives you've considered**

The only alternative is to implement the macro by hand

**Comment by AArnott** [comment]
The Win32metadata repo has indicated that it will not include macros (https://github.com/microsoft/win32metadata/issues/326). If there are specific macros that would be very valuable in a C# context, please raise them as individual issues and we can consider special casing them.

**Comment by AArnott** [comment]
#666 adds `HRESULT_FROM_WIN32` as a macro that can be generated.
