### ISSUE TITLE
DesktopWallpaper generated as a struct instead of a class

### ISSUE THREAD

**Issue by rgl** [microsoft/CsWin32#473]
## Actual behavior

The `Windows.Win32.UI.Shell.DesktopWallpaper` type is generated as a `struct` instead of a `class`:

![image](https://user-images.githubusercontent.com/43356/147882022-3bede838-cee6-43ca-be97-b2dd0bd70177.png)

## Expected behavior

I expected it to be generated as a `class` and with the `ComImport` attribute.

To make this work, I had to manually create the `DesktopWallpaperCoClass` class:

```csharp
using Windows.Win32;
using Windows.Win32.UI.Shell;
using System.Runtime.InteropServices;
using SkiaSharp;

namespace Example
{
    [ComImport]
    [Guid("C2CF3110-460E-4FC1-B9D0-8A1C0C9CC4BD")]
    public class DesktopWallpaperCoClass
    {
    }

    class Program
    {
        static void Main(string[] args)
        {
            var desktopWallpaper = (IDesktopWallpaper)new DesktopWallpaperCoClass();

            desktopWallpaper.GetBackgroundColor(out uint backgroundColorNative);

            var backgroundColor = new SKColor(backgroundColorNative);
            Console.WriteLine("BackgroundColor={0}", backgroundColor);
        }
    }
}
```

## Repro steps

1. `NativeMethods.txt` content:
```csharp
// NB this file is handled by the Microsoft.Windows.CsWin32 package source generator from:
//          https://github.com/microsoft/CsWin32/blob/v0.1.619-beta/src/Microsoft.Windows.CsWin32/SourceGenerator.cs#L20

DesktopWallpaper        // aka Windows.Win32.UI.Shell.DesktopWallpaper
IDesktopWallpaper       // aka Windows.Win32.UI.Shell.IDesktopWallpaper
```

2. `NativeMethods.json` content (if present):
```json
```

3. Any of your own code that should be shared?

Please see the above `Expected behavior` section.

I would appreciate guidance on whether its the correct way of doing this.

### Context

- CsWin32 version: `0.1.619-beta`
- Win32Metadata version (if explicitly set by project):
- Target Framework: `net6.0-windows`
- `LangVersion` (if explicitly set by project): [e.g. `9`]

**Comment by jnm2** [comment]
I believe this may already be fixed in the main branch: https://github.com/microsoft/CsWin32/issues/453#issuecomment-977010738

**Comment by rgl** [comment]
Indeed it is! Thank you for pointing that out!

Changing the reference to:

```xml
  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.CsWin32" Version="0.1.631-beta">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>
```

And using the daily repository by adding a `nuget.config` file (to the current directory) with the content:

```xml
<configuration>
  <packageSources>
    <add key="winsdk" value="https://pkgs.dev.azure.com/azure-public/winsdk/_packaging/CI/nuget/v3/index.json" />
  </packageSources>
</configuration>
```

Did the trick!
