### ISSUE TITLE
Implicit conversion of `nint` to `HWND`

### ISSUE THREAD

**Issue by Turnerj** [microsoft/CsWin32#481]
**Is your feature request related to a problem? Please describe.**
I'm working on some code that wraps various PInvoke calls etc generated by the source generator.
Because the types generated are internal, if I need to expose the value of a handle to external code I'm using `nint`.
Currently `nint` has implicit conversion from `HWND` but only explicit conversion to `HWND`.

It is just a tiny bit annoying that I need to explicitly cast back to `HWND` to do the PInvoke calls.

**Describe the solution you'd like**
Add an implicit conversion for `nint` to `HWND`.

**Describe alternatives you've considered**
There really isn't many alternatives that _this_ project can do. Obviously on my end, I could either keep explicitly casting everywhere but that gets old fast, like I'm fighting with the tool.

**Comment by Turnerj** [comment]
Actually just realised a workaround for changes here - the types are partials so I can just create my own partial extensions of the types and add the implicit binding.

While I think it would be useful to still do in-the-box, I can at least solve it for me.

**Comment by jnm2** [comment]
I think requiring an explicit cast is a feature, since `IntPtr`/`nint` are stripped of semantic information about what they mean.

**Comment by Turnerj** [comment]
> I think requiring an explicit cast is a feature, since `IntPtr`/`nint` are stripped of semantic information about what they mean.

That's a good point - I was actually gonna tag you earlier when I saw your reaction to the post to ask what your thoughts were.

My actual workaround of using partials to add an implicit conversion didn't work as you can't have both implicit and explicit at the same time. Ended up just having a private property on each of my types like so:

```csharp
private HMONITOR Win32Handle => new(Handle);
```

With what you mentioned though, it does make me think I _could_ just have my own handle struct which I could implicitly convert to-and-from the `HWND` type - that way my public API can still work while integrating easily with the generated Win32 bindings.

**Comment by jnm2** [comment]
> Because the types generated are internal, if I need to expose the value of a handle to external code I'm using `nint`.

This is the part I'm focusing on first. @AArnott Is there something James can do to expose just the single type `HWND` as a public library type if he wants? Or maybe it would be recommended for him to declare it manually to replace the source generator's output and prevent implicitly changing public API?

**Comment by AArnott** [comment]
> Because the types generated are internal

@turnerj You can make it generate public APIs. See [our readme](https://github.com/microsoft/CsWin32#customizing-generated-code).

> Or maybe it would be recommended for him to declare it manually to replace the source generator's output and prevent implicitly changing public API?

Yes, this is what I'd recommend. Unless your library's purpose is to expose p/invoke APIs and can handle the rapid breaking changes produced by CsWin32, I would recommend you copy/paste the HWND definition from the generated code into your own project and change it to `public`. When you define the type, CsWin32 stops defining it itself, so this process should be pretty easy.
