### ISSUE TITLE
Support TOPMOST etc constants for `HWND`

### ISSUE THREAD

**Issue by Turnerj** [microsoft/CsWin32#482]
**Is your feature request related to a problem? Please describe.**
Currently doing a call to [`SetWindowPos`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowpos) requires me to specify a magic number or define my own constants for `hWndInsertAfter`.

Because the documentation lists the fixed 4 values it is expecting, it would be worthwhile having that generated when `SetWindowsPos` method is generated.

**Describe the solution you'd like**
Constants on `HWND` itself for the following:
- HWND_BOTTOM: 1
- HWND_NOTOPMOST: -2
- HWND_TOP: 0
- HWND_TOPMOST: -1

**Describe alternatives you've considered**
I could just create the constants manually from the documentation in my own project but it would be more discoverable being something that can autocomplete more easily on the generated method.

**Comment by Turnerj** [comment]
Nevermind - while re-reading the readme, I saw that you can include constants and then they are imported. Was able to import `HWND_TOPMOST` by adding it to the `NativeMethods.txt` file.

Admittedly, I think it would be better on the `HWND` type rather than the `PInvoke` type but 🤷‍♂️.

**Comment by AArnott** [comment]
Thank you for your feedback, @turnerj. In fact #340 tracks the work that will suit your suggestion I think.
