### ISSUE TITLE
Passing unioned struct to OpenVirtualDisk returns INVALID_PARAMTERS

### ISSUE THREAD

**Issue by Rainmaker52** [microsoft/CsWin32#484]
I'm trying to open a virtual harddisk using the OpenVirtualDisk function (https://docs.microsoft.com/en-us/windows/win32/api/virtdisk/nf-virtdisk-openvirtualdisk).
The problem I'm having is that I'm unable to pass the "OPEN_VIRTUAL_DISK_PARAMETERS" structure, which honestly is a bit of a weird struct. https://docs.microsoft.com/en-us/windows/win32/api/virtdisk/ns-virtdisk-open_virtual_disk_parameters

If I try: 
```cs
var storageType = new VIRTUAL_STORAGE_TYPE()
{
    DeviceId = 3,
    VendorId = Guid.Parse("EC984AEC-A0F9-47e9-901F-71415A66345B")
};

var success = Windows.Win32.PInvoke.OpenVirtualDisk(
            in storageType,
            @"D:\Hyper-V\Virtual Disks\Linux.vhdx", 
            VIRTUAL_DISK_ACCESS_MASK.VIRTUAL_DISK_ACCESS_ATTACH_RO | VIRTUAL_DISK_ACCESS_MASK.VIRTUAL_DISK_ACCESS_GET_INFO, 
            OPEN_VIRTUAL_DISK_FLAG.OPEN_VIRTUAL_DISK_FLAG_CACHED_IO,
            null,
            out var myHandle);

```
it works.
But, I'd like to explicitly open the disk readonly. Because of the union, I need to define it like this:

```cs
var openParams = new OPEN_VIRTUAL_DISK_PARAMETERS()
        {
            Version = OPEN_VIRTUAL_DISK_VERSION.OPEN_VIRTUAL_DISK_VERSION_2,
            Anonymous = new OPEN_VIRTUAL_DISK_PARAMETERS._Anonymous_e__Union
            {
                Version2 = new OPEN_VIRTUAL_DISK_PARAMETERS._Anonymous_e__Union._Version2_e__Struct()
                {
                    ReadOnly = true
                }
            }   
        };

```
(thank you IntelliSense).
If I then open the disk using 
```cs
        var success = Windows.Win32.PInvoke.OpenVirtualDisk(
            in storageType,
            @"D:\Hyper-V\Virtual Disks\Linux.vhdx", 
            VIRTUAL_DISK_ACCESS_MASK.VIRTUAL_DISK_ACCESS_ATTACH_RO | VIRTUAL_DISK_ACCESS_MASK.VIRTUAL_DISK_ACCESS_GET_INFO, 
            OPEN_VIRTUAL_DISK_FLAG.OPEN_VIRTUAL_DISK_FLAG_CACHED_IO,
            openParams,               // Changing this to openParams makes the command fail
            out var myHandle);

```

the returncode is 87 (ERROR_INVALID_PARAMETER).

Is there a "trick" to passing the unioned struct? Would I need to pass it differently?

I am noticing that, contrary to the VIRTUAL_STORAGE_TYPE struct, this one is not accepting the "in" keyword.
Is there something wrong with the source generation, is my usage wrong, or can these unioned structs simply not work?

**Comment by AArnott** [comment]
tip: You don't have to specify `in` for an argument whose parameter is declared with `in`. C# lets you omit it.

Union structs should work. They are declared in C# such that although the syntax for initializing them may feel very unnatural, they should layout in memory in a compatible way for Win32. 

Are you sure you are initializing the struct adequately? Have you tried writing similar code in C to test your inputs?

**Comment by Rainmaker52** [comment]
Thank you for your response.

I think you are correct, and this seems to be a documentation error.

I found https://github.com/Microsoft/Windows-classic-samples/blob/main/Samples/Hyper-V/Storage/cpp/RawIO.cpp which has a lot of useful information in its comments. Including the fact that the "only valid mode for v2 disks is VIRTUAL_DISK_ACCESS_NONE, and apparently also OPEN_VIRTUAL_DISK_FLAG_NONE.

After changing my code to pass those 2 parameters, the call returned 0.

It's very weird behavior in my opinion (should have given error 87 regardless of whether I'm passing an optional parameter or not), but that's up to the Hyper-V team at Microsoft, and has nothing to do with CsWin32.

Again, thank you for the response.
