### ISSUE TITLE
Offer SafeHandle parameter overloads where 'base type' typedef structs are taken

### ISSUE THREAD

**Issue by AArnott** [microsoft/CsWin32#491]
Consider [the `SelectObject` method](https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-selectobject), which takes an `HGDIOBJ` as its second parameter. This is a 'base type' of sorts among the win32metadata structs. Its `[AlsoUsableFor]` derived types include `HBITMAP` and others which carry `RAIIFree` attributes and thus would warrant a `SafeHandle`. But as `SelectObject` takes the base type, and no `RAIIFree` attribute is applied to that struct, a `SelectObject` overload that takes the base `SafeHandle` type should be generated.

**Comment by jnm2** [comment]
ℹ️ I opened #205 for SelectObject specifically.

**Comment by AArnott** [comment]
Duplicate of #205
