### ISSUE TITLE
ref return struct instead of struct ptr

### ISSUE THREAD

**Issue by AliveDevil** [microsoft/CsWin32#523]
**Describe the solution you'd like**
Currently using ILCreateFromPath requires having unsafe user-code. Ideally having a friendly overload of
> `ref ITEMIDLIST ILCreateFromPath(string path)`

would be appreciated.
This allows using `S.R.CS.Unsafe.IsNullRef()` for further checks whether returned value is indeed null.

My current implementation requires creating a separate method with different name, as there is a signature collision due to C# not taking ref return value into account.
```
/// <inheritdoc cref="ILCreateFromPath(PCWSTR)"/>
public static unsafe ref ITEMIDLIST ILCreateFromPath2(string pszPath)
{
    fixed (char* pszPathLocal = pszPath)
    {
        ITEMIDLIST* __result = ILCreateFromPath(pszPathLocal);
        return ref *__result;
    }
}
```

**Describe alternatives you've considered**
Using `ITEMIDLST*` directly, but that requires annotating a method with unsafe or using unsafe blocks.

**Additional Context**
`ILCreateItemFromPath`[^1] returns `PIDLIST_ABSOLUTE` which, per documentation[^2], needs to be freed with `ILFree`.
Assuming that the returned `ITEMIDLIST` pointer needs to be freed, instead of its value, ILFree would need to change as well:
From:
```
public static unsafe void ILFree(ITEMIDLIST? pidl)
{
	ITEMIDLIST pidlLocal = pidl.HasValue ? pidl.Value : default(ITEMIDLIST);
	ILFree(pidl.HasValue ? &pidlLocal : null);
}
```
to either or both option:
```
public static unsafe void ILFree(ref ITEMIDLIST pidl)
{
    fixed (ITEMIDLIST* pidlLocal = &pidl)
    {
        ILFree(pidlLocal);
    }
}
public static unsafe void ILFree(in ITEMIDLIST pidl)
{
    fixed (ITEMIDLIST* pidlLocal = &pidl)
    {
        ILFree(pidlLocal);
    }
}
```

[^1]: https://docs.microsoft.com/en-us/windows/win32/api/shlobj_core/nf-shlobj_core-ilcreatefrompath
[^2]: https://docs.microsoft.com/en-us/windows/win32/api/shtypes/ns-shtypes-itemidlist

**Comment by AArnott** [comment]
Avoiding `unsafe` isn't a goal of CsWin32, as interop is fundamentally unsafe anyway. And `unsafe` C# code is often easier to read and get right than "safe" code anyway. Just look at pointers vs. IntPtr uses in interop code. 

That said, ref return is an interesting idea. But case in point, if a null result is expected, checking for null is _much_ harder to discover with ref return per your example than if a pointer were returned. It also looks like you just have a reference to a struct, which doesn't scream "you might need to free this" to avoid a memory leak. So I'm honestly seeing more negatives than positives with this proposed change.

**Comment by AliveDevil** [comment]
After figuring out what I really want with this proposal I think it really is not really viable, and requires specific, project dependent code to work properly.

Like this struct[^1] which can be used as a container, just like SafeHandles could, but without the need to generate heap objects. Requires IL manipulation and some quirks to get around, but can be used with "safe" code.
Maybe went too far to get C++/WinRT-style `*_handle`-types in C#.

Though I think I prefer handle types to behave more like this[^2] (without the assignment/conversion magic), which can be used rather easily[^3].
Closing here, unless there is some viability to the latter option, which I don't think will happen (as it is niche to the project I'm using it in).

[^1]: https://github.com/iterate-ch/cyberduck/blob/master/core/src/main/csharp/Windows/Win32/PIDLIST_ABSOLUTEHandle.cs
[^2]: https://github.com/iterate-ch/cyberduck/blob/master/core/src/main/csharp/Windows/Win32/CredHandle.cs
[^3]: https://github.com/iterate-ch/cyberduck/blob/master/core/src/main/csharp/ch/cyberduck/core/credentialmanager/WinCredentialManager.cs#L61-L62
