### ISSUE TITLE
A single pragma disabling multiple warnings can be used

### ISSUE THREAD

**Issue by jnm2** [microsoft/CsWin32#53]
If desired, the generated source can be made more readable:

![image](https://user-images.githubusercontent.com/8040367/105556595-51ccce00-5cd8-11eb-9206-1e32507aaf45.png)

By generating this instead:

```cs
#pragma warning disable CS1591, CS1573, CS0649, CS8019, CS1570
```

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-pragma-warning

**Comment by AArnott** [comment]
Oh! Nice. I wished there was a way to do that but didn't know. Thank you for sharing.
