### ISSUE TITLE
Return Out value instead of "success" boolean (OpenProcessToken, PrivilegeCheck, etc.)

### ISSUE THREAD

**Issue by BinToss** [microsoft/CsWin32#531]
...and if unsuccessful, throw an exception.

**Is your feature request related to a problem? Please describe.**

CreateFile returns a SafeFileHandle, but OpenProcessToken and similar functions returns a boolean to indicate if the function encountered an error. This boolean can be considered redundant if the functions threw exceptions.
If–instead of returning False and writing an error code–OpenProcessToken threw an appropriate exception (e.g. System.UnauthorizedAccessException)

As stated, CreateFile already returns a SafeFileHandle. However, this SafeFileHandle's value can invalid (zero or minus). I would prefer it if an exception is thrown to explain why the SafeFileHandle could not be acquired.
Generating a new Exception Type for each Windows error code along and setting the error code's string as the exception's default Message value or a Message prefix should cover most cases.

```cs
public class FileNotFoundException : Win32Exception
{
  private _baseMessage = "The system cannot find the file specified.";
  private _message = string.empty;

  public Message {
    get => _message;
    set {
      _message = _baseMessage + ' ' + value;
    }
  }

// using dotnet/PInvoke's Win32ErrorCode enum for example
 public readonly override Win32ErrorCode Error => Win32ErrorCode.ERROR_FILE_NOT_FOUND;
}
```

**Describe the solution you'd like**

PInvoke methods that return bools to indicate success should instead return an appropriate Type or throw an Exception with an inner Win32Exception. Ideally, the Type of the the parent exception should indicate the error code e.g. System.IO.FileNotFoundException(message, filename, new Win32Exception())

#### OpenProcessToken
Current
```cs
internal static unsafe winmdroot.Foundation.BOOL OpenProcessToken(SafeHandle ProcessHandle, winmdroot.Security.TOKEN_ACCESS_MASK DesiredAccess, out Microsoft.Win32.SafeHandles.SafeFileHandle TokenHandle)
```
Proposed wrapper
(I wish .NET provided a SafeProcessHandle)
```cs
internal static unsafe Microsoft.Win32.SafeHandles.SafeFileHandle OpenProcessToken(SafeHandle ProcessHandle, winmdroot.Security.TOKEN_ACCESS_MASK DesiredAccess)
```

#### Void function()
Native functions which return only a bool indicating success should instead return void or else throw a new Exception with a Win32Exception inner exception.

**Describe alternatives you've considered**
Manually written wrappers. This becomes tedious esp. when writing new exceptions for Windows error codes.

**Comment by AArnott** [comment]
Thank you for using CsWin32 and for sending the feedback.
CsWin32 isn't scoped to produce a refined, higher-level API. It merely exposes the Win32 APIs as they were written. Making them more .NET friendly by throwing exceptions, etc., is the job of a higher level API such as the BCL itself.
