### ISSUE TITLE
Using Windows.Win32.UI.Controls gives build errors on Microsoft.Windows.CsWin32 0.1.635-beta but not on 0.1.588-beta

### ISSUE THREAD

**Issue by deepthi-msft** [microsoft/CsWin32#532]
## Actual behavior
I am using https://github.com/microsoft/WindowsAppSDK-Samples/tree/main/Samples/Windowing cs-winui sample app.
However the following 2 usings gives build errors on Microsoft.Windows.CsWin32 0.1.635-beta
using Windows.Win32.UI.Controls;
using static Windows.Win32.Constants;
Errors:
- The type or namespace name 'Constants' does not exist in the namespace 'Windows.Win32' (are you missing an assembly reference?)
- The type or namespace name 'Controls' does not exist in the namespace 'Windows.Win32.UI' (are you missing an assembly reference?)

I observed that when I downgraded to Microsoft.Windows.CsWin32 0.1.588-beta everything builds successfully and I am able to launch the app. So is this a regression?

## Expected behavior
Consistent behavior on Microsoft.Windows.CsWin32 0.1.635-beta as well as 0.1.588-beta 

## Repro steps
1. Download the sample app from https://github.com/microsoft/WindowsAppSDK-Samples/tree/main/Samples/Windowing 
2. Open Windowing\cs-winui sample app in Visual Studio 2022. 
3. Right click on the project and click manage nuget packages. 
    a. Install Microsoft.Windows.CsWin32 0.1.635-beta.
    b. Install Microsoft.WindowsAppSDK 1.1.0-preview1
    c. Install Microsoft.Windows.SDK.BuildTools 10.0.22598-preview 

5. Now launch Windowing(package) app
The app doesn't launch because of build errors:
Error CS0234 The type or namespace name 'Controls' does not exist in the namespace 'Windows.Win32.UI' (are you missing an assembly reference?) Windowing E:\WindowsAppSDKSample10-3\WindowsAppSDK-Samples-main\Samples\Windowing\cs-winui\MainWindow.xaml.cs 11 Active
Error CS0234 The type or namespace name 'Constants' does not exist in the namespace 'Windows.Win32' (are you missing an assembly reference?) Windowing E:\WindowsAppSDKSample10-3\WindowsAppSDK-Samples-main\Samples\Windowing\cs-winui\MainWindow.xaml.cs 13 Active

6. Any of your own code that should be shared?

### Context

- CsWin32 version: 0.1.635-beta
- Win32Metadata version (if explicitly set by project):Not explicitly set. 17.0.2-preview

**Comment by AArnott** [comment]
The upgrade your spanning changes namespaces of generated APIs. Resolving this is as easy as deleting the two lines that the compiler is complaining about.
