### ISSUE TITLE
Structs and enums not getting generated

### ISSUE THREAD

**Issue by shv07** [microsoft/CsWin32#534]
## Actual behavior

I am trying to generate all the methods, structs, enums, etc. within a module (User32.dll here). I am able to get the methods but not the structs or enums (like ImageType, MENUITEMINFOA, etc. 

## Repro steps

1. `NativeMethods.txt` content:
```
// Tried using just 'User32' too
User32.*
```

2. `NativeMethods.json` content (if present):
Not present

3. Any of your own code that should be shared?
Not relevant
### Context

- CsWin32 version: 0.1.635-beta
- Win32Metadata version (if explicitly set by project): Not set
- Target Framework: net6.0-windows10.0.19041
- `LangVersion` (if explicitly set by project): Not set

**Comment by AArnott** [comment]
Structs and enums are not in the dll. Those are declared in headers, which can be consumed from anywhere. As such, `User32.*` does not select them. That wildcard only gives you *methods*, and the types to support their signatures. If you want a struct or enum that isn't automatically brought in by a method in user32, you'll have to ask for it explicitly in your NativeMethods.txt file.
