### ISSUE TITLE
Can't upgrade to 0.1.646-beta from 0.1.635-beta

### ISSUE THREAD

**Issue by virzak** [microsoft/CsWin32#535]
## Actual behavior

Looks like this is the actual bug:

```
warning CS8785: Generator 'SourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'IOException' with message 'The process cannot access the file 'C:\Users\virzak\.nuget\packages\microsoft.windows.sdk.win32metadata\17.0.2-preview\Windows.Win32.winmd' because it is being used by another process.'
```

## Repro steps

1. `NativeMethods.txt` content:
```
GetWindowLong
SetWindowLong
WINDOW_STYLE
```

### Context

- CsWin32 version: 0.1.646-beta
- Target Framework: net6
- `LangVersion` preview (C# 11)

**Comment by virzak** [comment]
Ok, there is definitely an issue with this release. The first time generation works fine, but rebuilding fails. Looks like the generation locks the nuget package.

**Comment by AArnott** [comment]
Thanks for your report. The new version should only ever open the file *once*. I wonder if in your case you have a mix of analyzers versions in the process (or another process also has the file open). This latest version _does_ have a regression where it fails to be willing to share read locks on the file with others. I'll get that fixed.

**Comment by virzak** [comment]
`Microsoft.Windows.CsWin32` was the only package in the project, so no other analyzers.

**Comment by AArnott** [comment]
I suspect CsWin32 was loaded with both the latest and older versions in the process (older versions don't get unloaded when you upgrade till you restart VS). It's not a bug on your side. This is our bug. I should have a fix out later today. Thank you for reporting.

**Comment by AArnott** [comment]
Watch for a new version to be pushed to nuget.org sometime in the next 24 hours.

**Comment by virzak** [comment]
Thanks, I have a unique disorder where I run `dotnet outdated` every 10 minutes

**Comment by AArnott** [comment]
0.1.647-beta is now on nuget.org (being indexed, so it's invisible for a few more minutes.)
