### ISSUE TITLE
README animated gif should demo default internal visibility

### ISSUE THREAD

**Issue by jnm2** [microsoft/CsWin32#54]
Can the visibility for static classes be `internal` by default? Most libraries that use APIs would not want to expose and take on the burden of maintaining those APIs to consumers of the library.

![image](https://user-images.githubusercontent.com/8040367/105556857-e7685d80-5cd8-11eb-9ddf-15d585a5970e.png)

**Comment by AArnott** [comment]
The default _is_ for all generated types to be `internal`. Are you sure you don't have a `NativeMethods.json` file that sets the public flag to true?

**Comment by dotMorten** [comment]
I'm seeing them as internal too.

**Comment by AArnott** [comment]
@jnm2 Let me know if you continue to have the problem and please send a repro .zip if possible. I'm going to close the issue for now, but if you comment here later, I'll see it.

**Comment by jnm2** [comment]
@AArnott I took that screenshot from the GIF in the readme which gives the impression that `public` is the default.

**Comment by dotMorten** [comment]
That gif doesn't show any of the generated code?

**Comment by AArnott** [comment]
@dotMorten, the gif is animated. If you watch it all, you will indeed see the generated code, and @jnm2 is right that it shows public modifiers there. I'll recapture the animation with the default `internal` visibility to make it clearer that this is an appropriate choice for libraries.

**Comment by AArnott** [comment]
We also need an update to remove showing the need for `AdditionalFiles` items in the project file.
