### ISSUE TITLE
Why there is not the StructLayoutAttribute on structures?

### ISSUE THREAD

**Issue by raffaeler** [microsoft/CsWin32#541]
## Actual behavior
I requested the generation of the Win32 `DCB` structure and the code generator generated this:

![image](https://user-images.githubusercontent.com/5183152/167873055-4d2ed2ea-2a64-4f71-a8c5-0073405629df.png)

I can see potential problems when the structure is missing the `[StructLayout(LayoutKind.Sequential)]`
Why are the structures generated without the attribute?

## Expected behavior

I expect to see the attribute  `[StructLayout(LayoutKind.Sequential)]` on the generated structure declaration.

## Repro steps

1. `NativeMethods.txt` content:
```
DCB
```

2. No `NativeMethods.json` content

3. Any of your own code that should be shared?

### Context
- `<PackageReference Include="Microsoft.Windows.CsWin32" Version="0.1.647-beta">`
- Target Framework: [e.g. `net6.0`]
- `LangVersion` not set

**Comment by jnm2** [comment]
I thought `[StructLayout(LayoutKind.Sequential)]` was already the default for every struct.

**Comment by AArnott** [comment]
Sequential is default in C#: https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.structlayoutattribute?view=net-6.0#remarks
So no need to emit it.
