### ISSUE TITLE
ReadFile and WriteFile do not match with .NET overlapped structure

### ISSUE THREAD

**Issue by raffaeler** [microsoft/CsWin32#545]
## Actual behavior

The signature generated for the `ReadFile` and `WriteFile` structures is:
```cs
internal static unsafe winmdroot.Foundation.BOOL WriteFile(SafeHandle hFile, void* lpBuffer,
    uint nNumberOfBytesToWrite, uint* lpNumberOfBytesWritten,
    winmdroot.System.IO.OVERLAPPED* lpOverlapped) {}
```
On the other hand, .NET already defines `System.Threading.NativeOverlapped` which must be used with `ThreadPoolBoundHandle.GetNativeOverlappedState` and other APIs.

As a consequence, when using the asynchronous behaviour on Windows, I can't rely on the generated code, but I have to define separately the PInvokes.

Please note that this is also true for other APIs like:
- GetOverlappedResult
- ClearCommError
- WaitCommEvent
- WIN32_ERROR (must be casted to match `Marshal.GetLastWin32Error()`

## Expected behavior

Whenever .NET defines some interop code, I expect the generated code matches them. Or at least provides a different overload with a native pointer so that it can be used with code different than the one created by the genrator.
In general, when there is a pointer, it would be useful to get overloads with a "void*" to avoid being blocked.

## Repro steps

1. `NativeMethods.txt` content:
```
CreateFile
ReadFile
WriteFile
GetOverlappedResult
CloseHandle
```

2. `NativeMethods.json` content (if present):

N/A

3. Any of your own code that should be shared?

Not needed

### Context

- CsWin32 version: `<PackageReference Include="Microsoft.Windows.CsWin32" Version="0.1.647-beta">`
- Win32Metadata version: N/A
- Target Framework: net6.0
- `LangVersion` : N/A

**Comment by AArnott** [comment]
Interoperating with existing .NET APIs is certainly desirable. Let's see what we can do here.

**Comment by AArnott** [comment]
Thank you for the feedback. We'll get the Overlapped struct issue fixed. For the other APIs, please open individual issues if there are more .NET structs that we should use instead of generating our own.
As for the WIN32_ERROR cast, that's by design. Sadly, C# doesn't allow us to express structs with implicit conversion operators.

**Comment by raffaeler** [comment]
@AArnott  From what I see the fix is valid for any Win32 function using the `Overlapped` structure, right?
In other words, this include also the fix for ReadFileEx and WriteFileEx and other APIs, right?

BTW what is the trigger that updates the nuget package? When should I expect to see it?

Thank you!

**Comment by AArnott** [comment]
Yes, the fix will replace all uses of `Overlapped`, altering all the APIs that reference it.

I expect to release another CsWin32 to nuget.org by Thursday of this week.
