### ISSUE TITLE
Can't work in WinUI 3 project

### ISSUE THREAD

**Issue by huoyaoyuan** [microsoft/CsWin32#59]
Start from WinUI 3 Preview 3 template project

Add package reference to `Microsoft.Windows.CsWin32`, with `GetActiveWindow` in NativeMethods.txt
Make a call to the method anywhere.

The IDE can correctly analysis all the occurrence and references of the method. However, when building the project, the command line output shows error CS0234: No member 'Windows' in namespace 'Microsoft'.

I think this is https://github.com/dotnet/roslyn/issues/46420 , in another way.

**Comment by AArnott** [comment]
I am not familiar with WinUI 3. But the symptoms are very similar to #7. Can you try the workaround documented there to see if it helps? Otherwise, we may need to move your bug to the WinUI team.

**Comment by huoyaoyuan** [comment]
No, the workaround for #7 doesn't work here.

Seems that WinUI invokes legacy roslyn somehow.

**Comment by AArnott** [comment]
@huoyaoyuan Where can I get this WinUI project template you're talking about so I can test it? Any idea where we can file issues against it?

**Comment by huoyaoyuan** [comment]
@AArnott

https://github.com/microsoft/microsoft-ui-xaml
https://aka.ms/winui3/preview3-download

I can open issue myself there. They have been incompatible with several compiling stuff like `dotnet build`, `<Nullable>enable</Nullable>`.

If you have internal contacts, you may ask them about their interaction with roslyn and msbuild team. Thanks.

**Comment by dotMorten** [comment]
I'm successfully using this with WinUI3. I've used this to have my WinUI3 app generate a tray icon, and clicking the tray icon will bring the WinUI3 window to the top.

**Comment by huoyaoyuan** [comment]
I'm targeting Win32.

**Comment by dotMorten** [comment]
OK this is odd. Just created a new project and hit the same thing while compiling:

![image](https://user-images.githubusercontent.com/1378165/105883139-597fc180-5fbb-11eb-93ef-0ab6b2ffe122.png)

**Comment by dotMorten** [comment]
Investigating some more: The reason it worked for me was I was building a class library. But the moment I add XAML to that class library, this error occurs.

**Comment by huoyaoyuan** [comment]
Yes. The `#nullable` issue occurs too when I add XAML. So I suspect they have the same root cause.

**Comment by dotMorten** [comment]
Seems like the `XamlPrecompile` step isn't including the generated files, and thus fails:
![image](https://user-images.githubusercontent.com/1378165/105885789-74a00080-5fbe-11eb-8a2e-5f30ec65d8b0.png)

**Comment by huoyaoyuan** [comment]
OK. So if `XamlPrecompile` invokes csc with custom command line and may not respect `csproj`, it's reasonable to report warning for no `<Nullable>enable</Nullable>`.

**Comment by dotMorten** [comment]
Seems duplicate to this: https://github.com/dotnet/roslyn/issues/46300

**Comment by Sergio0694** [comment]
Not sure if this has already been mentioned, but it seems this is not specific to WinUI 3 - I get the same exact error when trying to use a source generator that interacts with a XAML-related file in any way on vanilla UWP (SDK 19041) as well 🤔

**Comment by dotMorten** [comment]
@Sergio0694 Yes agreed. Not specific to this. It should probably be moved to the WinUI repo

**Comment by AArnott** [comment]
Some investigations led to https://github.com/dotnet/msbuild/pull/6096, which may fix the WinUI problem.

**Comment by dotMorten** [comment]
@AArnott That helps some. 
As mentioned in email offline, the code generator need to prefix usings with `global::` or it'll clash with WinUI. (props to @chsienki for discovering this)

**Comment by dotMorten** [comment]
Just confirming that 0.1.370-beta works great with WinUI 3. Thank you!
