### ISSUE TITLE
Consider implementing Dispose pattern for handle typedefs

### ISSUE THREAD

**Issue by AArnott** [microsoft/CsWin32#596]
When a typedef struct represents a releasable handle, we could implement `IDisposable` so that C# `using` syntax would allow deterministic release of these handle.

**Comment by elachlan** [comment]
I think this will be blocked by the solution in #610, which should establish how to reliably identify what nativedef structs are handles.

**Comment by AArnott** [comment]
I don't think so... #610 is about picking which structs should get an `IsNull` property, but _this_ issue only needs to know whether a given typedef struct has a releaser method, which we already know.

**Comment by elachlan** [comment]
Yes, I guess we have to know HOW to release it, to be able to release it. Adding this won't be too bad.

**Comment by elachlan** [comment]
Should this be able to be turned on/off by a setting? Or would there be no benefit in that?

**Comment by AArnott** [comment]
I don't anticipate any downside to it, so I wouldn't add a switch unless a downside presents itself.

**Comment by elachlan** [comment]
@AArnott if we add `IDisposable` to a struct, do we also need to add an `bool ownsHandle` similar to `safehandles`? That way we can handle when a method is tagged with `DoNotReleaseAttribute`?

**Comment by jnm2** [comment]
The handle struct would no longer be blittable and would also be subject to tearing.

**Comment by elachlan** [comment]
So we can't use `IDisposable` then on any struct that is used by a method which has the `DoNotReleaseAttribute`.

**Comment by AArnott** [comment]
No, it's not the `IDisposable` that would present the problems that @jnm2 calls out. It's the additional field where we would store the `ownsHandle` value.
If folks want .NET/C# to help with disposal of native resources, SafeHandle is the standard. The typedef structs are the native primitive that folks use when they specifically want to control lifetime themselves and/or cannot take the GC pressure of a SafeHandle. To make the struct disposable may be interesting, but it blurs the line. And if it led to analyzers producing warnings when they are not disposed of, that would violate a major point of falling back to them in the first place.

So maybe we could do the IDisposable struct thing if we new analyzers don't and would never call out disposing them. But I'm leaning against doing it at all given that's SafeHandle territory.

**Comment by elachlan** [comment]
That is probably a good idea. So should we close this issue or limit it to structs without associated methods tagged with `DoNotReleaseAttribute`? I don't really have an opinion either way.

**Comment by AArnott** [comment]
Given the risk that an analyzer exists or comes long that would try to coerce people to dispose of their typedef structs, I'd lean toward not implementing `IDisposable`, and continue to collect feedback.

**Comment by michael-hawker** [comment]
Was just translating some code from another PInvoke library to CsWin32, it was nice they handled the Disposable from CreateRectRgn on the HGRN object. That way they could just use C#'s using statement handle everything in scope:

```cs
using var rgn = PInvoke.CreateRectRgn(-2, -2, -1, -1);
```
