### ISSUE TITLE
Ability to turn off usage of safe handles in overloads

### ISSUE THREAD

**Issue by fernandanavamoya** [microsoft/CsWin32#605]
**Is your feature request related to a problem? Please describe.**
In Windows Forms we generally don't use safe handle in our interop but we do use string marshalling. In order to use the friendly overloads we need to turn off the usage of safe handles.

For example, this:

``` C#
IntPtr threadHandle = (ctx is null ? IntPtr.Zero : ctx.GetHandle());

if (threadHandle != IntPtr.Zero)
{
    Kernel32.GetExitCodeThread(threadHandle, out uint exitCode);
```

Becomes this:

``` C#
nint threadHandle = (ctx is null ? 0 : ctx.GetHandle());

if (threadHandle != 0)
{
     uint exitCode;
     PInvoke.GetExitCodeThread((Foundation.HANDLE)threadHandle, &exitCode);

```
**Describe the solution you'd like**
An option to disable safe handle usage.

**Comment by JeremyKuhne** [comment]
This blocked us from using `HMODULE GetModuleHandle(PCWSTR)` as we couldn't hack around the generated easy wrapper that returned the `SafeHandle`. We had to use `GetModuleHandleEx` to avoid getting a safe handle. There is also a bug in the generated `GetModuleHandle` safe overload, opening a bug on it.

**Comment by JeremyKuhne** [comment]
The GetModuleHandle bug: https://github.com/microsoft/CsWin32/issues/616
