### ISSUE TITLE
Generate HKL IsNull helper

### ISSUE THREAD

**Issue by elachlan** [microsoft/CsWin32#610]
As per https://github.com/dotnet/winforms/pull/7451#discussion_r926180298 `HKL` is missing the `IsNull` helper talked about in https://github.com/microsoft/CsWin32/issues/206

**Comment by elachlan** [comment]
Is this where we make the change?
https://github.com/microsoft/CsWin32/blob/2a9343502baebcf0787ad88a663da02acab55b69/src/Microsoft.Windows.CsWin32/Generator.cs#L3776-L3788

**Comment by elachlan** [comment]
Foundation.HWND doesn't seem to have an IsNull property, Graphics.Gdi.HGDIOBJ does.

`Error CS1061 'HWND' does not contain a definition for 'IsNull' and no accessible extension method 'IsNull' accepting a first argument of type 'HWND' could be found (are you missing a using directive or an assembly reference?`

**Comment by elachlan** [comment]
@AArnott I think the issue is because `Foundation.HWND` uses `nint` and `Graphics.Gdi.HGDIOBJ` uses `IntPtr`.

This code only checks `IntPtr` and `UIntPtr`. 
https://github.com/microsoft/CsWin32/blob/2a9343502baebcf0787ad88a663da02acab55b69/src/Microsoft.Windows.CsWin32/Generator.cs#L3920-L3928

I think this:
```csharp
if (fieldType is IdentifierNameSyntax { Identifier: { Value: nameof(IntPtr) or nameof(UIntPtr) } })
```

needs to change to:
```csharp
if (fieldType is IdentifierNameSyntax { Identifier: { Value: nameof(IntPtr) or nameof(UIntPtr) or nameof(nint) or nameof(nuint) } })
```

I'll create a PR if you are happy with that.

**Comment by AArnott** [comment]
That's where I suspected the bug to be too. We have had a little churn in whether we generate IntPtr or nint lately. I think though, rather than update the condition check to allow for `nint`, I'd rather fix the generator to produce `IntPtr` as it is intended to. I realize in C# 11 it's equivalent, but that's not out yet, and `IntPtr` does a better job of conveying "this is a pointer-sized opaque value" than `nint` does.

**Comment by elachlan** [comment]
I played around with it and I think its caused by `PreferNativeInt` on the `generalTypeSettings` in Generator:
https://github.com/microsoft/CsWin32/blob/2a9343502baebcf0787ad88a663da02acab55b69/src/Microsoft.Windows.CsWin32/Generator.cs#L386-L393

This causes the output to change:
https://github.com/microsoft/CsWin32/blob/6ea3f448867d9fafb9ae24e04ea5a10b5f483d1d/src/Microsoft.Windows.CsWin32/PrimitiveTypeHandleInfo.cs#L24-L47

So I guess we hardcode it for now and update it once `LanguageVersion.CSharp11` is included in `Microsoft.CodeAnalysis.CSharp`?

**Comment by AArnott** [comment]
Thanks for looking.

We *want* the general type settings to prefer `nint` over `IntPtr` though. It's only in the handle structs that we want to prefer IntPtr. We have code to do this, but it's failing... somewhere. 

I wouldn't bother changing it again for C# 11, since if they _are_ equivalent, there's no value in switching from one to the other.

**Comment by jnm2** [comment]
And in C# 11 I still feel like showing the type as `IntPtr` versus `nint` carries useful expectations on the meaning of the contents.

**Comment by AArnott** [comment]
While I agree with you, @jnm2, I suspect time will judge differently. When everyone is using C# 11+ and the two are truly aliases of each other, I suspect people will consider them as equivalent as `int` and `Int32`. These days we do still split hairs (at least I do) in preferring `int` but using `Int32` when I want to be explicit about its length -- not because I have to, but it can be useful when implementing network protocols. Time will tell how people feel about IntPtr vs. nint at that point. But it certainly can do no _harm_ to continue to use IntPtr here, and it certainly is useful to do so in the hear and now.

**Comment by elachlan** [comment]
This is the code where it decides if a Handle struct is a handle:
https://github.com/microsoft/CsWin32/blob/2a9343502baebcf0787ad88a663da02acab55b69/src/Microsoft.Windows.CsWin32/Generator.cs#L3776-L3788

I think because there is no method for releasing the `HKL`, there is no hit in `MetadataIndex.HandleTypeReleaseMethod`. So then its up to the special cases section.

A lot of these types are `DECLARE_HANDLE` and have the `InvalidHandleValues` value. Could we use that?
https://github.com/microsoft/win32metadata/blob/5687b3cb4868c3142b98091ee970464f55219406/generation/WinSDK/autoTypes.json#L114-L118

Would `IsNull` still make sense in that context?

**Comment by elachlan** [comment]
I think this works:
```csharp
private bool IsHandle(TypeDefinitionHandle typeDefHandle, out string? releaseMethodName)
{
    if (this.MetadataIndex.HandleTypeReleaseMethod.TryGetValue(typeDefHandle, out releaseMethodName))
    {
        return true;
    }
    else if (this.GetInvalidHandleValues(typeDefHandle).Count > 0) {
        return true;
    }

    // Special case handles that do not carry RAIIFree attributes.
    releaseMethodName = null;
    TypeDefinition typeDef = this.Reader.GetTypeDefinition(typeDefHandle);
    return this.Reader.StringComparer.Equals(typeDef.Name, "HGDIOBJ")
        || this.Reader.StringComparer.Equals(typeDef.Name, "HWND");
}
```

But `CreateCommonTypeDefMembers` would need to change to again check for invalid values and then generate code which checked for the invalid values instead of default?
https://github.com/microsoft/CsWin32/blob/2a9343502baebcf0787ad88a663da02acab55b69/src/Microsoft.Windows.CsWin32/Generator.cs#L3920-L3928

**Comment by elachlan** [comment]
> The typedef structs are (mostly) strongly-typed wrappers for handles.
https://github.com/microsoft/win32metadata/issues/21#issuecomment-812599766

Can you clarify **mostly**?

My above attempts I believe were wrong. I think DeclareTypeDefStruct needs to always have isHandle=true, as its only called when the metadata has the `NativeTypedef` attribute. Additionally, the section in CreateCommonTypeDefMembers which adds `IsNull` checks for `IntPtr` and `UIntPtr`, so that covers the "mostly" part as far as I can tell.

If there is a counter example we can add it to the tests and see if we need additional information from the metadata.

**Comment by elachlan** [comment]
@AArnott should the win32metadata repo just explicitly tag each typedef struct which is a handle? Are all the structs with intptr values handles?

**Comment by AArnott** [comment]
Good question. I don't know. Maybe CsWin32's need for a 'handle' designation is flawed, if the information simply isn't in the header files either.

**Comment by elachlan** [comment]
> Good question. I don't know. Maybe CsWin32's need for a 'handle' designation is flawed, if the information simply isn't in the header files either.

Can you think of an example of a NativeTypedef struct with an IntPtr which isn't a handle?

**Comment by AArnott** [comment]
No. So far I've coded CsWin32 to consider that all typedef structs with intptr are the same.

**Comment by elachlan** [comment]
I think we can refactor the code where ishandle is called. If you ignore the result, the all nativetypedef structs with intptr are generated with IsNull.

**Comment by elachlan** [comment]
@sotteson1 We are looking at how to distinguish between a `NativeTypedef` which is a handle and one that just has an `IntPtr`. It seems like not all `NativeTypedefs` with `IntPtr` are handles since some are defined in autotypes with ` "ValueType": "DECLARE_HANDLE"` and so a new attribute might be required. Am I way off the mark with this?

**Comment by elachlan** [comment]
Found this comment in Winforms, which might help sway us towards wanting to use `nint`/`nuint` over `IntPtr`/`UIntPtr`.
```
// It is particularly dangerous to cast to/from IntPtr on 64 bit platforms as casts are checked.
// Doing so leads to hard-to-find overflow exceptions. We've mitigated this historically by trying
// to first cast to long when casting out of IntPtr and first casting to int when casting into an
// IntPtr. That pattern, unfortunately, is difficult to audit and has negative performance implications,
// particularly on 32bit.
//
// Using the new nint/nuint types allows casting to follow with the default project settings, which
// is unchecked. Casting works just like casting between other intrinsic types (short, int, long, etc.).
```
https://github.com/dotnet/winforms/blob/179df82381b5df175d043c2190306354f8b46cae/src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Message.cs#L39-L50

**Comment by AArnott** [comment]
@elachlan, that comment is interesting and I'd like to learn more. But why post it here on an issue about adding `IsNull`, which may be closed as Won't Fix, but this casting concern should likely have its own discussion lifetime?

**Comment by elachlan** [comment]
> @elachlan, that comment is interesting and I'd like to learn more. But why post it here on an issue about adding `IsNull`, which may be closed as Won't Fix, but this casting concern should likely have its own discussion lifetime?

Basically this issue is caused by the setting for preferring nint over IntPtr.

**Comment by elachlan** [comment]
Adding this here based on Andrew's question in the PR:

> Given how hard it is to get this right, I wonder if it's worth it. Particularly because all this change would do is enable an .IsNull syntax where == default would already do the same. Why is this so important?

I think its less about `.IsNull` and more about CsWin32 and other Win32Metadata consumers not knowing how to tell if something is a handle or not. An attribute in the metadata would remove that ambiguity. Really `.IsNull` is just a symptom of the problem and if the ambiguity isn't rectified in the metadata, I imagine there will be other "symptoms".

**Comment by AArnott** [comment]
> if the ambiguity isn't rectified in the metadata, I imagine there will be other "symptoms".

I would be content to leave the metadata alone so they can focus on more meaningful changes, until one of these other symptoms shows up with a compelling case for fixing. I don't think IsNull is compelling enough. 

@elachlan, if your concern about IntPtr checked casting remains (I suspect it does), can you please file a new issue to track that? Consider that I would _like_ handle typedef's to use `IntPtr` instead of `nint` as their field type. At one point this worked, but I don't know whether that still works. So even if we have `nint` now, we may have IntPtr later unless a discussion (on a new issue) compels me to give it up and use `nint` to avoid checked cast exceptions.

**Comment by elachlan** [comment]
New issue is at #661

**Comment by elachlan** [comment]
I mean, the majority of the typedefstructs work. So the PR isn't a complete failure. Its just if you want complete coverage of all handles then we would need more info from the metadata.
