### ISSUE TITLE
The type or namespace name 'Windows' does not exist in the namespace 'Microsoft'

### ISSUE THREAD

**Issue by Demkeys** [microsoft/CsWin32#611]
.Net SDK version: 6.0.300
CsWin32 version: 0.2.10-beta
I'm using VS Code. The project is a Console app. 

I'm getting the error `The type or namespace name 'Windows' does not exist in the namespace 'Microsoft'` on the line `using Microsoft.Windows.Sdk` . I've tried some of the solutions from other issues, except updating my .Net SDK to a newer version. What I've tried so far doesn't seem to be working.

**Comment by AArnott** [comment]
I'm not familiar with the `Microsoft.Windows.Sdk` namespace. CsWin32 doesn't produce that. It produces types in the `Windows.Win32` namespace. Wanna try than instead?
When you have problems even with that, try `using global::Windows.Win32`.

**Comment by Demkeys** [comment]
UPDATE:
I used the line `using Windows.Win32;` instead, and the error went away. I'm still not able to use `using Microsoft.Windows.Win32` but atleast now I'm able to access PInvoke class and call Win32 API functions, so that solves my problem. Wasn't aware I was supposed to use `Windows.Win32`.

I also get the following warning when compiling and running the program: `warning  
CA1416: This call site is reachable on all platforms. 'PInvoke.GetActiveWin 
dow()' is only supported on: 'windows' 5.0 and later.`. I get it once for each Win32 method call.

That being said, the problem is solved now so I'll close this issue.

**Comment by Demkeys** [comment]
> I'm not familiar with the `Microsoft.Windows.Sdk` namespace. CsWin32 doesn't produce that. It produces types in the `Windows.Win32` namespace. Wanna try than instead? When you have problems even with that, try `using global::Windows.Win32`.

Thanks for the quick reply! Saw your comment after hitting comment. Yes that worked.

**Comment by AArnott** [comment]
> I also get the following warning when compiling and running the program: warning CA1416: This call site is reachable on all platforms. 'PInvoke.GetActiveWin dow()' is only supported on: 'windows' 5.0 and later.

That's a .NET feature because .NET can target non-Windows. You can look up the docs on that particular warning to learn how it works and how to resolve or suppress it.
