### ISSUE TITLE
GetModuleHandle returns an owned SafeHandle

### ISSUE THREAD

**Issue by JeremyKuhne** [microsoft/CsWin32#616]
## Actual behavior

GetModuleHandle's safe overload returns an owned safe handle, which would free the HINSTANCE .

## Expected behavior

The handle shouldn't be owned as GetModuleHandle doesn't ref count. https://docs.microsoft.com/windows/win32/api/libloaderapi/nf-libloaderapi-getmodulehandlew#remarks

## Repro steps

1. `NativeMethods.txt` content:
```
GetModuleHandle
```

**Comment by AArnott** [comment]
Duplicate of https://github.com/microsoft/win32metadata/issues/921
