### ISSUE TITLE
Allow passing structs directly or with out/ref keywords instead of having to use unsafe

### ISSUE THREAD

**Issue by palenshus** [microsoft/CsWin32#619]
Currently, the PInvoke generated for `SystemParametersInfo` is:

```cs
static extern unsafe BOOL SystemParametersInfo(SYSTEM_PARAMETERS_INFO_ACTION uiAction, uint uiParam, [Optional] void* pvParam, SYSTEM_PARAMETERS_INFO_UPDATE_FLAGS fWinIni);
```

The `SystemParametersInfo` method itself is quite varied and allows for a number of different types to be passed for pvParam, some `in` some `out`, different types of structs or uint, etc.

In my specific case, I can handcraft a much simpler signature since I know I'll be getting an `out RECT`:

```cs
static extern bool SystemParametersInfo(SYSTEM_PARAMETERS_INFO_ACTION uiAction, uint uiParam, out RECT pvParam, SYSTEM_PARAMETERS_INFO_UPDATE_FLAGS fWinIni);
```

Is there any way for the library to support these types of signatures? Would it be crazy (or even possible) to automatically generate overloads for all the different possible valid signatures? Otherwise maybe there could be some way in NativeMethods.txt to indicate which specific case I want implemented?

**Comment by AArnott** [comment]
This has come up a few times. We may eventually add overloads where the set is small, and when the metadata CsWin32 is based on documents what the allowed types are. But for now we're limited to what the headers and thus metadata represent, which is generally restricted to pointers in cases where multiple data types may be pointed to.

In general, interop is fundamentally *not* "safe", and using the `unsafe` keyword often leads to simpler *safer* code than when it is avoided. A classic example is using `Marshal.AllocGlobal` and `IntPtr` and copying structs around is used to avoid `unsafe` where a simple `&mystruct` would have been sufficient had the author been willing to use the `unsafe` keyword, and it would have been perfectly "safe" to do so.

In your case, having more overloads that take your specific type would be quite "safe", but it results in potentially much more interop code being emitted than you may end up using, so swallowing the `unsafe` pill and just passing in `&yourStruct` may be the best course long term anyway.
