### ISSUE TITLE
System.ExecutionEngineException

### ISSUE THREAD

**Issue by Gavin-Williams** [microsoft/CsWin32#623]
## Actual behavior

I was running the app and watching process memory in VS diagnostic tools. Checking the value intermittently. The app had been running for a minute or two. When it crashed.

> **Output**
> An unhandled exception of type 'System.ExecutionEngineException' occurred in Core.dll
> 
> Extracted embedded document "F:\Projects\CoreWindowProjects\CoreWindow\Microsoft.Windows.CsWin32\Microsoft.Windows.CsWin32.SourceGenerator\Windows.Win32.PInvoke.User32.g.cs" to "C:\Users\deads\AppData\Local\Temp\.vsdbgsrc\C3EE4EF4AB5791F171B8ABE25BD66C50E0B23E07\Windows.Win32.PInvoke.User32.g.cs"

```
    Crash in C:\Users\deads\AppData\Local\Temp\.vsdbgsrc\C3EE4EF4AB5791F171B8ABE25BD66C50E0B23E07\Windows.Win32.PInvoke.User32.g.cs

    internal static unsafe winmdroot.Foundation.BOOL PeekMessage(out winmdroot.UI.WindowsAndMessaging.MSG lpMsg, winmdroot.Foundation.HWND hWnd, uint wMsgFilterMin, uint wMsgFilterMax, winmdroot.UI.WindowsAndMessaging.PEEK_MESSAGE_REMOVE_TYPE wRemoveMsg)
    {
    	fixed (winmdroot.UI.WindowsAndMessaging.MSG* lpMsgLocal = &lpMsg)
    	{
    		winmdroot.Foundation.BOOL __result = PInvoke.PeekMessage(lpMsgLocal, hWnd, wMsgFilterMin, wMsgFilterMax, wRemoveMsg); ** Crash on this line.
    		return __result;
    	}
    }
```
    
    

> System.ExecutionEngineException
  HResult=0x80131506
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

## Expected behavior

I expect to be able to watch the program run for several minutes and inspect process memory value

**Comment by Gavin-Williams** [comment]
I can force this event by calling GC.Collect() in my Update method. I've never used GC, so I don't know if this is expected or not.

`
    private static void Update()
    {
        if (window == null)
            return;

        Debug.WriteLine(GC.GetTotalMemory(false));
        GC.Collect();
        Debug.WriteLine(GC.GetTotalMemory(false));
    }
`

**Comment by AArnott** [comment]
So, does the crash happen in your Update method then, or do you have to call the Update method somehow in tandem with the call to PeekMessage?

**Comment by Gavin-Williams** [comment]
Just to note, if you take a look at the UWP Community Discord - I've talked about some memory issues - it's probably related.
https://discord.com/channels/372137812037730304/580484525075857428/1001839035876135014

Here's my mainloop...
```
 public void Run()
    {
        // main loop
        MSG msg = default;
        IsUpdating = IsRendering = true;
        while (IsUpdating)
        {
            // dispatch messages
            while (PeekMessage(out msg, default, 0, 0, PM_REMOVE))
            {
                _ = TranslateMessage(in msg);
                _ = DispatchMessage(in msg);
            }

            // Having dispatched messages for the frame, Keyboard
            // will now hold a record of events. Access a snapshot
            // of the keyboard stream state with...
            // Window.Keyboard.GetSnapshot()
            
            UpdateWindowMetrics();
            Update?.Invoke();
            
            // rendering
            if (!IsMinimized && IsRendering)
            {
                PrepareBackBuffer();
                Render?.Invoke(Bitmap);
                PresentBackBuffer();
            }
        }
    }
```
So my Update method is bound to an Action in Window class...
```
    public Action Update;
    public Action<Bitmap> Render;
```
I can move the call to GC.Collect out of the Update method, and just have it in my Run method and the crash still occurs.

**Comment by Gavin-Williams** [comment]
Could you please take a look at this minimal repro - it sets up a window and calls GC.Collect to crash the app.
[MemoryIssueProject.zip](https://github.com/microsoft/CsWin32/files/9206658/MemoryIssueProject.zip)

**Comment by AArnott** [comment]
Thanks for the repro. I see it as you described it. But I don't see any error in how `PeekMessage` is generated, and there aren't any managed objects involved such that I would expect a negative interaction with `GC.Collect`. Maybe the problem is elsewhere.
Given it seems to be GC related, my best guess is some *other* API call you make takes a SafeHandle or other managed object but you don't use `GC.KeepAlive` *after* the call. But a quick search doesn't produce anything in your sample, though I may have missed it. 
@AaronRobinsonMSFT do you have any ideas?

**Comment by AaronRobinsonMSFT** [comment]
@Gavin-Williams Are you running this as a 32 or 64 bit process?

**Comment by AaronRobinsonMSFT** [comment]
Yep, I just check the project. Sorry for the numbskull query.

**Comment by AaronRobinsonMSFT** [comment]
This is a collected Delegate issue. Using C# function pointers would be the recommended solution.

```csharp
WNDCLASSEXW windowClass = new()
{
    cbSize = (uint)Unsafe.SizeOf<WNDCLASSEXW>(),
    style = style,
    lpfnWndProc = ProcessWindowMessage, // An implicit delegate is being created here and is then collected.
    hInstance = (HINSTANCE)HInstance.DangerousGetHandle(),
    hCursor = LoadCursor(default, szCursorName),
    hbrBackground = default,
    hIcon = default,
    lpszClassName = lpszClassName
};
```

A second best solution is to create a `static` field to store the Delegate.

```csharp
private static WNDPROC s_WinProc;

...

s_WinProc = ProcessWindowMessage;
WNDCLASSEXW windowClass = new()
{
    cbSize = (uint)Unsafe.SizeOf<WNDCLASSEXW>(),
    style = style,
    lpfnWndProc = s_WinProc,
    hInstance = (HINSTANCE)HInstance.DangerousGetHandle(),
    hCursor = LoadCursor(default, szCursorName),
    hbrBackground = default,
    hIcon = default,
    lpszClassName = lpszClassName
};
```

**Comment by AArnott** [comment]
Thanks for your help, @AaronRobinsonMSFT.

**Comment by Gavin-Williams** [comment]
How do I setup the function pointer. I can't make anything compatible, 
```
private static LRESULT ProcessWindowMessage(HWND hWnd, uint message, WPARAM wParam, LPARAM lParam)
...
// tried each of these...
delegate* unmanaged<HWND, uint, WPARAM, LPARAM, LRESULT> winProc1 = &Window.ProcessWindowMessage;
delegate* unmanaged[Cdecl]<HWND, uint, WPARAM, LPARAM, LRESULT> winProc2 = &Window.ProcessWindowMessage;
delegate* unmanaged[Stdcall, SuppressGCTransition]<HWND, uint, WPARAM, LPARAM, LRESULT> winProc3 = &Window.ProcessWindowMessage;

WNDCLASSEXW windowClass = new()
{
    ...
    lpfnWndProc = (WNDPROC)winProc1,
```

**Comment by AaronRobinsonMSFT** [comment]
@Gavin-Williams The `WNDCLASSEXW` type would need to be updated. Right now, it is a `Delegate` field not an unsafe pointer field. It needs to be a pointer field in order for this to work. Either `IntPtr`, `delegate*unmanaged<...>`, or even `void*` will work, but it would need to be updated to accept a pointer.

**Comment by Gavin-Williams** [comment]
OK, assigning PorcessWindowMessage to a static field works. So I'll use that for now.

**Comment by AArnott** [comment]
You can get CsWin32 to generate a non-Delegate field in the struct by setting `allowMarshaling: false` in `NativeMethods.json`. But that can impact other APIs as well and make them harder to use, so the static field approach with the delegate makes the most sense most of the time.

**Comment by asklar** [comment]
I hit this for maybe the 3rd time in a year :-) 
Beyond fixing WNDCLASSEX's projection... is there a chance that a build warning be issued when assigning to anything but a static delegate field? or an analyzer that can detect this?

**Comment by AArnott** [comment]
@asklar that's an interesting idea. But we'd need to formalize it to say exactly which conditions trigger the analyzer. It isn't a problem for example so long as the method the delegate is passed to calls the delegate only during the p/invoke call. So we'd need to know which win32 functions hold onto the function pointer, and then an analyzer could potentially detect when a delegate is constructed and passed in without being assigned to something else for retention. I don't think we should require a _static_ field, because not every such pattern is a long-lived WNDPROC.

**Comment by Tape-Worm** [comment]
Just FYI, I ran into this today. 

I didn't make a static reference to the wndproc, just a local private variable, and it seems to work just fine with that. It seems to me that as long as the reference to the delegate is rooted, in this case to the lifetime of its containing object, it shouldn't be collected.

If anyone can see a flaw with this approach, I would love an explanation as I'm not 100% sure if this is OK in all cases.
