### ISSUE TITLE
Consider adding cast operators to System.Drawing types

### ISSUE THREAD

**Issue by JeremyKuhne** [microsoft/CsWin32#626]
**Is your feature request related to a problem? Please describe.**
It is tedious and error prone (particularly with RECT/Rectangle) to convert between the native types and System.Drawing types (`Point`, `Size`, `Rectangle`, and `*F` variants).

**Describe the solution you'd like**
In Windows Forms we define the RECT, POINT, etc. structs with cast operators (often implicit). We also provide useful properties on RECT for convenience, notably `.Width` and `.Height`.

**Comment by elachlan** [comment]
@AArnott should they be added via templates or directly in the generator?
