### ISSUE TITLE
Cannot use a result of 'MemoryMarshal.CreateSpan<char>(ref char, int)' in this context because it may expose variables referenced by parameter 'reference' outside of their declaration scope

### ISSUE THREAD

**Issue by virzak** [microsoft/CsWin32#637]
## Actual behavior

Compilation fails when using C# preview and msbuild.

```
  CompilerServer: server failed - server rejected the request due to analyzer / generator issues 'analyzer assembly 'C:\Users\virzak\.nuget\packages\microsoft.windows.cswin32\0.2.10-beta\analyzers\cs\System.Runtime.CompilerServices.Unsafe.dll' has MVID 'd22a1fa6-8134-4c26-bb36-e67aceee55b8' but loaded assembly 'System.Runtime.CompilerServices.Unsafe, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' has MVID 'bc84029b-1123-4266-bc37-9616e5f03999'' - 3ab8afc4-73d7-4553-b014-16f9a787539b
Q:\Code\Sandbox\SetupDiGetDeviceInterfaceDetail\Microsoft.Windows.CsWin32\Microsoft.Windows.CsWin32.SourceGenerator\Windows.Win32.SP_DEVICE_INTERFACE_DETAIL_DATA_W.g.cs(47,66): error CS8170: Struct members cannot return 'this' or other instance members by reference [Q:\Code\Sandbox\SetupDiGetDeviceInterfaceDetail\SetupDiGetDeviceInterfaceDetail.csproj]
Q:\Code\Sandbox\SetupDiGetDeviceInterfaceDetail\Microsoft.Windows.CsWin32\Microsoft.Windows.CsWin32.SourceGenerator\Windows.Win32.SP_DEVICE_INTERFACE_DETAIL_DATA_W.g.cs(47,37): error CS8347: Cannot use a result of 'MemoryMarshal.CreateSpan<char>(ref char, int)' in this context because it may expose variables referenced by parameter 'reference' outside of their declaration scope [Q:\Code\Sandbox\SetupDiGetDeviceInterfaceDetail\SetupDiGetDeviceInterfaceDetail.csproj]
Done Building Project "Q:\Code\Sandbox\SetupDiGetDeviceInterfaceDetail\SetupDiGetDeviceInterfaceDetail.csproj" (default targets) -- FAILED.
```

## Repro steps

1. `NativeMethods.txt` content:
```
SetupDiGetDeviceInterfaceDetail
```

Run the following to reproduce:

```pwsh
dotnet new classlib -o SetupDiGetDeviceInterfaceDetail --langVersion preview
dotnet add SetupDiGetDeviceInterfaceDetail package Microsoft.Windows.CsWin32 --version 0.2.10-beta
echo "SetupDiGetDeviceInterfaceDetail" > SetupDiGetDeviceInterfaceDetail/NativeMethods.txt
msbuild .\SetupDiGetDeviceInterfaceDetail\ /p:Runtimeidentifier=win-x64 /restore
```

3. Any of your own code that should be shared?

### Context

- CsWin32 version: 0.2.10-beta
- Target Framework: net6.0, net7.0
- `LangVersion` (if explicitly set by project): 11 preview

Either removing preview flag, or compiling with `dotnet` doesn't produce this issue

**Comment by AArnott** [comment]
Well, that's disappointing but also not entirely a surprise. We knew (as the code comment on the failing code indicates) that this was a risky method. I guess we'll have to find another way to make inline spans easy to use. I thought I'd heard that C# 11 was supposed to make fixed arrays better, but I can't anything about it [here](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-11).

**Comment by AArnott** [comment]
The fix for this will be to adjust the emitted code to attribute the `AsSpan()` method with `[UnscopedRef]`. [This attribute](https://apisof.net/catalog/fd88e6e8-1acb-4351-13c1-e8c4f7a98037) tells the compiler about how the ref escapes the current method, and in fact will allow us to remove the warning on the doc comment because at this point the compiler will guard the caller's code for us. When targeting < .NET 7 (or more precisely, when `UnscopedRefAttribute` isn't available), we can emit that attribute as well. The attribute should always be emitted as `internal`.

While these changes need only be made for C# 11+ compilations, as none of these are required or helpful down-level, it is conceivable that a C# 11 project that references the generated APIs may exist, so the attribute on the member may still be useful to apply.

**Comment by virzak** [comment]
Looks like this problem just went away after installing `7.0.100-rc.1.22431.12`. Version 0.2.10-beta all of a sudden works.

**Comment by AArnott** [comment]
Good. Yes, the fix I made to the source generator was "forward facing" to an SDK update that would carry a compiler change.
