### ISSUE TITLE
.net 6 64bit - Doesn't generate SetWindowLongPtrW/GetWindowLongPtrW

### ISSUE THREAD

**Issue by AsafMahlev** [microsoft/CsWin32#638]
## Actual behavior

My project was on AnyCPU, and when trying to generate SetWindowLongPtrW/GetWindowLongPtrW, it gave me a warning that I need to change to x64.
So I changed to x64, and now nothing is being generated from these methods, and I don't get any warnings.
I get warnings for other non-existing methods, and SetWindowLongW does generate fine, so I think the generator thinks it's a 32 bit project, when it's not.

## Expected behavior
Have SetWindowLongPtrW/GetWindowLongPtrW be generated.

## Repro steps

1. `NativeMethods.txt` content:
```
GetWindowLongPtrW
SetWindowLongPtrW
```

2. `NativeMethods.json` content (if present):
```json
```

3. Any of your own code that should be shared?
relevant csproj part:
```csproj
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net6.0</TargetFramework>
        <Nullable>enable</Nullable>
        <!--Avalonia doesen't support TrimMode=link currently,but we are working on that https://github.com/AvaloniaUI/Avalonia/issues/6892 -->
        <TrimMode>copyused</TrimMode>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <Configurations>Release;Debug</Configurations>
        <Platforms>x64</Platforms>
        <LangVersion>default</LangVersion>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x64' ">
      <DefineConstants>TRACE</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x64' ">
      <DefineConstants>TRACE</DefineConstants>
    </PropertyGroup>
```

### Context

- CsWin32 version: [e.g. `0.4.422-beta`] 0.2.10-beta
- Win32Metadata version (if explicitly set by project):
- Target Framework: [e.g. `netstandard2.0`] .net 6
- `LangVersion` (if explicitly set by project): [e.g. `9`]

**Comment by elachlan** [comment]
Any PInvokes which are platform specific will only be generated on that platform. So the current recommendation is to multi-target, or hand write the PInvokes which are platform specific. You can do this by copying the code and adding it to a partial class.

**Comment by AsafMahlev** [comment]
The problem is I'm not trying to be multi-target, I'm compiling only for x64 and it still isn't generated

**Comment by elachlan** [comment]
You need to use SetWindowLongPtr and CsWin32 will generate the appropriate method for you.

**Comment by AsafMahlev** [comment]
I did, it doesn't generate it, that's why I opened this.

That's when I try to generate it (notice how nothing is generated):

<img width="670" alt="image" src="https://user-images.githubusercontent.com/109351094/183026333-09ba5cae-0102-4767-9031-092270e07a1e.png">

And that's to show that other methods generate fine: 

![image](https://user-images.githubusercontent.com/109351094/183026485-0f35e861-f3f4-4dd6-a199-fc089d2f13d4.png)

**Comment by elachlan** [comment]
Use `SetWindowLongPtr` not `SetWindowLongPtrW`. Without the **W**. CsWin32 abstracts it for you.

**Comment by AsafMahlev** [comment]
Still Nothing, and other methods successfully generate with or without the W

**Comment by elachlan** [comment]
GetWindowLong/SetWindowLong

**Comment by AsafMahlev** [comment]
I don't think so - it returns an int, which is too small for a function pointer in 64 bit.

**Comment by elachlan** [comment]
Your project is probably not targeting x64.
This what what is generated when I target x64 and use `GetWindowLongPtrW`.
```
internal static extern nint GetWindowLongPtr(winmdroot.Foundation.HWND hWnd, winmdroot.UI.WindowsAndMessaging.WINDOW_LONG_PTR_INDEX nIndex);
```

**Comment by AsafMahlev** [comment]
I have posted my csproj in the first comment, am I doing something wrong?

**Comment by AsafMahlev** [comment]
This appears to be a problem with the Rider IDE, since it works fine in Visual Studio.
I have left an issue in their tracker - https://youtrack.jetbrains.com/newIssue?draftId=25-3997624
And will close this one.

**Comment by olluz** [comment]
It doesn't seem to work fine in VS2022. I'm having the same problem:
Specified SetWindowLong, GetWindowLong (I've also tried SetWindowLongPtr, GetWindowLongPtr) in NativeMethods.txt
Neither"Any CPU" nor "x64" are working. 

All of the other methods are generated, just not SetWindowLongPtr, GetWindowLongPtr

Has anyone tried this in VS2022 ?
