### ISSUE TITLE
GetModuleHandle shouldn't return FreeLibrarySafeHandle

### ISSUE THREAD

**Issue by HavenDV** [microsoft/CsWin32#644]
## Actual behavior

`GetModuleHandle` returns `FreeLibrarySafeHandle`. Which will call `FreeLibrary` on cleanup. But, according to the documentation, this is not necessary to avoid errors:
> The `GetModuleHandle` function returns a handle to a mapped module without incrementing its reference count. However, if this handle is passed to the `FreeLibrary` function, the reference count of the mapped module will be decremented. Therefore, do not pass a handle returned by `GetModuleHandle` to the `FreeLibrary` function. Doing so can cause a DLL module to be unmapped prematurely.
https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-getmodulehandlew#remarks

`GetModuleHandleEx` partly also affected by this problem, because the cleanup behavior depends on the arguments passed
https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-getmodulehandleexw#parameters

## Repro steps

1. `NativeMethods.txt` content:
```
GetModuleHandle
```

2. `NativeMethods.json` content (if present):
```json
```

3. Any of your own code that should be shared?

### Context

- CsWin32 version: [e.g. `0.1.635-beta`]
- Win32Metadata version (if explicitly set by project):
- Target Framework: [e.g. `netstandard2.0`]
- `LangVersion` (if explicitly set by project): [e.g. `9`]

**Comment by elachlan** [comment]
We need something like this, maybe in `DeclareFriendlyOverloads`?
```csharp
internal const string DoNotReleaseAttribute = "DoNotReleaseAttribute";
bool doNotRelease = false;
foreach (CustomAttributeHandle attHandle in this.GetReturnTypeCustomAttributes(methodDefinition) ?? Enumerable.Empty<CustomAttributeHandle>())
{
    CustomAttribute att = this.Reader.GetCustomAttribute(attHandle);
    if (this.IsAttribute(att, InteropDecorationNamespace, DoNotReleaseAttribute))
    {
        doNotRelease = true;
        break;
    }
}
```

**Comment by AArnott** [comment]
Wanna take this, @elachlan? We might have a helper method that does the loop-search for you.

**Comment by elachlan** [comment]
I did implement it and it worked. But not exactly how I'd hoped. Since there was still a friendly overloads, when it probably shouldn't be generated at all.

Also if we implement IDisposable on the structs(#596), then we are pushing the problem down the line. I am not sure how to fix that. Maybe wrap the return type?

**Comment by AArnott** [comment]
The friendly overload should still return a `SafeHandle`, since all the other friendly APIs we generate will take a SafeHandle as an argument. But the SafeHandle should be created, passing in `ownsHandle: false` to the constructor.

**Comment by elachlan** [comment]
ahhhh, thanks. I should be able to get it sorted in the next few days in my free time.
