### ISSUE TITLE
Fix formatting issues around for loops

### ISSUE THREAD

**Issue by elachlan** [microsoft/CsWin32#648]
## Actual behavior

Code generated with for loops seem to be indented and formatted incorrectly.

## Expected behavior

Code should be generated with correctly formatted for loops.

## Repro steps

1. `NativeMethods.txt` content:
```
PAINTSTRUCT
```

2. `NativeMethods.json` content (if present):
```json
```

3. Any of your own code that should be shared?

Issue is in `WhitespaceRewriter`.

![image](https://user-images.githubusercontent.com/2433737/183801157-53090d2e-28c1-41f5-af9d-12b47f3ca642.png)

### Context

- CsWin32 version: [e.g. `0.4.422-beta`]
- Win32Metadata version (if explicitly set by project):
- Target Framework: [e.g. `netstandard2.0`]
- `LangVersion` (if explicitly set by project): [e.g. `9`]

**Comment by elachlan** [comment]
In the example screenshot, is there supposed to be braces, or is this a single line?

**Comment by AArnott** [comment]
No braces are generated in the syntax tree because it was only one statement. But if it makes it easier to fix, I have no objection with you adding braces around the statement in the syntax tree.
