### ISSUE TITLE
FwpmFilterAdd0: optional parameter cannot be null

### ISSUE THREAD

**Issue by Hill-98** [microsoft/CsWin32#652]
## Actual behavior

The last two optional parameters of FwpmFilterAdd0 cannot be null

## Expected behavior

The last two optional parameters of FwpmFilterAdd0 can be null

## Repro steps

1. `NativeMethods.txt` content:
```
FwpmFilterAdd0
OpenProcess
QueryFullProcessImageName
```

### Context

- CsWin32 version: 0.2.10-beta
- Target Framework: .NET 6

**Comment by AArnott** [comment]
Thanks for using CsWin32 and reporting on your experience, @Hill-98. 
These are the method signatures I see that are generated for the API you're reporting on:

```cs
internal static extern unsafe uint FwpmFilterAdd0(winmdroot.Foundation.HANDLE engineHandle, winmdroot.NetworkManagement.WindowsFilteringPlatform.FWPM_FILTER0* filter, winmdroot.Security.PSECURITY_DESCRIPTOR sd, [Optional] ulong* id);
internal static unsafe uint FwpmFilterAdd0(SafeHandle engineHandle, in winmdroot.NetworkManagement.WindowsFilteringPlatform.FWPM_FILTER0 filter, winmdroot.Security.PSECURITY_DESCRIPTOR sd, ulong* id)
```

The fourth parameter is a `ulong*`, and a `null` argument is the way to leverage the parameter being 'optional'.

The third parameter is a `PSECURITY_DESCRIPTOR`, which [has an interesting history](https://github.com/microsoft/win32metadata/issues/835) in the win32metadata. It is not actually a `SECURITY_DESCRIPTOR*` in native code, but rather a `void*`. Apparently the balance between usability and type safety led the metadata team to decide to declare this special typedef as a struct. In C# this makes it impossible to pass in `null` as a 3rd argument. But you can pass in `default`. The struct carries a single `void* Value` field, which defaults to `null`.

So in fact the last two optional in that they can both receive default/null values and the native function will receive null pointers.

**Comment by Hill-98** [comment]
@AArnott Thanks for your answer, let me know more about Win32API.
