### ISSUE TITLE
No PInvoke for memcmp

### ISSUE THREAD

**Issue by palenshus** [microsoft/CsWin32#658]
## Actual behavior

`warning PInvoke001: Method, type or constant "memcmp" not found. Did you mean "u_memcmp" or "u_memcmpCodePointOrder"?`

Is it expected that cswin32 can't generate a pinvoke for memcmp? Here's my workaround:

```cs
[DllImport("msvcrt.dll")]
private static extern int memcmp(IntPtr b1, IntPtr b2, long count);
```

## Repro steps

1. `NativeMethods.txt` content:
```
memcmp
```
### Context

- CsWin32 version: 0.2.10-beta

**Comment by AArnott** [comment]
CsWin32 generated interop APIs for Win32. Not the VC runtime.
Your workaround is fine. But you could do it without p/invoke too:

```cs
    public unsafe void memcpy(IntPtr src, IntPtr dest, int size) {
        new Span<byte>(src.ToPointer(), size).CopyTo(new Span<byte>(dest.ToPointer(), size);
    }
```

**Comment by palenshus** [comment]
Ah, my mistake, thanks @AArnott! Regarding the workaround though, I'm calling mem**cmp** not memcpy :)
