### ISSUE TITLE
This generator is not generating files

### ISSUE THREAD

**Issue by hxhgxy** [microsoft/CsWin32#659]
## Actual behavior

I tried to install different version of Microsoft.Windows.CsWin32 in different projects, for example Net4.62, 4.8, Net core 5.0, 6.0 etc, I got the same problem:

This generator is not generating files.

What can i do to fix the problem?

Thanks
Tiger

## Repro steps

1. `NativeMethods.txt` content:
```

```

2. `NativeMethods.json` content (if present):
```json
```

3. Any of your own code that should be shared?

### Context

- CsWin32 version: [e.g. `0.4.422-beta`]
- Win32Metadata version (if explicitly set by project):
- Target Framework: [e.g. `netstandard2.0`]
- `LangVersion` (if explicitly set by project): [e.g. `9`]

**Comment by AArnott** [comment]
Well, according to your repro steps, you have an empty `NativeMethods.txt` file. What generated code were you expecting if you didn't request any code to be generated?

**Comment by hxhgxy** [comment]
> Well, according to your repro steps, you have an empty `NativeMethods.txt` file. What generated code were you expecting if you didn't request any code to be generated?

thank you very much!

**Comment by antleite2001** [comment]
So the message should be: Include functions in your NativeMethods.txt
