### ISSUE TITLE
Add `DateTime` operators to `SYSTEMTIME`

### ISSUE THREAD

**Issue by elachlan** [microsoft/CsWin32#667]
Issue came up in a PR(https://github.com/dotnet/winforms/pull/7662) as apart of the winforms conversion effort.

https://github.com/dotnet/winforms/blob/74e08305a520abc8cf176350072784c6d8d98ddc/src/System.Windows.Forms.Primitives/src/Windows/Win32/Foundation/SYSTEMTIME.cs

https://github.com/dotnet/winforms/issues/7468

**Comment by AArnott** [comment]
Thanks for suggesting this. I'm not sure an *implicit* conversion operator is appropriate for this, but if the conversion is lossless and fast/alloc free, it's probably fine. In your sample conversion operators, one of them drops the millisecond field. We wouldn't want to do that in our conversion operators. If WinForms wanted to drop to second resolution, that should be done in their own code. Perhaps with a partial struct on their side that defines a method like `SYSTEMTIME ToSecondResolution()` or something like that.

A template file for this type is probably the best way to add these conversion operators.

**Comment by elachlan** [comment]
@fernandanavamoya can you let us know why you are stripping the millisecond field?
