### ISSUE TITLE
Use `System.IO.SeekOrigin` instead of `System.Com.STREAM_SEEK`

### ISSUE THREAD

**Issue by elachlan** [microsoft/CsWin32#675]
The values match between them.

We need something like `BclInteropStructs` in the Generator for BCL enums. Allowing us to replace a generated enum with an enum from the BCL.

**Comment by AArnott** [comment]
Sounds good. Thanks for confirming that the values are the same. Are you calling out that the BclInteropStructs support we already have for substituting metadata types with BCL types doesn't yet work for enums? If so, that's something I'd support improving.

But in this case, I wonder... what is the benefit of sharing an enum here? The *cost* is that the enum type used won't match win32 documentation. With *structs* this cost is often outweighed by the improved interoperability with other BCL-based code. But for a STREAM_SEEK enum, is there material benefit? Will there ever be code that is given one type and must use the other type?

I'm not against consolidating these two types, ... but if there's no know benefit, I'm on the fence.

**Comment by elachlan** [comment]
Winforms uses the BCL enum on its `IStream` interface and that is what inspired this issue.

IF we replace it, it will be used everywhere and so that concern won't matter for code we generate. Even if a user passes the enum to external win32 code it shouldn't be a problem because the underlying type of the enum is the same.

I can see how the docs could be an issue. 

There would be marginally less generated code and its not hard to cast between the enums. So the benefit isn't massive.

**Comment by elachlan** [comment]
Do we have a policy on using BCL structs/enums? I know we use a few BCL structs where it directly mirrors win32api (blittable).

**Comment by AArnott** [comment]
This is what I'd suggest as a policy:
For structs, we want to reuse them where they are compatible. Enums *may* be shared when all members are equivalent as well, particularly when:
* the enum values are not likely to change over time, since if they did, the BCL would be 'behind' whatever was offered by Windows.
* the enum is likely to propagate across methods or APIs, such that it would be useful to pass the managed BCL type into an interop method.
