### ISSUE TITLE
Missing SecurityCritical attributes

### ISSUE THREAD

**Issue by HavenDV** [microsoft/CsWin32#689]
## Actual behavior

I'm not sure about this (because .Net Core doesn't use this attribute), but it might apply where .Net Framework/.Net Standard/UWP is still relevant.
For example, here is the class decompiled from .Net Framework to use CreateNamedPipe with SECURITY_ATTRIBUTES in .Net Standard:
https://github.com/HavenDV/NamedPipeServerStream.NetFrameworkVersion/blob/58d49a12b8356c8a3065a9d6e314de8272e0ff06/src/libs/NamedPipeServerStream.NetFrameworkVersion/SECURITY_ATTRIBUTES.cs#L1-L15
CsWin32 generates the following code:
```cs
[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.46-beta+0e9cbfc7b9")]
internal partial struct SECURITY_ATTRIBUTES
{
	/// <summary>The size, in bytes, of this structure. Set this value to the size of the **SECURITY\_ATTRIBUTES** structure.</summary>
	internal uint nLength;
	/// <summary>
	/// <para>A pointer to a [**SECURITY\_DESCRIPTOR**](../winnt/ns-winnt-security_descriptor.md) structure that controls access to the object. If the value of this member is **NULL**, the object is assigned the default security descriptor associated with the [*access token*](/windows/win32/secauthz/access-tokens) of the calling process. This is not the same as granting access to everyone by assigning a **NULL** [*discretionary access control list*](/windows/win32/secauthz/dacls-and-aces) (DACL). By default, the default DACL in the access token of a process allows access only to the user represented by the access token. For information about creating a security descriptor, see [Creating a Security Descriptor](/windows/win32/secauthz/creating-a-security-descriptor-for-a-new-object-in-c--).</para>
	/// <para><see href="https://docs.microsoft.com/windows/win32/api//wtypesbase/ns-wtypesbase-security_attributes#members">Read more on docs.microsoft.com</see>.</para>
	/// </summary>
	internal unsafe void* lpSecurityDescriptor;
	/// <summary>A Boolean value that specifies whether the returned handle is inherited when a new process is created. If this member is **TRUE**, the new process inherits the handle.</summary>
	internal winmdroot.Foundation.BOOL bInheritHandle;
}
```

## Repro steps

1. `NativeMethods.txt` content:
```

```

2. `NativeMethods.json` content (if present):
```json
```

3. Any of your own code that should be shared?

### Context

- CsWin32 version: [e.g. `0.4.422-beta`] `0.2.46-beta`
- Win32Metadata version (if explicitly set by project):
- Target Framework: [e.g. `netstandard2.0`] `netstandard2.0`
- `LangVersion` (if explicitly set by project): [e.g. `9`] `preview`

**Comment by HavenDV** [comment]
Small issues:
- KERNEL32.dll FormatMessage generates
```cs
internal static extern unsafe uint FormatMessage(winmdroot.System.Diagnostics.Debug.FORMAT_MESSAGE_OPTIONS dwFlags, [Optional] void* lpSource, uint dwMessageId, uint dwLanguageId, winmdroot.Foundation.PWSTR lpBuffer, uint nSize, [Optional] sbyte** Arguments);
```
where Arguments starts with a capital letter

- PInvoke.CreateNamedPipe can return `SafePipeHandle` instead `SafeFileHandle`. This is in the same namespace and library

**Comment by AArnott** [comment]
Thanks for suggesting this, @havendv. The `SecurityCritical` attributes are the successor to Code Access Security, and are meant to enable partial trust scenarios. That isn't something we're investing in any more, and the metadata we're generating doesn't include the information we'd need to place those attributes anyway. Anyone writing interop code must be running with full trust anyway, so these attributes would be ignored. That may not be *strictly* true in the code you decompiled because the BCL exposes these types to apps that may be running under partial trust. But CsWin32-generated code is not meant for general consumption via higher-level APIs either.

Regarding your second issue on the parameter name, I'd generally say please file distinct issues separately. But we'll close on that by just saying all identifier names used in CsWin32 generated APIs come from the metadata, which come from the headers. They are not hand-edited to conform to .NET naming guidelines, so what you see is by design.

**Comment by AArnott** [comment]
I see you blocked another PR on this. If this is a real blocking issue, I guess I'd like to learn more. I think a p/invoke method itself is considered by the CLR to be security critical by default anyway. So I think this is only a concern on your struct fields, correct? Manipulating a struct field itself isn't a security critical operation unless that struct is then used or passed to someone who will read that data. Does your project ever expose the generated struct to partially trusted code and then pass it back to kernel32? (I would hope not, regardless).

**Comment by HavenDV** [comment]
Thanks for the answer. I'm not sure about my PR because the library uses .Net Standard 2.0 for Interop code. Basically, this is now used to add a NamedPipeServerStream constructor with SECURITY_ATTRIBUTES where .Net Framework/.Net 6 is not available.
But given your answer, I don't think there will be any problems with that.
