### ISSUE TITLE
LARGE_INTEGER/ULARGE_INTEGER should map to Int64/UInt64

### ISSUE THREAD

**Issue by saul** [microsoft/CsWin32#69]
These structs date back to a time where C compilers didn't natively support 64-bit integers. I think these should be represented as System.Int64 and System.UInt64 in the metadata.

I tried having a go at this myself by adding:

```
LARGE_INTEGER=Int64
_LARGE_INTEGER=Int64
ULARGE_INTEGER=UInt64
_ULARGE_INTEGER=UInt64
```

To `generation/baseRemap.rsp`, but to my surprise it just resulted in Microsoft.Windows.Sdk.Int64 and Microsoft.Windows.Sdk.UInt64 types being generated.

Do you think this is a reasonable change?

**Comment by kennykerr** [comment]
@saul - I've just transferred it here for you.
