### ISSUE TITLE
C# 11: consider adding `scoped` modifier to `ref` or `in` parameters of generated methods

### ISSUE THREAD

**Issue by alexrp** [microsoft/CsWin32#697]
I have a WIP project using .NET 7 and C# 11 that I just upgraded to .NET 7 RC 1. Upon doing so, I got these errors:

```
error CS8168: Cannot return local 'startupInfo' by reference because it is not a ref local
error CS8350: This combination of arguments to 'WindowsPInvoke.CreateProcessW(string, ref Span<char>, SECURITY_ATTRIBUTES?, SECURITY_ATTRIBUTES?, BOOL, PROCESS_CREATION_FLAGS, void*, string, in STARTUPINFOW, out PROCESS_INFORMATION)' is disallowed because it may expose variables referenced by parameter 'lpStartupInfo' outside of their declaration scope
```

The code in question:

![image](https://user-images.githubusercontent.com/44076/192078000-1d9dcf6d-dd59-4359-a1af-d3f2f7a7f694.png)
![image](https://user-images.githubusercontent.com/44076/192078006-77b9d200-0cd8-44f2-9858-40d30a9ad896.png)

After talking to Tanner and Jared on Discord, it turns out that this is actually an intentional breaking change in C# 11. For the full details, see this discussion on the DotNetEvolution Discord server: https://discord.com/channels/732297728826277939/732297994699014164/1022962100546576545

A minimal repro (not using CsWin32) looks something like this:

```csharp
class Program
{
    public struct STARTUPINFOW
    {
    }

    public static void CreateProcessW(ref Span<char> commandLine, in STARTUPINFOW startupInfo)
    {
    }

    static void Main()
    {
        var startupInfo = new STARTUPINFOW();
        var args = Span<char>.Empty;

        CreateProcessW(ref args, in startupInfo);
    }
}
```

The breaking change is described here: https://github.com/dotnet/roslyn/blob/main/docs/compilers/CSharp/Compiler%20Breaking%20Changes%20-%20DotNet%207.md#instance-method-on-ref-struct-may-capture-unscoped-ref-parameters (the break is more general and applies anywhere where there're multiple `ref`s)

The solution in this case is to annotate the `lpStartupInfo` parameter as `scoped in`. I'm not entirely sure what the general fix is going to look like for CsWin32 though. (For now I've worked around this by calling the 'unfriendly' overload of `CreateProcessW`.)

**Comment by AArnott** [comment]
Interesting. This sounds at least related to #637.

**Comment by AArnott** [comment]
The doc you linked to is specifically around `ref struct`, which doesn't apply in your repro case. I think the `ref struct` case makes sense because a `ref struct` may be able to retain an `in` or `ref` reference in a field. But a static method as given in your repro cannot do this, AFAIK. I wonder if this is a compiler bug. I'll reach out to that team.

**Comment by alexrp** [comment]
FWIW, @jaredpar provided me with that link. From the Discord discussion:

```
[11:16 PM] alexrp: so the breaking change is broader than just instance methods on ref structs (as described in that link)?
[11:35 PM] jaredpar: It's subject to any method where you have multiple refs. The most common we found in practice was the instance method case which is why it's featured.
```

**Comment by AArnott** [comment]
Thanks. So it sounds like we could just get in the habit of adding `scoped` to every `in` or `ref` parameter we generate since we never store any of them anywhere else. Although strictly speaking we can get away with adding it only to methods with multiple such parameters. That's something we cando.

**Comment by jaredpar** [comment]
This is going to change in .NET 7 RTM. There was a lot of feedback about this breaking change so we found a way to limit the scope of it. The breaking change only hits if you have a ref-like type in a return or `out` parameter. Those are the only places that can capture `ref` inputs as fields.

**Comment by AArnott** [comment]
Sounds good. We'll deprioritize the issue here then and potentially add `scoped` in the future.

**Comment by AArnott** [comment]
Given the stack of impactful bugs and feature requests, and addressing this future-looking request would add additional branching to test in the source generator, and we haven't identified any user impact whether or not we deliver on this, I'm closing as won't fix. If user impact is ever identified, we can reconsider.
