### ISSUE TITLE
Stable release

### ISSUE THREAD

**Issue by CyberSinh** [microsoft/CsWin32#698]
This project is in development/preview state for 2 years.
When do you plan to release a stable version?
Thanks!

**Comment by AArnott** [comment]
Probably when we have fixed all the known bugs (both in the metadata and this source generator) that lead to generating unusable APIs. A good % of them are correct at this point, but we still have active bugs for defective APIs generated.

How does the fact that this is marked as an unstable package impact you? Does it limit your consumption in any way that we should be aware of?

**Comment by CyberSinh** [comment]
The release of a package in preview often indicates that the package is not ready for production use. The lack of a stable version can therefore discourage developers from using this package.

As far as I am concerned, this project brings me enough value to take the risk of using it as it is.

**Comment by elachlan** [comment]
Normally I would agree. But since this is a source generator its not as bad. Its only an issue if you stumble on a broken API, which you can then jump in and submit a PR for if its time sensitive.

**Comment by jnm2** [comment]
I haven't thought of source generators as being different from libraries in this way. In both cases, I see it as adding executable code of some quality that is communicated in the same way either way.

**Comment by CyberSinh** [comment]
CsWin32 has now stable release:
https://github.com/microsoft/CsWin32/releases/tag/v0.3.106

Thanks @AArnott  !
