### ISSUE TITLE
Add IID guids that don't use strings for construction.

### ISSUE THREAD

**Issue by JeremyKuhne** [microsoft/CsWin32#711]
Having a Guid that doesn't need reflection to obtain is more performant and facilitates AOT compiliation. The pattern used in [TerraFX.Interop.Windows](https://source.terrafx.dev/#TerraFX.Interop.Windows/Windows/um/Unknwnbase/IUnknown.cs,1b0a5ca761c053b6) seems ideal:

``` C#
[Guid("00000000-0000-0000-C000-000000000046")]
public unsafe partial struct IUnknown : IUnknown.Interface, INativeGuid
{
    static Guid* INativeGuid.NativeGuid => (Guid*)Unsafe.AsPointer(ref Unsafe.AsRef(in IID_IUnknown));

    public void** lpVtbl;

    // ...
}

public static partial class IID
{
    public static ref readonly Guid IID_IUnknown
    {
        get
        {
            ReadOnlySpan<byte> data = new byte[] {
                0x00, 0x00, 0x00, 0x00,
                0x00, 0x00,
                0x00, 0x00,
                0xC0,
                0x00,
                0x00,
                0x00,
                0x00,
                0x00,
                0x00,
                0x46
            };

            Debug.Assert(data.Length == Unsafe.SizeOf<Guid>());
            return ref Unsafe.As<byte, Guid>(ref MemoryMarshal.GetReference(data);
        }
    }
}

public unsafe interface INativeGuid
{
    protected internal static abstract Guid* NativeGuid { get; }
}
```

This allows writing a reasonable implementation of `ComPtr` in C# (which should also be provided by CsWin32 when generating COM structs).  It allows implementing `As` methods that allow keeping management contained within `ComPtr`. See the implementation in [TerraFx](https://github.com/terrafx/terrafx.interop.windows/blob/main/sources/Interop/Windows/ComPtr%601.cs).

This `ComPtr` implementation also shows the value of having the COM structs implement a nested interface. You can better constrain helpers like these to the COM structs.

``` C#
public unsafe struct ComPtr<T> : IDisposable
    where T : unmanaged, IUnknown.Interface
```

The minbar is having the IID's for COM interfaces defined so we can avoid manually transcribing them for trimming/AOT purposes.

**Comment by AArnott** [comment]
I can't imagine how all the trouble with per-byte representation and pointers provides a meaningful perf benefit over just a static field initializer. Do you object to my adding this as a member to the struct to close this issue?

```cs
internal static readonly Guid Guid = new Guid(0x00000101, 0x0000, 0x0000, 0xC0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x46);
```

**Comment by AArnott** [comment]
I did test the perf of retrieving a `static readonly Guid` field with retrieving `typeof(something).GUID`, and indeed the former was over 1000X faster than the latter.
