### ISSUE TITLE
Add `decimal` conversion for `DECIMAL`

### ISSUE THREAD

**Issue by JeremyKuhne** [microsoft/CsWin32#719]
Something like this at least and/or conversion operators would be very useful.

``` C#
public decimal ToDecimal()
{
    return new decimal(
        (int)Anonymous2.Anonymous.Lo32,
        (int)Anonymous2.Anonymous.Mid32,
        (int)Hi32,
        Anonymous1.Anonymous.sign == 0x80,
        Anonymous1.Anonymous.scale);
}
```

**Comment by AArnott** [comment]
I agree. I'm guessing the snippet you whipped up is too simple to be generally accurate. Is that right? You're only using one field in union structs, which seems likely to be leaving out certain ranges.

**Comment by AArnott** [comment]
Never mind. I guess those unions aren't to support different modes, but rather just to provide different cuts into the same data.
