### ISSUE TITLE
Can't generate VirtualQuery*

### ISSUE THREAD

**Issue by wwh1004** [microsoft/CsWin32#722]
## Actual behavior

Can't generate VirtualQuery*

## Expected behavior

Generate VirtualQuery*

## Repro steps

1. `NativeMethods.txt` content:
```
VirtualQuery
VirtualQueryEx
```
or
```
kernel32.*
```

3. Any of your own code that should be shared?

### Context

- CsWin32 version: 0.2.63-beta
- Target Framework: net6.0
- `LangVersion` (if explicitly set by project): 10.0

### Additions

I found there are two MEMORY_BASIC_INFORMATION in winmd. Maybe it causes cswin32 can't work.
``` cs
[SupportedArchitecture(Architecture.X86)]
public struct MEMORY_BASIC_INFORMATION {}

[SupportedArchitecture(Architecture.X64 | Architecture.Arm64)]
public struct MEMORY_BASIC_INFORMATION {}
```

**Comment by AArnott** [comment]
Try building the project and inspect the build output for a build warning that explains why that API was not generated. You are correct in your suspicion: the fact that this API has architecture-specific type references means CsWin32 can only generate this API when your C# compilation is also architecture-specific. 

As this question comes up regularly, I wrote [a doc](https://github.com/microsoft/CsWin32/blob/main/doc/ArchSpecificAPIs.md) today to help explain it all. I hope that helps.
