### ISSUE TITLE
"UnscopedRefAttribute is inaccessible" with net6.0/C#10

### ISSUE THREAD

**Issue by AArnott** [microsoft/CsWin32#742]
I get a build failure with generating code for the RAWHID struct with dotnet 6/C#10. I assume related to these changes:
error CS0122: 'UnscopedRefAttribute' is inaccessible due to its protection level

_Originally posted by @jeremy-visionaid in https://github.com/microsoft/CsWin32/issues/687#issuecomment-1296460149_

**Comment by AArnott** [comment]
I'm guessing that this is because your project references another project that already declares this attribute, as internal. When we suppress our own generation of the attribute it appears we only check that the attribute is declared somewhere -- not whether it's accessible.

**Comment by AArnott** [comment]
Thank you for your report @jeremy-visionaid

**Comment by jeremy-visionaid** [comment]
Thanks for getting that fixed so quickly, that's awesome!
