### ISSUE TITLE
Provide a static interface for the Guid on COM structs

### ISSUE THREAD

**Issue by JeremyKuhne** [microsoft/CsWin32#752]
We don't want to use reflection to get `Guid` information and also want to constrain generic helpers so in WinForms we implement `INativeGuid` on every generated COM struct:

``` C#
internal interface INativeGuid
{
    public static abstract unsafe Guid* NativeGuid { get; }
}

internal unsafe partial struct IStream : IPopulateVTable<IStream.Vtbl>, INativeGuid
{
    static Guid* INativeGuid.NativeGuid => (Guid*)Unsafe.AsPointer(ref Unsafe.AsRef(in Guid));
}
```

Here is an example of how we use it: https://github.com/microsoft/CsWin32/issues/751#issuecomment-1304268295

Here is another:

``` C#
picture.Value->QueryInterface(IPersistStream.NativeGuid, persist);
```

**Comment by JeremyKuhne** [comment]
cc: @lonitra

**Comment by AArnott** [comment]
Here is what I plan to add. It's not quite the same as what you were doing. Please advise if it deviates in an unacceptable way.

```cs
internal interface IComIID
{
    internal static abstract ref readonly Guid Guid { get; }
}
```

**Comment by JeremyKuhne** [comment]
>  Please advise if it deviates in an unacceptable way.

We're passing `Guid*` directly to native APIs in most cases. As long as we can write some sort of adapter to avoid making a copy that's fine.

Had a chat with @tannergooding to vet design.

To be as safe as possible we need the `Guid` definition to be unmoveable. The best way to do this is to take advantage of the `ReadOnly<T> = new T[]` optimization which directly references the assembly metadata. If the `Guid`s are defined as such:

``` C#
public static struct IUnknown : IComIID
{
    public static ref readonly Guid Guid
    {
        // Aggressive inlining needed to get this to inline as a single address move
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get
        {
            // Little Endian- all Windows platforms
            ReadOnlySpan<byte> data = new byte[] {
                0x00, 0x00, 0x00, 0x00,
                0x00, 0x00,
                0x00, 0x00,
                0xC0,
                0x00,
                0x00,
                0x00,
                0x00,
                0x00,
                0x00,
                0x46
            };

            return ref Unsafe.As<byte, Guid>(ref MemoryMarshal.GetReference(data));
        }
    }  
}
```

This ends up getting you this for asm:

```
IUnknown.get_Guid()
    L0000: mov rax, 0x20ca0fa0d80
    L000a: ret
```

And we can then write something like this:

``` C#
public unsafe static class IID
{
    public static Guid* Get<T>() where T : unmanaged, IComIID
    {
        return (Guid*)Unsafe.AsPointer(ref Unsafe.AsRef(in T.Guid));
    }
}
```

See [Sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgCUBXAOwwEt8YLAMIR8AB14AbGFADKMgG68wMXAG4a9Jq049+ggJI8ZEMfKhKV6zY1kALbFDEAZbMHbc+AjdU0BmBm5cbAAzGCZSBiEaAG8aBgSGAG0AKV4MAHEYLhllAAoMAE8xGAgQvIMAVS4Aay4IAHcuAEpmgF14xOIA3h4GAFkAHgAVAD484YAqBl7cDGwuFWaGBrsZcOGGEECufAXsAHMYABM0BgMRfAMDABFOhLjqROemAHYGYdUMFllRGABBAAKBgqtxYWQwI3GrQYAGoZlw5gsVDNcAwuBxJJIGAB+BiMbbkHzPAC+NDJvloASCoXCzCQEXOt1i92SaUy2VyYAKxVK5SqtXqTVaHSeiSS/RgGDsEGOBnEkjykulsvlYkkAHkxHwIIiWP8DgdYLhcLwFDAjJJer0DgxCAMpTK5QqtTq9QajapTebXfxeAAvbBu9qs7raBkZDi8Y7TCFQvLLVbrD5bHZ7LiHE5nC6ia53MUPVnPYjvPKR6OTZrVYJhfW4QEQXoYGR5WAhBjV2l1tgwcq9D7gqPHVrExIUin+HY1unkBlkD5fFkF5LKp1qxWr1Uu7W8XW4FgAOQglutXAOIeXYfpCIwDF+AiBIPLMZm0eWAF5Rq/jnBRgBRABHDhsEkXA8mOXtsExDBljxchUzoHwJypKdaQYOYoA4MBbwFOpGi4VMcyuZlqEeLoAmvNsGFgbBjl1SRCgYZ8mKHe4yJeBIJUdLd1SVbjnXVX0931Q1jW9C0uCtLgbQvDiEiODAi0Sdi5MSAB6NSGGcdIMGkBg/y4Y5eAWJSOJ7WiNUkwpZDEBZBmAQpmy/Y4g2wBh33RGAGgYBzmySNoGBU1SXjoBA6DoM5QvCyKwoi/FYrQUzgqiuKUsS5dgsSNL4uipLVNCoQIryuS0uKjjSoyzKcqKyrMoqqqQoSsrGty2rkoQFAkGakkfGaktqN7DtES7f5cHsxyYDOZ9xioyV8GgQp+kcXAHEkcEpR7MJYEWGBwNckckopMdyRoScmxkEJsBRIi8yXYsKNnBg3Awq7byomi6Ksljo2+45WSC54FNHBJxyAA===) for an example.

Note, that we would like the `Guid` property to be public rather than explicit implementation.

**Comment by AArnott** [comment]
> Note, that we would like the Guid property to be public rather than explicit implementation.

We do offer a public `IID_Guid` property already. The explicit implementation property is on IComIID. So with my current design, it makes it convenient in either case (generic interface parameter or specific interface type). Is there a problem with the explicit interface implementation that I've missed?

> To be as safe as possible we need the Guid definition to be unmoveable. 

Is a static field movable? I didn't expect that.

**Comment by tannergooding** [comment]
> Is a static field movable? I didn't expect that.

Static fields do not have any guarantee of being immovable. As an implementation detail the JIT may decide to allocate the space for them on the FOH (Frozen Object Heap) or POH (Pinned Object Heap), but it is not required to do so. -- There are runtimes/GCs that may not do this optimization and scenarios like collectible assemblies where RyuJIT might not either. C# currently emits an RVA static (backing data is embedded in the `.rodata` section of the PE or ELF file) for the `ROSpan<byte> x = new byte[] { all constant data };` pattern. This, being directly embedded into the native image, is immovable.
