### ISSUE TITLE
Should CERs be used when marshaling SafeHandles?

### ISSUE THREAD

**Issue by AArnott** [microsoft/CsWin32#763]
### Discussed in https://github.com/microsoft/CsWin32/discussions/753

<div type='discussions-op-text'>

<sup>Originally posted by **User1785604260** November  7, 2022</sup>
On a more advanced note, the [documentation for DangerousAddRef](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.safehandle.dangerousaddref?view=net-6.0#remarks) also indicates that a Constrained Execution Region should be used. I've never touched those and don't know what proper usage of that would look like, and if it's relevant to CsWin32.</div>

Thank you @User1785604260 for bringing this up.

**Comment by AaronRobinsonMSFT** [comment]
**TL;DR** The code snippet above is correct and follows the .NET team's recommended pattern.

I will update the doc as it needs some details.

1) The `DangerousAddRef()` will throw if it can't add ref - there is no need to check for failure. However, it is important for the "addref" `bool` to be initialized to `false`.
1) CER is impossible to get right in practice and was removed in .NET Core/.NET 5+ because it adds very little value.

**Comment by User1785604260** [comment]
Are you referring to updating the docs on DangerousAddRef? As the original user who filed this issue, I did find those a bit confusing to read, which is how I ended up filing these (incorrect) bugs.

From reading the docs, I had no idea DangerousAddRef would throw when the handle was closed, although trying it out now I do see the ObjectDisposedException getting thrown.

Also from reading the docs, I was left confused about what exactly I should be doing when the success value is false after making the call. Is this a condition that's simply impossible to have happen...? If not, when would success be false and what should you do when that happens?

**Comment by AArnott** [comment]
> what exactly I should be doing when the success value is false after making the call. Is this a condition that's simply impossible to have happen...? If not, when would success be false and what should you do when that happens?

@User1785604260, it sounds like you will _always_ get `true` set on that `ref` parameter unless the method throws. But as you can see from our method above, it's useful to have the `ref` parameter just in case it was set to true *and* an exception was thrown (from anywhere) because that tells us that a release is required.

Closing since no CER is required.

**Comment by User1785604260** [comment]
Ahhhh, ok, I get the intended use given that success will always get set to true. That definitely wasn't clear to me from reading the docs. 🙂
