### ISSUE TITLE
Visual Studio Quick Actions doesn't offer to import PInvoke namespaces

### ISSUE THREAD

**Issue by riverar** [microsoft/CsWin32#773]
## Actual behavior

_It's not clear if this is a CsWin32 issue or more general .NET / Visual Studio issue._ 

When attempting to use code generated types, Visual Studio typically provides a Quick Action to import the appropriate namespace to avoid fully qualifying the type. For example, using Quick Actions on a naked `HWND` should recommend importing `Windows.Win32.Foundation` and offer use of the fully qualified type name.

![image](https://user-images.githubusercontent.com/475132/201730426-73b11ba5-2ffe-43c2-968b-f204de8b7f35.png)
Built-in types work great.

![image](https://user-images.githubusercontent.com/475132/201730173-1cdd2133-f920-4c94-b1fe-2819f8346400.png)
Code-generated types do not.

## Expected behavior

I expect to see a `using Windows.Win32.Foundation;` Quick Action.

## Repro steps

1. Create a new net6 C# project and add CsWin32 `0.2.104-beta` as a dependency.
2. Add the following content to `NativeMethods.txt`:
   ```
   HWND
   ```
3. In any class method or function, type `HWND` and click the light bulb (or type `CTRL + .`).
4. Observe the Quick Actions menu does not offer to import the namespace in which HWND lives in.

**Comment by AArnott** [comment]
This is a roslyn limitation. https://github.com/dotnet/roslyn/issues/52184 is related (though more complex than the simple repro we see for CsWin32).

The feedback ticket I filed on this issue specifically is [here](https://developercommunity.visualstudio.com/t/C-Add-using-refactoring-not-offered-f/1428570?q=add+using+source+generator). It's already been closed as won't fix, but feel free to vote it up and maybe they'll reconsider.

**Comment by riverar** [comment]
@AArnott Thanks, will make some noise!
