### ISSUE TITLE
Add “partial” modifier to generated members

### ISSUE THREAD

**Issue by TIPConsulting** [microsoft/CsWin32#78]
I was trying to update a non-trivial project (x_input gamepad library) to use this generator. The methods were generating properly, but I found that many of my existing data structs had custom members. It would be nice to have a way to extend the capabilities of auto-generated structs. I think adding the partial modifier could be an easy fix, but I'm not sure if that would cause any issues for marshaled objects

**Comment by dotMorten** [comment]
I've been using a different code generator for a few years (not based on analyzers), but we did exactly this and it's been very helpful to add a bit of extra functionality without having to change what is used to drive the generated code. So I could definitely see this being useful.

**Comment by AArnott** [comment]
Note #133, as your scenario is still blocked as tracked by that issue.
