### ISSUE TITLE
Provide a way for user code to implement COM interfaces

### ISSUE THREAD

**Issue by wjk** [microsoft/CsWin32#79]
I am using CsWinRT as a means of implementing control-less rich text support for my application. This requires that I retrieve an instance of `ITextServices` (which is trivial), and provide an instance of `ITextHost`. This second one is a problem, because while CsWinRT can easily bind it, AFAIK the code generator can currently only generate code to call an interface, not to implement one. Therefore, this issue is a blocker for this project. Could you please look into this? Thanks!

(And, by the way, props for generating NativeAOT-compatible code. Much appreciated!)

**Comment by AArnott** [comment]
Great point about not being able to implement, door faces. That will fit as part of #26.
