### ISSUE TITLE
SHGetImageList outputs an object, but ImageList_GetIcon takes a SafeHandle or HIMAGELIST

### ISSUE THREAD

**Issue by palenshus** [microsoft/CsWin32#799]
## Actual behavior

I'm trying to call [ImageList::GetIcon](https://learn.microsoft.com/en-us/windows/win32/api/commoncontrols/nf-commoncontrols-iimagelist-geticon) using cswin32. I'm feeling around in the dark trying to figure out how to do that, here's what I'm trying:

```cs
const string IID_IImageList2 = "192B9D83-50FC-457B-90A0-2B82A8B5DAE1";
Guid guil = new Guid(IID_IImageList2);
PInvoke.SHGetImageList((int)PInvoke.SHIL_JUMBO, guil, out object ppvObj);
```

And now I'd like to call `PInvoke.ImageList_GetIcon`, except that takes a `SafeHandle` or an `HIMAGELIST`, and I'm not sure how to get one from that out object.

## Expected behavior

It'd be nice if SHGetImageList returned something that could just be passed to GetIcon

## Repro steps

1. `NativeMethods.txt` content:
```
SHGetImageList
ImageList_GetIcon
SHIL_JUMBO
```

3. Any of your own code that should be shared?

I'm able to workaround it by defining the IImageList interface and using my own GetIcon implementation:

```cs
((IImageList)ppvObj).GetIcon(iImage, (int)(IMAGE_LIST_DRAW_STYLE.ILD_TRANSPARENT | IMAGE_LIST_DRAW_STYLE.ILD_IMAGE), ref hIcon);

[ComImport]
[Guid("46EB5926-582E-4017-9FDF-E8998DAA0950")]
[InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
internal interface IImageList { ... }
```

### Context

- CsWin32 version: 0.2.138-beta
- Target Framework: net6.0-windows10.0.18362.0

**Comment by AArnott** [comment]
Thanks for your feedback.

You can drop the first two lines of code that hard-code the GUI in favor of the constant that CsWin32 can generated for you.
Then, because you asked for an `IImageList2`, you should then cast the `ppvObj` to it, and call GetIcon on that:

```cs
PInvoke.SHGetImageList((int)PInvoke.SHIL_JUMBO, typeof(IImageList2).GUID, out object ppvObj);
IImageList2 imageList = (IImageList2)ppvObj;
imageList.GetIcon(...)
```

> I'm able to workaround it by defining the IImageList interface and using my own GetIcon implementation:

Why would you define that interface yourself? CsWin32 can generated all these types for you if you add them to NativeMethods.txt.

**Comment by palenshus** [comment]
Ah, thank you @AArnott as always! I didn't realize cswin32 could generate those interfaces, and I found that ImageList_GetIcon in the generated PInvoke class so I assumed that was the "cswin32 way to do it". For anyone else coming here looking to do the same thing I'm doing, which is to get the large icon for a file type, here's my code:

```cs
using System.Drawing;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using Windows.Win32;
using Windows.Win32.Storage.FileSystem;
using Windows.Win32.UI.Controls;
using Windows.Win32.UI.Shell;

public static class IconHelper
{
    public static Bitmap GetIconForFileExtension(string extension)
    {
        extension = $"*.{extension.TrimStart('.')}";

        SHFILEINFOW sfi = default;
        SHGetFileInfo(extension, default, sfi, SHGFI_FLAGS.SHGFI_SYSICONINDEX | SHGFI_FLAGS.SHGFI_LARGEICON | SHGFI_FLAGS.SHGFI_USEFILEATTRIBUTES);

        using DestroyIconSafeHandle hIcon = GetJumboIcon(sfi.iIcon);

        // from native to managed
        using Icon icon = Icon.FromHandle(hIcon.DangerousGetHandle());
        var bitmap = icon.ToBitmap();
        return bitmap;
    }

    // 256*256
    private static DestroyIconSafeHandle GetJumboIcon(int iImage)
    {
        PInvoke.SHGetImageList((int)PInvoke.SHIL_JUMBO, typeof(IImageList2).GUID, out object ppvObj);
        ((IImageList2)ppvObj).GetIcon(iImage, (uint)(IMAGE_LIST_DRAW_STYLE.ILD_TRANSPARENT | IMAGE_LIST_DRAW_STYLE.ILD_IMAGE), out DestroyIconSafeHandle hIcon);
        Marshal.FinalReleaseComObject(ppvObj);
        return hIcon;
    }

    private static unsafe nuint SHGetFileInfo(string pszPath, FILE_FLAGS_AND_ATTRIBUTES dwFileAttributes, in SHFILEINFOW sfi, SHGFI_FLAGS uFlags)
    {
        var psfi = (SHFILEINFOW*)Unsafe.AsPointer(ref Unsafe.AsRef(sfi));
        fixed (char* pszPathLocal = pszPath)
        {
            return PInvoke.SHGetFileInfo(pszPathLocal, dwFileAttributes, psfi, (uint)Unsafe.SizeOf<SHFILEINFOW>(), uFlags);
        }
    }
}
```

NativeMethods.txt:
```txt
SHGetFileInfo
SHGetImageList

IImageList2

IMAGE_LIST_DRAW_STYLE
SHIL_JUMBO
```

**Comment by AArnott** [comment]
I'm glad you have it working. I'm curious why you got a pointer to `sfi` the hard way. Why not just do this?

```diff
-var psfi = (SHFILEINFOW*)Unsafe.AsPointer(ref Unsafe.AsRef(sfi));
+fixed (SHFILEINFOW* psfi = &sfi)
```

**Comment by palenshus** [comment]
I used your code from this answer :) https://github.com/microsoft/CsWin32/issues/361#issuecomment-901392857

**Comment by AArnott** [comment]
I fixed it there too then. I'm not even that clever. I must have copied it from someone else's code. :)
