### ISSUE TITLE
Nightly nuget server or public access to the CI-generated nuget packages?

### ISSUE THREAD

**Issue by dotMorten** [microsoft/CsWin32#80]
There's a lot of good and critical fixes that have gone in the past few weeks since this was first released.

I see there's an azure pipeline, but we're not allowed to access it so we can get at the latest packages.
Is there a public nightlies nuget server we can use?

**Comment by AArnott** [comment]
Closed by a339625

**Comment by AArnott** [comment]
Note the updated readme that tells where you can find daily builds on a public feed.
