### ISSUE TITLE
I didn't see the function SetWindowTopMost. So I suggest adding it.

### ISSUE THREAD

**Issue by laktarik** [microsoft/CsWin32#800]
public static void SetWindowTopMost()
    {
        IntPtr HWND_TOPMOST = new IntPtr(-1);
        const UInt32 SWP_NOSIZE = 0x0001;
        const UInt32 SWP_NOMOVE = 0x0002;
        const UInt32 SWP_SHOWWINDOW = 0x0040;
        Win32.SetWindowPos(hWnd, HWND_TOPMOST, 0, 0, 0, 0, SWP_NOMOVE | SWP_NOSIZE | SWP_SHOWWINDOW);
    }

**Comment by AArnott** [comment]
I don't see `SetWindowTopMost` in docs.microsoft.com or the win32metadata repo. It must be in win32metadata to be generated by cswin32. 
If you are confident this is actually a win32 SDK function (not just a macro or a useful utility method), then please file a bug in the microsoft/win32metadata repo to have the function added.
