### ISSUE TITLE
CreateWindowEx

### ISSUE THREAD

**Issue by Gavin-Williams** [microsoft/CsWin32#810]
CreateWindowEx is returning a zero handle with the following output...

An unhandled exception of type 'System.InvalidOperationException'
Failed to create window class. Error: 1401

// error 1401 / 0x579   ERROR_INVALID_MENU_HANDLE

I'm passing default as the menu handle. I don't see a problem with that, it's what I've been using.

Update: 
OK : 
    0.2.63
    0.2.104
NOT WORKING:
    0.2.138
    0.2.158

**Comment by Gavin-Williams** [comment]
I tried replacing default with GetWindowSafeHandle() but

```cs
private static SafeHandle GetWindowSafeHandle()
    {
        return null;
    }
```

**Comment by AArnott** [comment]
I don't know what you mean by replacing default with GetWindowSafeHandle which just returns null. That doesn't sound like a change at all. And where did you make this change?
I'm not familiar with this particular API. If you can provide a compilable repro case (following the issue template we created) I can probably help further.

**Comment by AArnott** [comment]
It looks like #760 probably regressed this by passing in -1 for hMenu instead of 0. I'll look more into this.
