### ISSUE TITLE
Generated output missing IDC_ARROW

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/CsWin32#822]
## Actual behavior

Trying to figure out what the current cursor loaded on screen is using [`GetCursorInfo`](https://learn.microsoft.com/windows/win32/api/winuser/nf-winuser-getcursorinfo). I think (though the documentation is unclear) that I can just compare the handle `HCURSOR` returned with one of the Macro values like `IDC_ARROW` or `IDC_SIZENS` as listed [here](https://learn.microsoft.com/windows/win32/api/winuser/nf-winuser-loadcursora).

However, while I see the generated `GetCursorInfo` function and `HCURSOR` structures, I don't see `IDC_ARROW` being generated. 

![image](https://user-images.githubusercontent.com/24302614/206062065-f6a9583b-407b-456d-90f7-33291b3513fc.png)

## Expected behavior

Would expect access to generated `IDC_ARROW` macro to be able to use.

I see that it's used in one of the test projects in this repo as an example, but don't know if that project is run/tested on the CI?

## Repro steps

1. `NativeMethods.txt` content:
```
GetClientRect
MapWindowPoints
GetCursorInfo
IDC_ARROW
MAKEINTRESOURCE
```

3. Any of your own code that should be shared?

```cs
        CURSORINFO curinfo = new()
        {
            cbSize = (uint)Marshal.SizeOf(typeof(CURSORINFO))
        };
        Assert.IsTrue(PInvoke.GetCursorInfo(ref curinfo), "Could not get current mouse cursor.");

        // Not really sure about this part either as can't find docs on this explicit scenario? But first issue is IDC_ARROW not generated.
        Assert.AreEqual(IDC_ARROW, curinfo.hCursor, "Current cursor isn't Arrow cursor.");
```

### Context

- CsWin32 version: 0.2.104-beta
- Win32Metadata version (if explicitly set by project): ?
- Target Framework: uap10.0.17763;net6.0-windows10.0.19041.0
- `LangVersion`: latest

**Comment by michael-hawker** [comment]
I'm wondering if I need to use `LoadCursor` to check the handles match? But `LoadCursor` seems to take a string and not an `int` as a 2nd argument. I see in the test the `IDC_ARROW` is cast to char/PCWSTR here:

https://github.com/microsoft/CsWin32/blob/14e48cf5e15420736f6409e66431eafa59a284ab/test/WinRTInteropTest/Program.cs#L39

I figured I could maybe try just doing this as I don't have `IDC_ARROW` currently:

```cs
HCURSOR arrowHandle = PInvoke.LoadCursor(null, "IDC_ARROW");
```

But I don't think it works, but it also doesn't want to cast the result to an `HCURSOR`...

As a C# dev needing to call Win32 APIs (especially now with the Windows App SDK), it's pretty confusing to understand how to use these functions still. Though maybe the underlying scenario I'm trying to achieve (check type of current mouse cursor on screen) is the tricky bit? I feel like that should be a common scenario for test development though.

**Comment by michael-hawker** [comment]
I went back today, and for some reason I do now see `PInvoke.IDC_ARROW` available, so I'm not sure what was happening.

I did also have to use `HINSTANCE` to make it work here:

```cs
var arrowCursor = PInvoke.LoadCursor(HINSTANCE.Null, PInvoke.IDC_ARROW);

Assert.AreEqual(arrowCursor, curinfo.hCursor, "Cursor wasn't arrow cursor.");
```

**Comment by AArnott** [comment]
Great. I'll close the issue then.
