### ISSUE TITLE
Shipping System.Memory in analyzer folder can cause other Source Generators to fail

### ISSUE THREAD

**Issue by hymccord** [microsoft/CsWin32#836]
This has been written up in two places already so I won't delve into detail here. The roslyn issue I wrote has the technical stuff.
Bringing up the issue here so it can be tracked if appropriate.

CommunityToolkit Issue: https://github.com/CommunityToolkit/dotnet/issues/493
Roslyn: https://github.com/dotnet/roslyn/issues/66104

## Actual behavior

Having both `CommunityToolkit.Mvvm` and `Microsoft.Windows.CsWin32` (since `v0.2.63-beta`), causes the CommunityTookit source generators to fail with a `MissingMethodException` in `System.Memory`.

## Expected behavior

Generators should play nice with each other and not cause IL generation to fail.

### Context

- CsWin32 version: `0.2.164-beta`
- Target Framework: `net7.0`

**Comment by AArnott** [comment]
We should review the lowest csc.exe version that we intend to support and review the version of System.Memory that it includes. If that version is one that CsWin32 can tolerate, we can drop shipping our own copy.
