### ISSUE TITLE
Visual Studio 2022 Integration?

### ISSUE THREAD

**Issue by lishinko** [microsoft/CsWin32#859]
## Actual behavior
using "生成解决方案(Generate Solution, Ctrl+Shift+B)" to compile a solution with 0.2188-beta attached to one of several csprojects failed with "namespace Windows not found",
while "dotnet run" compiles and runs fine

## Expected behavior
VS should compile the code

## Repro steps

1. `NativeMethods.txt` content:
```
GetWindowRect
PrintWindow
CreateRectRgn
GetWindowRgn
GetModuleHandle
```

2. `NativeMethods.json` content (if present):
```json
```

3. Any of your own code that should be shared?
https://github.com/lishinko/AppFrameworkCSharp/tree/main
https://github.com/lishinko/AppFrameworkCSharp/commit/b072d3bee00d100e37f46a8922507dc1c4f283d0
### Context

- CsWin32 version: [e.g. `0.2188-beta`]
- Win32Metadata version (if explicitly set by project):
- Target Framework: [e.g. `net 6.0`]
- `LangVersion` (if explicitly set by project): [e.g. `9`]

**Comment by AArnott** [comment]
Visual Studio integration should work. I cloned your repo and opened in VS and it worked right away:
![image](https://user-images.githubusercontent.com/3548/218632134-63635b42-b996-43fa-aa61-6fb8a7f48b0c.png)

**Comment by AArnott** [comment]
No, but I just tried it. That worked too.

```
========== Build: 4 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Build started at 2:42 PM and took 07.667 seconds ==========
```

That doesn't surprise me, because it looks like you're doing everything right, and CsWin32 is expected to work with VS2022. That's where I do all my development and testing.
