### ISSUE TITLE
Decorate relavant structures with DebuggerDisplayAttribute

### ISSUE THREAD

**Issue by vpenades** [microsoft/CsWin32#863]
**Is your feature request related to a problem? Please describe.**

Dealing with low level stuff is already very complex, and c# provides features to ease the burden.

One of those features is DebuggerDisplayAttribute.

**Describe the solution you'd like**

Decorate __char_80 , __char_260 and other relevant structures with [DebuggerDisplay] so they show meaningful data.

Right now, __char_80 and others only show the first letter.

**Describe alternatives you've considered**

-

**Additional context**

-

**Comment by AArnott** [comment]
I'm afraid that's a limitation of the VS debugger. Even if I add a `DebuggerDisplay` attribute, it too gets cut off after the first letter. I suspect it's because the API we call to render the data to a string triggers the debugger in some way to bail early.

**Comment by AArnott** [comment]
Nope. Evidently it's because the debugger executes the `DebuggerDisplay` (or ToString, which it does when `DebuggerDisplay` is not present) on a _copy_ of the struct, and it isn't smart enough to copy the entire struct. It only copies the first character in the fixed array. ;(

**Comment by AArnott** [comment]
I've reached out to the debugger team to see if there's a way we can make this work.

**Comment by vpenades** [comment]
maybe something like this would do?

```c#

[DebuggerDisplay("{_Internal_DebugText,nq}")]
struct __char_80 
{
    internal readonly string _Internal_DebugText
    {
        get
        {
             return "whatever";
        }
    }

}
```

theoretically, the "readonly" would prevent the compiler to create a defensive copy, but haven't tried myself

**Comment by AArnott** [comment]
The `readonly` doesn't have that effect, sadly. I've confirmed with the debugger team that this is their bug, as they don't handle fixed array fields properly.  

Internal bug tracking this: devdiv-1752489
