### ISSUE TITLE
Why is there a different CsWin32 generation for 2 structs in a Com method?

### ISSUE THREAD

**Issue by harborsiem** [microsoft/CsWin32#881]
I'm building a Com-Wrapper for UIRibbon.dll. In the UIRibbon is the Interface IUICommandHandler implemented, which has 2 methods.
I get the following generated code
```
[PreserveSig()]
unsafe winmdroot.Foundation.HRESULT Execute(uint commandId, winmdroot.UI.Ribbon.UI_EXECUTIONVERB verb, [Optional] winmdroot.UI.Shell.PropertiesSystem.PROPERTYKEY* key, in winmdroot.System.Com.StructuredStorage.PROPVARIANT currentValue, winmdroot.UI.Ribbon.IUISimplePropertySet commandExecutionProperties);

[PreserveSig()]
unsafe winmdroot.Foundation.HRESULT UpdateProperty(uint commandId, winmdroot.UI.Shell.PropertiesSystem.PROPERTYKEY* key, in winmdroot.System.Com.StructuredStorage.PROPVARIANT currentValue, out winmdroot.System.Com.StructuredStorage.PROPVARIANT newValue);
```
In the Execute method the parameter _key_ is marked with **Optional** and is generated as pointer, and the parameter _currentValue_ is a _in_ parameter. 
The same one can see in method UpdateProperty (here without **Optional** Attribute).
The key Parameter in both methods are never Optional and should be an _in_ parameter.
The currentValue in method Execute is **Optional** and may have a null value.

**Comment by AArnott** [comment]
> The key Parameter in both methods are never Optional and should be an in parameter.

Per the [docs for Execute](https://learn.microsoft.com/en-us/windows/win32/api/uiribbon/nf-uiribbon-iuicommandhandler-execute) the key *is* allowed to be null.

But the rest of what you said appears to be correct. The metadata does appear to be correct in all cases, so this is an oddity in CsWin32. I would expect all optional parameters to be declared as pointers instead of `in`, since `in` makes it very unintuitive to pass `null` in.
Thank you for this report.

**Comment by harborsiem** [comment]
@AArnott : Did you mean that the future implementation for COM- interface IUICommandHandler goes like this ?
```
            [PreserveSig()]
            unsafe winmdroot.Foundation.HRESULT Execute(uint commandId, winmdroot.UI.Ribbon.UI_EXECUTIONVERB verb, [Optional] winmdroot.UI.Shell.PropertiesSystem.PROPERTYKEY* key, [Optional] winmdroot.System.Com.StructuredStorage.PROPVARIANT* currentValue, winmdroot.UI.Ribbon.IUISimplePropertySet commandExecutionProperties);

            [PreserveSig()]
            unsafe winmdroot.Foundation.HRESULT UpdateProperty(uint commandId, in winmdroot.UI.Shell.PropertiesSystem.PROPERTYKEY key, [Optional] winmdroot.System.Com.StructuredStorage.PROPVARIANT* currentValue, out winmdroot.System.Com.StructuredStorage.PROPVARIANT newValue);

```
There are also some other interfaces affected by the current weird implementation with PROPERTYKEY, PROPVARIANT and GUID.
Interfaces: IPropertyStore, IPropertySystem, IUISimplePropertySet, IUIFramework, ...?

**Comment by AArnott** [comment]
Yes, just eye-balling it momentarily as you've written it, and re-reading my earlier response, yes I believe what you printed is what CsWin32 _should_ generate. Specifically, all optional parameters should take pointer types so that `null` can be passed in.
