### ISSUE TITLE
`PInvoke000`: `HLOCAL` return type not supported

### ISSUE THREAD

**Issue by alexrp** [microsoft/CsWin32#884]
## Actual behavior

`error PInvoke000: An internal error occurred: Failed while generating extern method: LocalFree. Failed while generating SafeHandle for LocalFree. Return type HLOCAL on release method LocalFree not supported.`

This happens when using `LocalFree` with newer Microsoft.Windows.SDK.Win32Metadata packages. Older packages were fine.

## Expected behavior

It should work.

## Repro steps

1. `NativeMethods.txt` content:
```
LocalFree
```

2. `NativeMethods.json` content (if present):
```json
{
  "className": "WindowsPInvoke",
  "allowMarshaling": false,
  "wideCharOnly": false,
  "emitSingleFile": true
}
```

### Context

- CsWin32 version: 0.2.188-beta
- Win32Metadata version (if explicitly set by project): 45.0.21-preview
- Target Framework: net7.0
- `LangVersion` (if explicitly set by project): latest

**Comment by AArnott** [comment]
Thanks for reporting. It's actually quite common for newer metadata versions to include breaking changes that CsWin32 must accommodate. We can keep this issue active till CsWin32 ships an update that references the new metadata.
