### ISSUE TITLE
Allow *not* generating documentation

### ISSUE THREAD

**Issue by colejohnson66** [microsoft/CsWin32#886]
**Is your feature request related to a problem? Please describe.**
When `<DocumentationFile>` contains a value in the `csproj` file, an XML documentation file is generated. However, this contains references to the *internal* functions inside the `PInvoke` class. It would be nice to have a way to not generate the API documentation comments if desired. It doesn't make sense to export documentation for internal APIs.

**Describe the solution you'd like**
A setting, in `NativeMethods.json` that provides a way to suppress doc comment generation.

**Describe alternatives you've considered**
A desire for a way to tell MSBuild itself to not generate documentation for `internal` APIs.

**Additional context**
None.

**Comment by AArnott** [comment]
I don't know why the C# compiler produces .xml documentation files that includes even private APIs (not just internal). 

But it's useful to have the xml doc comments generated because then you get Intellisense when calling those APIs within your project. Is this making your .xml file so large that it's a problem?

**Comment by colejohnson66** [comment]
Is that Roslyn or MSBuild doing that?

**Comment by AArnott** [comment]
It's roslyn. And they've converted all xml doc comments to the .xml file regardless of accessibility of the decorated member for as long as the C# compiler has been around, I believe.

**Comment by colejohnson66** [comment]
Ah, so this is a Roslyn issue then. I'll look there.

**Comment by AArnott** [comment]
@KalleOlaviNiemitalo Your `ExcludeAssets` technique is creative and probably a fine way to go.
I think you giving up friendly overloads altogether is a shame just to get rid of `inheritdoc` elements, which have no copyright significance. Of course, if you don't use the friendly overloads then by all means, feel free to turn them off to shrink your assembly size.
Regarding the remaining docs for `PCWSTR` and such, those come directly from CsWin32 itself and thus fall under the same copyright/license as the *code* generated by CsWin32 (which in short, is intended to not limit your use of the assembly at all).

**Comment by AArnott** [comment]
> There was a PCWSTR[] parameter and, although a friendly overload pinned the array, it did not pin the strings, and the application had to use GCHandle anyway.

A single `PCWSTR` should only ever be created over a pinned string anyway, since it's already a pointer at that point. If you have an array of unpinned strings, that's a bug in the code _before_ the friendly overload is ever called.
