### ISSUE TITLE
CreateFile no longer takes enum for dwDesiredAccess

### ISSUE THREAD

**Issue by User1785604260** [microsoft/CsWin32#893]
## Actual behavior

```CreateFile``` is now generated as:
```cs
public static unsafe Microsoft.Win32.SafeHandles.SafeFileHandle CreateFile(
string lpFileName,
uint dwDesiredAccess,
winmdroot.Storage.FileSystem.FILE_SHARE_MODE dwShareMode,
winmdroot.Security.SECURITY_ATTRIBUTES? lpSecurityAttributes,
winmdroot.Storage.FileSystem.FILE_CREATION_DISPOSITION dwCreationDisposition,
winmdroot.Storage.FileSystem.FILE_FLAGS_AND_ATTRIBUTES dwFlagsAndAttributes,
SafeHandle hTemplateFile)
```

with ```dwDesiredAccess``` no longer being an enum ```FILE_ACCESS_FLAGS```. The enum now appears to be named ```FILE_ACCESS_RIGHTS```, however.

## Expected behavior

```dwDesiredAccess``` is generated to take an enum:
```cs
public static unsafe Microsoft.Win32.SafeHandles.SafeFileHandle CreateFile(
string lpFileName,
winmdroot.Storage.FileSystem.FILE_ACCESS_RIGHTS dwDesiredAccess,
winmdroot.Storage.FileSystem.FILE_SHARE_MODE dwShareMode,
winmdroot.Security.SECURITY_ATTRIBUTES? lpSecurityAttributes,
winmdroot.Storage.FileSystem.FILE_CREATION_DISPOSITION dwCreationDisposition,
winmdroot.Storage.FileSystem.FILE_FLAGS_AND_ATTRIBUTES dwFlagsAndAttributes,
SafeHandle hTemplateFile)
```

## Repro steps

1. `NativeMethods.txt` content:
```
CreateFile
```

2. `NativeMethods.json` content (if present): n/a

3. Any of your own code that should be shared?

### Context

- CsWin32 version: 0.2.206-beta
- Win32Metadata version (if explicitly set by project): n/a
- Target Framework: net7.0-windows
- `LangVersion` (if explicitly set by project): n/a

**Comment by AArnott** [comment]
This is as intended. It feels like a takeback in the usability of the API, I agree, but we didn't have any great options. You should use `FILE_ACCESS_RIGHTS` and/or `GENERIC_ACCESS_RIGHTS` and cast to `uint`.

You can learn more about how we debated this over at https://github.com/microsoft/win32metadata/issues/1457.

**Comment by User1785604260** [comment]
Ahh, I didn't realize this was intentional.👍
