### ISSUE TITLE
Produce SafeHandle-derived types and accept SafeHandle base type

### ISSUE THREAD

**Issue by AArnott** [microsoft/CsWin32#9]
APIs should produce/return specific SafeHandle-derived types, but accept the base class SafeHandle for better interop with other systems pre-existing SafeHandle types.

i.e. project the parameter as SafeHandle and the return type as SafeFileHandle

**Comment by jnm2** [comment]
I'm concerned that I won't know which kind of handle to pass once I'm faced with parameters like `SafeHandle h` without spending extra time pulling up the docs.

**Comment by jnm2** [comment]
It's also not possible to do this anymore:

```cs
// Parameter: HCURSOR cursorHandle obtained from GetCursorInfo which returns it as an HCURSOR field of a struct

// ❌ CS0144 Cannot create an instance of the abstract type or interface 'SafeHandle'
//                       ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
if (!PInvoke.GetIconInfo(new(cursorHandle, ownsHandle: false), out var iconInfo)) throw new Win32Exception();
```

And there's no SafeHandle type available that is semantically correct to use here!
