### ISSUE TITLE
Unable to import IAntimalwareProvider::DisplayName

### ISSUE THREAD

**Issue by actionthomas** [microsoft/CsWin32#903]
## Actual behavior

Hello!
I'm trying to access [amsi.h](https://learn.microsoft.com/en-us/windows/win32/api/amsi/) methods and I can't find the way to use `IAntimalwareProvider::DisplayName`.

`warning PInvoke001: Method, type or constant "DisplayName" not found. Did you mean "MkParseDisplayName", "MkParseDisplayNameEx", "IParseDisplayName" or "GetServiceDisplayNameA"?`

The other `Amsi*` methods are available.

# Expected behavior

`DisplayName` method available to be called in C#

## Repro steps

1. `NativeMethods.txt` content:
```
AmsiCloseSession
AmsiInitialize
AmsiNotifyOperation
AmsiOpenSession
AmsiScanBuffer
AmsiScanString
AmsiUninitialize
AMSI_ATTRIBUTE
DisplayName
```

2. `NativeMethods.json` content (if present):
N/A

3. Any of your own code that should be shared?

### Context

- CsWin32 version: `0.2.206-beta`
- Win32Metadata version: `48.0.19-preview`
- Target Framework: `netstandard2.0`
- `LangVersion`: [e.g. `9`] `10.0`

**Comment by AArnott** [comment]
`IAntimalwareProvider` is an interface, as I'm sure you're aware. Why are you trying to add individual methods on that interface to this file? Try adding the interface name instead.

**Comment by AArnott** [comment]
Closing due to no response.
