### ISSUE TITLE
GetStdHandle shouldn't return a CloseHandleSafeHandle

### ISSUE THREAD

**Issue by deiruch** [microsoft/CsWin32#91]
Standard output handles should rarely be closed. Here's Raymond Chen's [explanation](https://devblogs.microsoft.com/oldnewthing/20130307-00/?p=5033). Thus, the proper way to use `GetStdHandle` is by combining it with `DangerousAddRef`:
```cs
var handle = PInvoke.GetStdHandle(STD_HANDLE_TYPE.STD_OUTPUT_HANDLE);
bool ignore=default;
handle.DangerousAddRef(ref ignore);
```

This could be simplified if `GetStdHandle` wouldn't return a `CloseHandleSafeHandle`.

**Comment by AArnott** [comment]
Great point. I filed https://github.com/microsoft/win32metadata/issues/244 against the metadata so we can do this along with other projections.

**Comment by AArnott** [comment]
Now that #143 is done, we actually *can* create `SafeHandle` instances with `ownsHandle: false` set on them.

**Comment by xPaw** [comment]
I'm curious, how are you expected to pass a handle from GetStdHandle into functions such as GetConsoleMode which expect SafeHandle?

Use SafeFileHandle or is there a better way of doing it?

```csharp
var @out = PInvoke.GetStdHandle(Windows.Win32.System.Console.STD_HANDLE.STD_OUTPUT_HANDLE);
var safeHandle = new Microsoft.Win32.SafeHandles.SafeFileHandle(@out, ownsHandle: false);
PInvoke.GetConsoleMode(safeHandle, out var mode);
```

**Comment by xPaw** [comment]
Ah that's the trick, thank you.
