### ISSUE TITLE
Generator 'SourceGenerator' failed to generate source.

### ISSUE THREAD

**Issue by L00pZBreak3r** [microsoft/CsWin32#915]
## Actual behavior

Generator 'SourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ArgumentException' with message 'An item with the same key has already been added.'

## Expected behavior

Successful compilation.

## Repro steps

1. `NativeMethods.txt` content:
```
CLSCTX
CoCreateInstance
CoTaskMemFree
ISpellChecker
ISpellCheckerFactory
S_FALSE
S_OK
SpellCheckerFactory
```

2. `NativeMethods.json` content (if present):
```json
{
  "$schema": "..\\..\\src\\Microsoft.Windows.CsWin32\\settings.schema.json"
}
```

3. Any of your own code that should be shared?

### Context

- CsWin32 version: 0.2.206-beta
- Win32Metadata version (if explicitly set by project): 49.0.21-preview
- Target Framework: netstandard2.0
- `LangVersion` (if explicitly set by project): [e.g. `9`]

**Comment by Marlax0** [comment]
I had the same problem when I added the `Microsoft.Windows.SDK.Win32Metadata` package (49.0.21-preview) to my project.
Removing it allowed the source generator to work again.

Not sure what the issue is.

**Comment by AArnott** [comment]
Each major version update of metadata carries with it the potential to break the source generator. We need a source generator update to get you to the latest metadata, evidently.
