### ISSUE TITLE
__char_260 (e.g.) is emitted in referenced projects, results in compilation failure

### ISSUE THREAD

**Issue by AliveDevil** [microsoft/CsWin32#918]
## Actual behavior

* Create LibA and ConsoleB
* Reference LibA in ConsoleB
* LibA imports `SHFILEINFOW`
* ConsoleB imports `DROPDESCRIPTION`
Observe error
```
CS0121	Der Aufruf unterscheidet nicht eindeutig zwischen den folgenden Methoden oder Eigenschaften: "Windows.Win32.InlineArrayIndexerExtensions.SliceAtNull(System.ReadOnlySpan<char>)" und "Windows.Win32.InlineArrayIndexerExtensions.SliceAtNull(System.ReadOnlySpan<char>)"
```

## Expected behavior

CsWin32 shouldn't emit `__char_260` in dependent projects, nor create `InlineArrayIndexerExtensions`, if already exists.

## Repro steps

1. `NativeMethods.txt` content:

LibA:
```
SHFILEINFOW
```
ConsoleB:
```
DROPDESCRIPTION
```

2. `NativeMethods.json` content (if present):
```json
{
  "$schema": "https://aka.ms/CsWin32.schema.json",
  "public": true
}
```

3. Any of your own code that should be shared?
[repro.zip](https://github.com/microsoft/CsWin32/files/11251083/repro.zip)

### Context

- CsWin32 version:  0.2.206-beta
- Target Framework: net7.0

**Comment by AArnott** [comment]
Thank you for the excellent report and repro.
