### ISSUE TITLE
CldApi CfExecute crashes the operating system (blue screen) on delete cancellation

### ISSUE THREAD

**Issue by maha-hari** [microsoft/CsWin32#920]
## Actual behavior

Under cloud sync root directory, CfExecute throws COMexception with HResult code -2147024498 for user-initiated cancellation for all operations except delete. In case of delete cancellation, the CfExecute crashes the operation system. Following is the error from mini dump. We import the cldapi.dll using System.Runtime.InteropServices. Is there a way to change or fix it?

KERNEL_SECURITY_CHECK_FAILURE (139)
A kernel component has corrupted a critical data structure.  The corruption
could potentially allow a malicious user to gain control of this machine.
Arguments:
Arg1: 0000000000000003, A LIST_ENTRY has been corrupted (i.e. double remove).
Arg2: ffff80086dbb69d0, Address of the trap frame for the exception that caused the BugCheck
Arg3: ffff80086dbb6928, Address of the exception record for the exception that caused the BugCheck
Arg4: 0000000000000000, Reserved

## Expected behavior

On user-initiated cancellation, CfExecute should throw COMexception with HResult code -2147024498 for all operations (including delete)

## Repro steps

1. Trigger a delete and cancel the delete by clicking the x.
2. The OS crashes and blue screen occurs

4. Any of your own code that should be shared?

### Context

- CsWin32 version: 0.2.206-beta
- Win32Metadata version (if explicitly set by project):
- Target Framework: net6.0-windows10.0.17763.0
- `LangVersion` (if explicitly set by project): [e.g. `9`]

**Comment by AArnott** [comment]
Are you reporting a bug in `CfExecute` itself? Because if you are, this repo isn't the way to do it. 
If the function works when called with the same inputs from C, and fails in C# using the APIs created by CsWin32, then we may have a CsWin32 bug here. But we'll need a repro, or you to show which API in the generated C# code is wrong compared to the C header files.

**Comment by maha-hari** [comment]
> Are you reporting a bug in `CfExecute` itself? Because if you are, this repo isn't the way to do it. If the function works when called with the same inputs from C, and fails in C# using the APIs created by CsWin32, then we may have a CsWin32 bug here. But we'll need a repro, or you to show which API in the generated C# code is wrong compared to the C header files.

Thank you for replying back! We also reported this under different forum and was able to repro this in C++ as well. So it turns out that it's not because of C# package issue. https://learn.microsoft.com/en-us/answers/questions/1257843/cldapi-cfexecute-crashes-the-operating-system-(blu

**Comment by AArnott** [comment]
Thanks for reporting back. I'll close this issue here then.
