### ISSUE TITLE
HINSTANCE is missing

### ISSUE THREAD

**Issue by harborsiem** [microsoft/CsWin32#924]
## Actual behavior

IUIFramework.LoadUI() first parameter "instance" now has the type "HMODULE".
CsWin32 version 0.2.223-beta had for the first parameter the type "HINSTANCE".

## Expected behavior

The [documentation](https://learn.microsoft.com/en-us/windows/win32/api/uiribbon/nf-uiribbon-iuiframework-loadui) and also the header file UiRibbon.h say that the first parameter type is a HINSTANCE

## Repro steps
```
IUIFramework Framework;
private void Method(HINSTANCE hInstance, string resourceIdent)
{
    Framework = new UIRibbonFramework() as IUIFramework;
    Framework.LoadUI(hInstance, resourceIdent);
}
```

1. `NativeMethods.txt` content:
```
UIRibbonFramework
IUIFramework

```

2. `NativeMethods.json` content (if present):
```json
```

3. Any of your own code that should be shared?

### Context

- CsWin32 version: [0.2.229-beta]
- Win32Metadata version (if explicitly set by project):
- Target Framework: [e.g. `netstandard2.0`]
- `LangVersion` (if explicitly set by project): [e.g. `9`]

**Comment by mikebattista** [comment]
Once https://github.com/microsoft/win32metadata/issues/1517 is fixed this will be resolved, but that fix is dependent on CsWin32 supporting implicit conversions between HMODULE and HINSTANCE.

**Comment by harborsiem** [comment]
It does not work in CsWin32 version 0.2.240-beta.

**Comment by AArnott** [comment]
@harborsiem, the fix requires a combination of CsWin32 changes (which you have) and the fix in the metadata (which has merged but has not yet shipped). Once those two things are available, CsWin32 will have to update to consume that metadata (or you could try referencing the latest metadata directly and you might get lucky).
