### ISSUE TITLE
Please don't add cast operators to System.Drawing types when System.Drawing is not installed

### ISSUE THREAD

**Issue by wherewhere** [microsoft/CsWin32#934]
## Actual behavior

![image](https://github.com/microsoft/CsWin32/assets/27689196/8a6f888d-44f1-493c-9d05-610a0d7441cb)

## Expected behavior

Don't generate it when System.Drawing is not installed.
It will be better if it can generate cast operators to Windows.Foundation
![image](https://github.com/microsoft/CsWin32/assets/27689196/ce519a98-b557-4e62-a448-5a2fadd3ffae)

## Repro steps

1. `NativeMethods.txt` content:
```
RECT
```

### Context

- CsWin32 version: 0.2.229-beta
- Win32Metadata version (if explicitly set by project): 49.0.21-preview
- Target Framework: uap10.0, netstandard1.1
- `LangVersion` (if explicitly set by project): 11

**Comment by wherewhere** [comment]
#626

**Comment by AArnott** [comment]
We should be able to suppress generation of these when the types it references aren't included in the compilation. Windows.Foundation cast operations is an option we could do when those types exist in the compilation as well.
