### ISSUE TITLE
'PInvoke' is inaccessible due to its protection level

### ISSUE THREAD

**Issue by ramjke** [microsoft/CsWin32#936]
## Actual behavior

<img width="569" alt="Screenshot 2023-05-20 at 17 43 15" src="https://github.com/microsoft/CsWin32/assets/45635648/f0fb2754-4e35-436a-80ab-566985e35f90">

**The build is successful**, but Visual Studio 17 shows an error: 'PInvoke' is inaccessible due to its protection level.

## Expected behavior

There should be no error.

## Repro steps

1. `NativeMethods.txt` content:
```
RegisterHotKey
UnregisterHotKey
GetSystemMetrics
DwmSetWindowAttribute
GetWindowLong
GetWindowLongPtr
GetWindowRect
SetLastError
SetWindowLongPtr
SetWindowLong
GetWindowRect
SetWindowPos
CallWindowProc
GetDpiForWindow
GetKeyboardLayout
GetWindowThreadProcessId
GetForegroundWindow
CreateEvent
SetEvent
CoWaitForMultipleObjects
SetForegroundWindow
```

2. `NativeMethods.json` content (if present):
```json
{
  "$schema": "https://aka.ms/CsWin32.schema.json",
  "public": true
}
```

3. Any of your own code that should be shared?

### Context

- CsWin32 version: 0.2.229-beta
- Win32Metadata version (if explicitly set by project):
- Target Framework: .NET6.0
- `LangVersion` (if explicitly set by project): 10

**Comment by AArnott** [comment]
Can you please attach a full repro? Your repro instructions don't include mention of two projects, but I can't imagine this failure without two projects being involved. In addition, the steps you _do_ include look correct (e.g. you set `public: true`) in the json file, so the APIs should be public, making me wonder if the error you see is coming from a different project that doesn't set that value. So a full repro is necessary to investigate this.

**Comment by AArnott** [comment]
Closing due to no response.

**Comment by Gavin-Williams** [comment]
I'm seeing it with one project.

**Comment by sakgoyal** [comment]
> making me wonder if the error you see is coming from a different project that doesn't set that value. 

Im running into the same issue. 
seems like I have a dependency that also uses this and explicitly sets public to false. Is there away around this?

I have `WinUIEx` as a dependency
https://github.com/dotMorten/WinUIEx/blob/main/src/WinUIEx/NativeMethods.json
