### ISSUE TITLE
Improve bit fields support

### ISSUE THREAD

**Issue by Nuklon** [microsoft/CsWin32#987]
## Actual behavior

This for example:
https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/d3dkmthk/ns-d3dkmthk-_d3dkmt_adaptertype

is generated as:
```csharp
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.3.18-beta+dc807e7787")]
		internal partial struct D3DKMT_ADAPTERTYPE
		{
			internal _Anonymous_e__Union Anonymous;

			[StructLayout(LayoutKind.Explicit)]
			[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.3.18-beta+dc807e7787")]
			internal partial struct _Anonymous_e__Union
			{
				[FieldOffset(0)]
				internal _Anonymous_e__Struct Anonymous;

				[FieldOffset(0)]
				internal uint Value;

				[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.3.18-beta+dc807e7787")]
				internal partial struct _Anonymous_e__Struct
				{
					internal uint _bitfield;
				}
			}
		}
```

## Expected behavior

Generate helpers around Value for RenderSupported, DisplaySupported, etc.

## Repro steps

1. `NativeMethods.txt` content:
```
D3DKMT_ADAPTERTYPE
```

### Context

- CsWin32 version: 0.3.18-beta+dc807e7787
- Target Framework: net 6.0
- `LangVersion` (if explicitly set by project): latest

**Comment by AArnott** [comment]
Reactivating because there is [lots to fix](https://github.com/microsoft/win32metadata/pull/1620#issuecomment-1894632690).
