### ISSUE TITLE
PInvoke007 - The API "IOCTL_*" is ambiguous. Please specify one of: "IOCTL_*" or "IOCTL_*".

### ISSUE THREAD

**Issue by Nuklon** [microsoft/CsWin32#988]
## Actual behavior

Doesn't build with the error. The "one of" are both identical. Weirdly it does generate the data.

## Expected behavior

Should work OK.

## Repro steps

1. `NativeMethods.txt` content:
```
IOCTL_*
```
### Context

- CsWin32 version: 0.3.18-beta+dc807e7787
- Target Framework: net 6.0
- `LangVersion` (if explicitly set by project): latest

**Comment by AArnott** [comment]
Thanks for the bug report. I can repro it.
